// typeship — account.
// Generated by typeship — https://typeship.dev — do not edit by hand.
package typeship

import (
	"context"
)

// AccountService accesses the account endpoints.
type AccountService struct {
	core *core
}

// Me — the account behind the presented credentials.
//
// Returns the account that owns the presented API key. This is also the
// identity endpoint the generated typeship CLI's `whoami` calls.
//
// GET /me
func (s *AccountService) Me(ctx context.Context, opts ...RequestOption) (*Account, error) {
	req := request{
		Method:     "GET",
		Path:       "/me",
		Errors:     map[string]func(int, []byte, string) error{"401": newUnauthorizedError},
		SchemaKey:  "account.me",
		Idempotent: true,
	}
	var out Account
	if err := s.core.do(ctx, req, &out, opts...); err != nil {
		return nil, err
	}
	return &out, nil
}
