// typeship — apiKeys.
// Generated by typeship — https://typeship.dev — do not edit by hand.
package typeship

import (
	"context"
	"fmt"
	"net/url"
)

// APIKeysService accesses the apiKeys endpoints.
type APIKeysService struct {
	core *core
}

// APIKeysListParams are the inputs for APIKeysService.List.
type APIKeysListParams struct {
	Limit  *int64  `json:"-"`
	Cursor *string `json:"-"`
}

// List API keys.
//
// Keys are never returned in full — only their identity and last four. Creation stays in the console deliberately: a leaked key that can mint more keys is a leaked account.
//
// GET /api_keys
//
// Returns an iterator that fetches pages lazily:
//
//	it := client.APIKeys.List(ctx, nil)
//	for it.Next() {
//		item := it.Value()
//	}
//	if err := it.Err(); err != nil { ... }
func (s *APIKeysService) List(ctx context.Context, params *APIKeysListParams, opts ...RequestOption) *Iter[APIKey] {
	query := map[string]any{}
	if params != nil {
		if params.Limit != nil {
			query["limit"] = *params.Limit
		}
		if params.Cursor != nil {
			query["cursor"] = *params.Cursor
		}
	}
	req := request{
		Method:     "GET",
		Path:       "/api_keys",
		Query:      query,
		Errors:     map[string]func(int, []byte, string) error{"401": newUnauthorizedError},
		SchemaKey:  "apiKeys.list",
		Idempotent: true,
	}
	return newIter[APIKey](ctx, s.core, req, opts, pageConfig{
		Style:           "cursor",
		ItemsField:      "data",
		CursorParam:     "cursor",
		NextCursorField: "next_cursor",
		LimitParam:      "limit",
	})
}

// Revoke an API key.
//
// Idempotent: revoking an already-revoked key returns the same body, so a rotation script that re-runs does not have to special-case having already succeeded.
//
// DELETE /api_keys/{api_key_id}
func (s *APIKeysService) Revoke(ctx context.Context, apiKeyID string, opts ...RequestOption) (*APIKey, error) {
	req := request{
		Method:     "DELETE",
		Path:       fmt.Sprintf("/api_keys/%s", url.PathEscape(apiKeyID)),
		Errors:     map[string]func(int, []byte, string) error{"401": newUnauthorizedError, "404": newNotFoundError},
		SchemaKey:  "apiKeys.revoke",
		Idempotent: true,
	}
	var out APIKey
	if err := s.core.do(ctx, req, &out, opts...); err != nil {
		return nil, err
	}
	return &out, nil
}
