// typeship — apiKeys.
// Generated by typeship — https://typeship.dev
package typeship

import (
	"context"
	"fmt"
	"net/url"
)

// APIKeysService accesses the apiKeys endpoints.
type APIKeysService struct {
	core *core
}

// APIKeysListParams are the inputs for APIKeysService.List.
type APIKeysListParams struct {
	// Limit Maximum number of resources to return. Omit for 20; otherwise supply base-10 digits representing an integer from 1 to 100. Empty, malformed, or out-of-range values return 400 input_invalid. List query parameters must appear only once; repeated or unrecognized parameters return 400 query_param_invalid.
	Limit *int64 `json:"-"`
	// Cursor Opaque cursor from the preceding page's next_cursor. Valid only for the same organization, operation, filters, and ordering that issued it. Omit to start at the first page. Empty or malformed cursors, and cursors issued for different filters, return 400 cursor_invalid; start again from the first page. Repeated cursors return 400 query_param_invalid. The page limit may change between requests.
	Cursor *string `json:"-"`
}

// APIKeysRevokeParams are the inputs for APIKeysService.Revoke.
type APIKeysRevokeParams struct {
	// IfMatch ETag from a preceding response. The write applies only if the resource still has that version; otherwise it returns 412 precondition_failed without changes. Omit to write the current version. See https://typeship.dev/docs/typeship-api#conditional-writes.
	IfMatch *string `json:"-"`
}

// List API keys.
//
// Lists key metadata and the last four characters of each key. Full keys are not returned. Create keys in the Console.
//
// GET /api-keys
//
// Returns an iterator that fetches pages lazily:
//
//	it := client.APIKeys.List(ctx, nil)
//	for it.Next() {
//		item := it.Value()
//	}
//	if err := it.Err(); err != nil { ... }
func (s *APIKeysService) List(ctx context.Context, params *APIKeysListParams, opts ...RequestOption) *Iter[APIKey] {
	query := map[string]any{}
	if params != nil {
		if params.Limit != nil {
			query["limit"] = *params.Limit
		}
		if params.Cursor != nil {
			query["cursor"] = *params.Cursor
		}
	}
	req := request{
		Method:     "GET",
		Path:       "/api-keys",
		Query:      query,
		Errors:     map[string]func(int, []byte, string) error{"400": newBadRequestError, "401": newUnauthorizedError, "403": newForbiddenError, "429": newRateLimitedError, "500": newInternalServerError},
		Security:   []map[string][]string{{"apiKey": {}}},
		SchemaKey:  "apiKeys.list",
		Idempotent: true,
	}
	return newIter[APIKey](ctx, s.core, req, opts, pageConfig{
		Style:           "cursor",
		ItemsField:      "data",
		CursorParam:     "cursor",
		NextCursorField: "next_cursor",
		HasMoreField:    "has_more",
		LimitParam:      "limit",
	})
}

// Get an API key.
//
// Returns the key summary and its ETag for conditional revocation.
//
// GET /api-keys/{api_key_id}
func (s *APIKeysService) Get(ctx context.Context, apiKeyID string, opts ...RequestOption) (*APIKeyResponse, error) {
	req := request{
		Method:     "GET",
		Path:       fmt.Sprintf("/api-keys/%s", url.PathEscape(apiKeyID)),
		Errors:     map[string]func(int, []byte, string) error{"401": newUnauthorizedError, "403": newForbiddenError, "404": newNotFoundError, "429": newRateLimitedError, "500": newInternalServerError},
		Security:   []map[string][]string{{"apiKey": {}}},
		SchemaKey:  "apiKeys.get",
		Idempotent: true,
	}
	var out APIKeyResponse
	if err := s.core.do(ctx, req, &out, opts...); err != nil {
		return nil, err
	}
	return &out, nil
}

// Revoke an API key.
//
// Revokes a key. Repeating the request returns the same result.
//
// With OAuth, members can revoke their own keys; organization admins can revoke any key. Organization API keys can revoke any key in their organization.
// See [conditional writes](https://typeship.dev/docs/typeship-api#conditional-writes) for ETag and If-Match.
//
// DELETE /api-keys/{api_key_id}
func (s *APIKeysService) Revoke(ctx context.Context, apiKeyID string, params *APIKeysRevokeParams, opts ...RequestOption) (*APIKeyResponse, error) {
	headers := map[string]string{}
	if params != nil {
		if params.IfMatch != nil {
			headers["If-Match"] = fmt.Sprint(*params.IfMatch)
		}
	}
	req := request{
		Method:     "DELETE",
		Path:       fmt.Sprintf("/api-keys/%s", url.PathEscape(apiKeyID)),
		Headers:    headers,
		Errors:     map[string]func(int, []byte, string) error{"400": newBadRequestError, "401": newUnauthorizedError, "403": newForbiddenError, "404": newNotFoundError, "412": newPreconditionFailedError, "429": newRateLimitedError, "500": newInternalServerError},
		Security:   []map[string][]string{{"apiKey": {}}},
		SchemaKey:  "apiKeys.revoke",
		Idempotent: true,
	}
	var out APIKeyResponse
	if err := s.core.do(ctx, req, &out, opts...); err != nil {
		return nil, err
	}
	return &out, nil
}
