// Package typeship is a typed, zero-dependency Go client for typeship.
// Generated by typeship — https://typeship.dev — do not edit by hand.
package typeship

import (
	"errors"
	"net/http"
	"os"
	"time"
)

// Version is this package's version, also sent as the User-Agent.
const Version = "0.8.0"

const userAgent = "typeship/0.8.0 (typeship)"

// Option configures a Client at construction.
type Option func(*core)

// WithBaseURL overrides the server URL from the spec.
func WithBaseURL(baseURL string) Option {
	return func(c *core) { c.baseURL = baseURL }
}

// WithHTTPClient supplies your own *http.Client — proxies, transports,
// connection pools, instrumentation. The client is copied, not mutated,
// and the copy drops credential headers on a cross-origin redirect; your
// own CheckRedirect still decides whether to follow.
func WithHTTPClient(client *http.Client) Option {
	return func(c *core) { c.httpClient = client }
}

// WithTimeout sets the per-attempt timeout, applied through the request
// context so it composes with whatever *http.Client you supply. Default: 30s.
func WithTimeout(d time.Duration) Option {
	return func(c *core) { c.timeout = d }
}

// WithMaxRetries sets retries after the first attempt. Default: 2.
func WithMaxRetries(n int) Option {
	return func(c *core) { c.maxRetries = n }
}

// WithRetryPolicy replaces the retry policy wholesale.
func WithRetryPolicy(policy RetryPolicy) Option {
	return func(c *core) { c.retry = policy }
}

// WithDebug receives one event per HTTP attempt. Events never carry
// headers or bodies, so this is safe to leave on.
func WithDebug(fn func(DebugEvent)) Option {
	return func(c *core) { c.debug = fn }
}

// WithOnRequest runs before every attempt; mutate the request to add
// tracing headers or inspect what is about to be sent.
func WithOnRequest(fn func(*http.Request)) Option {
	return func(c *core) { c.onRequest = fn }
}

// WithOnResponse runs after every HTTP response, before parsing and
// before retry decisions.
func WithOnResponse(fn func(*http.Response)) Option {
	return func(c *core) { c.onResponse = fn }
}

// WithValidation checks JSON request and response bodies against the
// spec's own schemas at runtime. Off by default; ValidateError returns
// a *ValidationError on mismatch, ValidateWarn reports through the
// debug sink and lets the call proceed. Catches drift the type system
// cannot see.
func WithValidation(mode ValidateMode) Option {
	return func(c *core) { c.validate = mode }
}

// WithOnError runs once per failed call, after retries are exhausted.
// Observability only: the error is returned unchanged.
func WithOnError(fn func(err error, method, path string)) Option {
	return func(c *core) { c.onError = fn }
}

// WithBearerToken sets the token sent as Authorization: Bearer.
func WithBearerToken(token string) Option {
	return func(c *core) { c.headers["Authorization"] = authValue{static: "Bearer " + token} }
}

// WithBearerTokenFunc resolves a token before every attempt, for
// credentials that expire.
func WithBearerTokenFunc(fn func() (string, error)) Option {
	return func(c *core) {
		c.headers["Authorization"] = authValue{fn: func() (string, error) {
			token, err := fn()
			if err != nil {
				return "", err
			}
			return "Bearer " + token, nil
		}}
	}
}

// Client is the entry point for typeship.
type Client struct {
	Generate            *GenerateService
	Projects            *ProjectsService
	Definitions         *DefinitionsService
	Targets             *TargetsService
	Generations         *GenerationsService
	DefinitionRevisions *DefinitionRevisionsService
	Account             *AccountService
	APIKeys             *APIKeysService

	core *core
}

// New builds a client. Credentials fall back to environment variables
// (TYPESHIP_TOKEN, TYPESHIP_BASE_URL) when no option supplies them.
func New(opts ...Option) (*Client, error) {
	c := &core{
		baseURL:     envOr("TYPESHIP_BASE_URL", "https://typeship.dev/api/v1"),
		httpClient:  &http.Client{},
		headers:     map[string]authValue{},
		query:       map[string]authValue{},
		userAgent:   userAgent,
		timeout:     30 * time.Second,
		maxRetries:  2,
		globalsVals: map[string]any{},
	}
	if token := os.Getenv("TYPESHIP_TOKEN"); token != "" {
		c.headers["Authorization"] = authValue{static: "Bearer " + token}
	}
	for _, opt := range opts {
		opt(c)
	}
	// Wraps whatever client the options left behind, ours or the caller's.
	c.httpClient = withRedirectPolicy(c.httpClient)
	if c.baseURL == "" {
		return nil, errors.New("no base URL: pass WithBaseURL or set TYPESHIP_BASE_URL")
	}
	client := &Client{core: c}
	client.Generate = &GenerateService{core: c}
	client.Projects = &ProjectsService{core: c}
	client.Definitions = &DefinitionsService{core: c}
	client.Targets = &TargetsService{core: c}
	client.Generations = &GenerationsService{core: c}
	client.DefinitionRevisions = &DefinitionRevisionsService{core: c}
	client.Account = &AccountService{core: c}
	client.APIKeys = &APIKeysService{core: c}
	return client, nil
}
