// Package typeship — HTTP transport.
// Generated by typeship — https://typeship.dev — do not edit by hand.
//
// Zero dependencies: built on net/http from the standard library.
package typeship

import (
	"bytes"
	"context"
	"crypto/rand"
	"encoding/json"
	"fmt"
	"io"
	"math"
	mathrand "math/rand"
	"mime/multipart"
	"net/http"
	"net/textproto"
	"net/url"
	"os"
	"reflect"
	"sort"
	"strconv"
	"strings"
	"time"
)

// DebugEvent is one HTTP attempt. It never carries headers or bodies, so a
// debug sink can be enabled in production without leaking credentials.
type DebugEvent struct {
	Method     string
	Path       string
	Status     int
	DurationMS int64
	Attempt    int
	RequestID  string
	Err        error
}

// RequestOption overrides client settings for a single call.
type RequestOption func(*requestConfig)

type requestConfig struct {
	timeout    time.Duration
	maxRetries *int
	headers    map[string]string
	response   *APIResponse
}

// APIResponse is the HTTP-level result of a call — status, headers, and
// the request id — for callers who need more than the decoded payload:
// rate-limit headers, a Location, a request id to quote in a bug report.
type APIResponse struct {
	StatusCode int
	Header     http.Header
	RequestID  string
}

// WithAPIResponse fills into with the metadata of the last HTTP response
// the call received, whether it succeeded or failed:
//
//	var resp acme.APIResponse
//	account, err := client.Accounts.Get(ctx, id, acme.WithAPIResponse(&resp))
//	fmt.Println(resp.Header.Get("X-RateLimit-Remaining"))
func WithAPIResponse(into *APIResponse) RequestOption {
	return func(c *requestConfig) { c.response = into }
}

// WithRequestTimeout overrides the per-attempt timeout for one call.
func WithRequestTimeout(d time.Duration) RequestOption {
	return func(c *requestConfig) { c.timeout = d }
}

// WithRequestMaxRetries overrides the retry count for one call.
func WithRequestMaxRetries(n int) RequestOption {
	return func(c *requestConfig) { c.maxRetries = &n }
}

// WithRequestHeader adds a header to one call.
func WithRequestHeader(name, value string) RequestOption {
	return func(c *requestConfig) {
		if c.headers == nil {
			c.headers = map[string]string{}
		}
		c.headers[name] = value
	}
}

// RetryPolicy tunes the retry behavior for a client or a single operation.
type RetryPolicy struct {
	MaxRetries         *int
	Statuses           []int
	InitialDelay       time.Duration
	MaxDelay           time.Duration
	RetryNonIdempotent bool
}

var defaultRetryStatuses = []int{408, 429, 500, 502, 503, 504}

type authValue struct {
	static string
	fn     func() (string, error)
}

func (a authValue) resolve() (string, error) {
	if a.fn != nil {
		return a.fn()
	}
	return a.static, nil
}

type core struct {
	baseURL     string
	httpClient  *http.Client
	headers     map[string]authValue
	query       map[string]authValue
	userAgent   string
	timeout     time.Duration
	maxRetries  int
	retry       RetryPolicy
	debug       func(DebugEvent)
	globalsVals map[string]any
	onRequest   func(*http.Request)
	onResponse  func(*http.Response)
	onError     func(error, string, string)
	validate    ValidateMode
}

// Ptr returns a pointer to v, for the optional fields and parameters this
// package models as pointers:
//
//	params.Limit = Ptr(int64(10))
func Ptr[T any](v T) *T { return &v }

// Nullable represents an optional JSON field with three states: omitted when
// the *Nullable is nil, explicit null from NullableNull, and a concrete value
// from NullableValue.
type Nullable[T any] struct {
	value T
	null  bool
}

// NullableValue returns a nullable field containing v.
func NullableValue[T any](v T) *Nullable[T] { return &Nullable[T]{value: v} }

// NullableNull returns a nullable field that marshals as JSON null.
func NullableNull[T any]() *Nullable[T] { return &Nullable[T]{null: true} }

// MarshalJSON preserves the explicit-null state on the wire.
func (n Nullable[T]) MarshalJSON() ([]byte, error) {
	if n.null {
		return []byte("null"), nil
	}
	return json.Marshal(n.value)
}

// ValidateMode controls optional runtime validation of JSON bodies
// against the spec's schemas.
type ValidateMode int

const (
	// ValidateOff is the default: no checking, no cost.
	ValidateOff ValidateMode = iota
	// ValidateError returns a *ValidationError when a body disagrees with
	// the spec.
	ValidateError
	// ValidateWarn reports through the debug sink and lets the call proceed.
	ValidateWarn
)

// request describes one API call. The generated service methods build it;
// callers never see it.
type request struct {
	Method            string
	Path              string
	Query             map[string]any
	Headers           map[string]string
	Body              any
	BodyKind          string
	ContentType       string
	Errors            map[string]func(int, []byte, string) error
	Idempotent        bool
	IdempotencyHeader string
	Retry             *RetryPolicy
	SchemaKey         string
}

func (c *core) do(ctx context.Context, req request, out any, opts ...RequestOption) error {
	cfg := &requestConfig{}
	for _, opt := range opts {
		opt(cfg)
	}
	policy := c.retry
	if req.Retry != nil {
		policy = mergeRetry(policy, *req.Retry)
	}
	attempts := c.maxRetries
	if policy.MaxRetries != nil {
		attempts = *policy.MaxRetries
	}
	// A per-call override wins over the operation policy and the client.
	if cfg.maxRetries != nil {
		attempts = *cfg.maxRetries
	}
	statuses := policy.Statuses
	if len(statuses) == 0 {
		statuses = defaultRetryStatuses
	}
	retryAllowed := req.Idempotent || req.Method == http.MethodGet || policy.RetryNonIdempotent
	// The per-attempt deadline: a per-call override, else the client's.
	timeout := cfg.timeout
	if timeout <= 0 {
		timeout = c.timeout
	}

	endpoint, err := c.buildURL(req.Path, req.Query)
	if err != nil {
		return err
	}
	payload, contentType, err := encodeBody(req.Body, req.BodyKind, req.ContentType)
	if err != nil {
		return err
	}

	var opSchema struct {
		Req json.RawMessage
		Res json.RawMessage
	}
	if c.validate != ValidateOff && req.SchemaKey != "" {
		loadSchemas()
		if entry, ok := schemas[req.SchemaKey]; ok {
			opSchema.Req, opSchema.Res = entry.Req, entry.Res
		}
	}
	if len(opSchema.Req) > 0 && req.Body != nil && req.BodyKind != "text" && req.BodyKind != "binary" && req.BodyKind != "multipart" {
		// A form body is validated in its JSON shape: the schema describes
		// the fields, not the wire encoding.
		jsonBody := payload
		if req.BodyKind == "form" {
			if jsonBody, err = json.Marshal(req.Body); err != nil {
				return err
			}
		}
		if err := c.validateBody("request", req.Method, req.Path, jsonBody, opSchema.Req); err != nil {
			return err
		}
	}

	// One key per logical call, reused across retries — the point of
	// idempotency keys.
	idempotencyKey := ""
	if req.IdempotencyHeader != "" {
		if _, ok := req.Headers[req.IdempotencyHeader]; !ok {
			idempotencyKey = newUUID()
		}
	}

	var lastErr error
	for attempt := 0; attempt <= attempts; attempt++ {
		httpReq, err := c.newRequest(ctx, req, endpoint, payload, contentType, idempotencyKey)
		if err != nil {
			return err
		}
		for name, value := range cfg.headers {
			httpReq.Header.Set(name, value)
		}

		started := time.Now()
		resp, body, err := c.attempt(ctx, httpReq, timeout)
		if resp == nil {
			lastErr = err
			c.emitDebug(DebugEvent{
				Method:     req.Method,
				Path:       req.Path,
				Attempt:    attempt + 1,
				DurationMS: time.Since(started).Milliseconds(),
				Err:        err,
			})
			if attempt < attempts && retryAllowed && ctx.Err() == nil {
				if sleepErr := sleepCtx(ctx, backoff(attempt, policy)); sleepErr != nil {
					return sleepErr
				}
				continue
			}
			transportErr := &TransportError{Method: req.Method, URL: endpoint, Err: err}
			if c.onError != nil {
				c.onError(transportErr, req.Method, req.Path)
			}
			return transportErr
		}
		readErr := err
		requestID := resp.Header.Get("X-Request-Id")
		if requestID == "" {
			requestID = resp.Header.Get("Request-Id")
		}
		if cfg.response != nil {
			*cfg.response = APIResponse{StatusCode: resp.StatusCode, Header: resp.Header.Clone(), RequestID: requestID}
		}
		c.emitDebug(DebugEvent{
			Method:     req.Method,
			Path:       req.Path,
			Status:     resp.StatusCode,
			Attempt:    attempt + 1,
			DurationMS: time.Since(started).Milliseconds(),
			RequestID:  requestID,
		})
		if readErr != nil {
			lastErr = readErr
			if attempt < attempts && retryAllowed {
				if sleepErr := sleepCtx(ctx, backoff(attempt, policy)); sleepErr != nil {
					return sleepErr
				}
				continue
			}
			return &TransportError{Method: req.Method, URL: endpoint, Err: readErr}
		}

		if resp.StatusCode >= 200 && resp.StatusCode < 300 {
			if len(opSchema.Res) > 0 && len(body) > 0 {
				if err := c.validateBody("response", req.Method, req.Path, body, opSchema.Res); err != nil {
					return err
				}
			}
			if out == nil || len(body) == 0 || resp.StatusCode == http.StatusNoContent {
				return nil
			}
			if err := decodeBody(body, resp.Header.Get("Content-Type"), out); err != nil {
				return fmt.Errorf("decode %s %s: %w", req.Method, req.Path, err)
			}
			return nil
		}

		// 429 is safe to retry for any verb; other retryable statuses only
		// when the call is idempotent.
		if attempt < attempts && containsInt(statuses, resp.StatusCode) && (retryAllowed || resp.StatusCode == 429) {
			wait := retryAfter(resp.Header.Get("Retry-After"))
			if wait == 0 {
				wait = backoff(attempt, policy)
			}
			if sleepErr := sleepCtx(ctx, wait); sleepErr != nil {
				return sleepErr
			}
			continue
		}

		apiErr := apiError(resp.StatusCode, body, requestID, req.Errors)
		if c.onError != nil {
			c.onError(apiErr, req.Method, req.Path)
		}
		return apiErr
	}

	return &TransportError{Method: req.Method, URL: endpoint, Err: lastErr}
}

func (c *core) newRequest(
	ctx context.Context,
	req request,
	endpoint string,
	payload []byte,
	contentType string,
	idempotencyKey string,
) (*http.Request, error) {
	var reader io.Reader
	if payload != nil {
		reader = bytes.NewReader(payload)
	}
	httpReq, err := http.NewRequestWithContext(ctx, req.Method, endpoint, reader)
	if err != nil {
		return nil, err
	}
	httpReq.Header.Set("User-Agent", c.userAgent)
	httpReq.Header.Set("Accept", "application/json")
	// Credentials resolve per attempt so callback-based tokens can refresh.
	for name, value := range c.headers {
		resolved, err := value.resolve()
		if err != nil {
			return nil, err
		}
		if resolved != "" {
			httpReq.Header.Set(name, resolved)
		}
	}
	if contentType != "" {
		httpReq.Header.Set("Content-Type", contentType)
	}
	if idempotencyKey != "" {
		httpReq.Header.Set(req.IdempotencyHeader, idempotencyKey)
	}
	for name, value := range req.Headers {
		if value != "" {
			httpReq.Header.Set(name, value)
		}
	}
	return httpReq, nil
}

// attempt performs one HTTP exchange under its own deadline and reads the
// whole body, so the deadline's cancel runs as soon as the attempt is over
// rather than piling up until the retry loop returns. A nil *http.Response
// means no response arrived at all.
func (c *core) attempt(ctx context.Context, httpReq *http.Request, timeout time.Duration) (*http.Response, []byte, error) {
	if timeout > 0 {
		attemptCtx, cancel := context.WithTimeout(ctx, timeout)
		defer cancel()
		httpReq = httpReq.WithContext(attemptCtx)
	}
	if c.onRequest != nil {
		c.onRequest(httpReq)
	}
	resp, err := c.httpClient.Do(httpReq)
	if err != nil {
		return nil, nil, err
	}
	if c.onResponse != nil {
		c.onResponse(resp)
	}
	body, readErr := io.ReadAll(resp.Body)
	resp.Body.Close()
	return resp, body, readErr
}

// decodeBody fills out from a success body. JSON is unmarshaled; a text or
// binary payload lands verbatim in a *string or *[]byte target.
func decodeBody(body []byte, contentType string, out any) error {
	switch target := out.(type) {
	case *[]byte:
		*target = body
		return nil
	case *string:
		if !strings.Contains(contentType, "json") {
			*target = string(body)
			return nil
		}
	case *json.RawMessage:
		*target = append((*target)[:0], body...)
		return nil
	}
	return json.Unmarshal(body, out)
}

func (c *core) emitDebug(event DebugEvent) {
	if c.debug != nil {
		c.debug(event)
	}
}

func (c *core) buildURL(path string, query map[string]any) (string, error) {
	endpoint := strings.TrimRight(c.baseURL, "/") + path
	values := url.Values{}
	for name, value := range c.query {
		resolved, err := value.resolve()
		if err != nil {
			return "", err
		}
		if resolved != "" {
			values.Set(name, resolved)
		}
	}
	encodeDeep(values, query)
	if len(values) == 0 {
		return endpoint, nil
	}
	sep := "?"
	if strings.Contains(endpoint, "?") {
		sep = "&"
	}
	return endpoint + sep + values.Encode(), nil
}

// encodeDeep flattens nested values into bracketed keys:
// {"created": {"gte": 5}} becomes created[gte]=5.
func encodeDeep(values url.Values, params map[string]any) {
	keys := make([]string, 0, len(params))
	for key := range params {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	for _, key := range keys {
		addDeep(values, key, params[key], true)
	}
}

func addDeep(values url.Values, key string, value any, top bool) {
	if value == nil {
		return
	}
	switch typed := value.(type) {
	case string:
		values.Add(key, typed)
	case bool:
		values.Add(key, strconv.FormatBool(typed))
	case int:
		values.Add(key, strconv.Itoa(typed))
	case int32:
		values.Add(key, strconv.FormatInt(int64(typed), 10))
	case int64:
		values.Add(key, strconv.FormatInt(typed, 10))
	case float64:
		values.Add(key, strconv.FormatFloat(typed, 'f', -1, 64))
	case time.Time:
		values.Add(key, typed.Format(time.RFC3339))
	case map[string]any:
		sub := make([]string, 0, len(typed))
		for k := range typed {
			sub = append(sub, k)
		}
		sort.Strings(sub)
		for _, k := range sub {
			addDeep(values, key+"["+k+"]", typed[k], false)
		}
	case []any:
		for i, item := range typed {
			if top {
				addDeep(values, key, item, false)
			} else {
				addDeep(values, key+"["+strconv.Itoa(i)+"]", item, false)
			}
		}
	case json.Number:
		values.Add(key, typed.String())
	default:
		// Pointers, slices, and named types (params structs, enums): go
		// through their JSON shape so a struct becomes key[field]=value and a
		// slice repeats the key, exactly like a literal map or slice would.
		generic, ok := jsonShape(typed)
		if !ok || generic == nil {
			return
		}
		switch generic.(type) {
		case map[string]any, []any, string, bool, json.Number:
			addDeep(values, key, generic, top)
		default:
			values.Add(key, fmt.Sprint(generic))
		}
	}
}

// jsonShape re-reads a value through encoding/json, so typed Go values take
// the same wire form as the generic maps and slices addDeep already handles.
// Numbers stay json.Number to keep 64-bit integers exact.
func jsonShape(value any) (any, bool) {
	encoded, err := json.Marshal(value)
	if err != nil {
		return nil, false
	}
	decoder := json.NewDecoder(bytes.NewReader(encoded))
	decoder.UseNumber()
	var generic any
	if err := decoder.Decode(&generic); err != nil {
		return nil, false
	}
	return generic, true
}

// Upload is a file for a multipart request: what the server receives as
// the file's name and content type, and where the bytes come from.
//
//	params.Document = &Upload{Name: "report.pdf", Reader: f}
type Upload struct {
	Name        string
	ContentType string
	Reader      io.Reader
}

// MarshalJSON keeps an Upload out of the JSON shape of a params struct: file
// parts are written separately by the multipart encoder.
func (u Upload) MarshalJSON() ([]byte, error) { return []byte("null"), nil }

func encodeBody(body any, kind string, contentType string) ([]byte, string, error) {
	if body == nil {
		return nil, "", nil
	}
	switch kind {
	case "form":
		values := url.Values{}
		if typed, ok := body.(map[string]any); ok {
			encodeDeep(values, typed)
		} else if generic, ok := jsonShape(body); ok {
			// A params struct: its JSON tags name the form fields.
			if fields, ok := generic.(map[string]any); ok {
				encodeDeep(values, fields)
			}
		}
		return []byte(values.Encode()), "application/x-www-form-urlencoded", nil
	case "multipart":
		return encodeMultipart(body)
	case "text":
		return []byte(fmt.Sprint(body)), "text/plain", nil
	case "binary":
		if contentType == "" {
			contentType = "application/octet-stream"
		}
		switch typed := body.(type) {
		case []byte:
			return typed, contentType, nil
		case io.Reader:
			// Read once up front so retries can resend the same bytes.
			raw, err := io.ReadAll(typed)
			if err != nil {
				return nil, "", fmt.Errorf("read request body: %w", err)
			}
			return raw, contentType, nil
		}
		fallthrough
	default:
		encoded, err := json.Marshal(body)
		if err != nil {
			return nil, "", fmt.Errorf("encode request body: %w", err)
		}
		// A nil params pointer means "no body", not a literal null.
		if string(encoded) == "null" {
			return nil, "", nil
		}
		return encoded, "application/json", nil
	}
}

// encodeMultipart writes a params struct (or map) as multipart/form-data:
// Upload fields become file parts, everything else becomes a text part under
// its JSON name, nested values as bracketed keys the way form bodies encode.
func encodeMultipart(body any) ([]byte, string, error) {
	var buf bytes.Buffer
	writer := multipart.NewWriter(&buf)
	files := collectFiles(body)
	if generic, ok := jsonShape(body); ok {
		if fields, ok := generic.(map[string]any); ok {
			values := url.Values{}
			encodeDeep(values, fields)
			keys := make([]string, 0, len(values))
			for key := range values {
				keys = append(keys, key)
			}
			sort.Strings(keys)
			for _, key := range keys {
				for _, value := range values[key] {
					if err := writer.WriteField(key, value); err != nil {
						return nil, "", err
					}
				}
			}
		}
	}
	for _, part := range files {
		header := textproto.MIMEHeader{}
		name := part.file.Name
		if name == "" {
			name = part.field
		}
		header.Set("Content-Disposition", fmt.Sprintf(`form-data; name="%s"; filename="%s"`, escapeQuotes(part.field), escapeQuotes(name)))
		contentType := part.file.ContentType
		if contentType == "" {
			contentType = "application/octet-stream"
		}
		header.Set("Content-Type", contentType)
		w, err := writer.CreatePart(header)
		if err != nil {
			return nil, "", err
		}
		if part.file.Reader != nil {
			if _, err := io.Copy(w, part.file.Reader); err != nil {
				return nil, "", fmt.Errorf("read %s: %w", part.field, err)
			}
		}
	}
	if err := writer.Close(); err != nil {
		return nil, "", err
	}
	return buf.Bytes(), writer.FormDataContentType(), nil
}

type filePart struct {
	field string
	file  Upload
}

// collectFiles finds the Upload-typed fields of a params struct (or the
// Upload values of a map), in declaration order, keyed by their JSON names.
func collectFiles(body any) []filePart {
	var parts []filePart
	value := reflect.ValueOf(body)
	for value.Kind() == reflect.Pointer || value.Kind() == reflect.Interface {
		if value.IsNil() {
			return nil
		}
		value = value.Elem()
	}
	asFile := func(v reflect.Value) (Upload, bool) {
		if v.Kind() == reflect.Pointer {
			if v.IsNil() {
				return Upload{}, false
			}
			v = v.Elem()
		}
		if v.Kind() == reflect.Interface {
			if v.IsNil() {
				return Upload{}, false
			}
			v = v.Elem()
			if v.Kind() == reflect.Pointer {
				if v.IsNil() {
					return Upload{}, false
				}
				v = v.Elem()
			}
		}
		if v.Type() == reflect.TypeOf(Upload{}) {
			return v.Interface().(Upload), true
		}
		return Upload{}, false
	}
	add := func(field string, v reflect.Value) {
		if file, ok := asFile(v); ok {
			parts = append(parts, filePart{field, file})
			return
		}
		if v.Kind() == reflect.Slice {
			for i := 0; i < v.Len(); i++ {
				if file, ok := asFile(v.Index(i)); ok {
					parts = append(parts, filePart{field, file})
				}
			}
		}
	}
	switch value.Kind() {
	case reflect.Struct:
		for i := 0; i < value.NumField(); i++ {
			field := value.Type().Field(i)
			if !field.IsExported() {
				continue
			}
			name := strings.Split(field.Tag.Get("json"), ",")[0]
			if name == "-" {
				continue
			}
			if name == "" {
				name = field.Name
			}
			add(name, value.Field(i))
		}
	case reflect.Map:
		keys := value.MapKeys()
		sort.Slice(keys, func(i, j int) bool { return keys[i].String() < keys[j].String() })
		for _, key := range keys {
			add(key.String(), value.MapIndex(key))
		}
	}
	return parts
}

func escapeQuotes(s string) string {
	return strings.NewReplacer("\\", "\\\\", `"`, "\\\"").Replace(s)
}

func mergeRetry(base, override RetryPolicy) RetryPolicy {
	if override.MaxRetries != nil {
		base.MaxRetries = override.MaxRetries
	}
	if len(override.Statuses) > 0 {
		base.Statuses = override.Statuses
	}
	if override.InitialDelay > 0 {
		base.InitialDelay = override.InitialDelay
	}
	if override.MaxDelay > 0 {
		base.MaxDelay = override.MaxDelay
	}
	if override.RetryNonIdempotent {
		base.RetryNonIdempotent = true
	}
	return base
}

func backoff(attempt int, policy RetryPolicy) time.Duration {
	initial := policy.InitialDelay
	if initial <= 0 {
		initial = 300 * time.Millisecond
	}
	maximum := policy.MaxDelay
	if maximum <= 0 {
		maximum = 10 * time.Second
	}
	cap := time.Duration(math.Min(float64(initial)*math.Pow(2, float64(attempt)), float64(maximum)))
	return time.Duration(mathrand.Int63n(int64(cap) + 1))
}

func retryAfter(header string) time.Duration {
	if header == "" {
		return 0
	}
	if seconds, err := strconv.ParseFloat(header, 64); err == nil {
		if seconds < 0 {
			return 0
		}
		if seconds > 60 {
			seconds = 60
		}
		return time.Duration(seconds * float64(time.Second))
	}
	if when, err := http.ParseTime(header); err == nil {
		wait := time.Until(when)
		if wait < 0 {
			return 0
		}
		if wait > time.Minute {
			wait = time.Minute
		}
		return wait
	}
	return 0
}

func sleepCtx(ctx context.Context, d time.Duration) error {
	if d <= 0 {
		return nil
	}
	timer := time.NewTimer(d)
	defer timer.Stop()
	select {
	case <-ctx.Done():
		return ctx.Err()
	case <-timer.C:
		return nil
	}
}

func containsInt(haystack []int, needle int) bool {
	for _, value := range haystack {
		if value == needle {
			return true
		}
	}
	return false
}

func newUUID() string {
	buf := make([]byte, 16)
	if _, err := rand.Read(buf); err != nil {
		return strconv.FormatInt(time.Now().UnixNano(), 16)
	}
	buf[6] = (buf[6] & 0x0f) | 0x40
	buf[8] = (buf[8] & 0x3f) | 0x80
	return fmt.Sprintf("%x-%x-%x-%x-%x", buf[0:4], buf[4:6], buf[6:8], buf[8:10], buf[10:16])
}

func envOr(name, fallback string) string {
	if value := os.Getenv(name); value != "" {
		return value
	}
	return fallback
}

// Dropped when a redirect crosses to another origin. net/http drops the
// standard names itself, but only when the target leaves the original parent
// domain, and it has never heard of the header this spec puts its key on: a
// Location pointing at object storage must not carry the credential to a host
// the spec never named.
var sensitiveHeaders = []string{"Authorization", "Cookie", "Cookie2", "Proxy-Authorization", "Www-Authenticate"}

// requestOrigin is scheme, host, and port — what has to match for a redirect
// to keep the credential. Compared exactly, as fetch does, rather than by
// parent domain as net/http does, so all three generated SDKs draw the line
// in the same place.
func requestOrigin(u *url.URL) string {
	port := u.Port()
	if port == "" {
		port = "80"
		if u.Scheme == "https" {
			port = "443"
		}
	}
	return strings.ToLower(u.Scheme) + "://" + strings.ToLower(u.Hostname()) + ":" + port
}

// withRedirectPolicy returns a copy of client that drops the credential
// headers when a redirect leaves the origin the request was made to. A copy,
// never a mutation: a client passed to WithHTTPClient belongs to the caller,
// and its own CheckRedirect still decides whether the redirect is followed.
//
// The comparison is against the first request, not the previous hop. net/http
// rebuilds every redirect's headers from the first request, so a hop that
// stays on a foreign origin (storage -> storage/region) would otherwise get
// the credential back after the hop before it had dropped it. The TypeScript
// and Python runtimes carry one header set through the chain and so compare
// hop to hop; here the chain is rebuilt from via[0] each time, and that is
// the origin the credential belongs to.
func withRedirectPolicy(client *http.Client) *http.Client {
	if client == nil {
		client = &http.Client{}
	}
	inner := client.CheckRedirect
	scoped := *client
	scoped.CheckRedirect = func(req *http.Request, via []*http.Request) error {
		if len(via) > 0 && requestOrigin(req.URL) != requestOrigin(via[0].URL) {
			for _, name := range sensitiveHeaders {
				req.Header.Del(name)
			}
		}
		if inner != nil {
			return inner(req, via)
		}
		if len(via) >= 10 {
			return fmt.Errorf("stopped after %d redirects", len(via))
		}
		return nil
	}
	return &scoped
}
