// typeship — definitions.
// Generated by typeship — https://typeship.dev — do not edit by hand.
package typeship

import (
	"context"
	"fmt"
	"net/url"
)

// DefinitionsService accesses the definitions endpoints.
type DefinitionsService struct {
	core *core
}

// Retrieve a Definition.
//
// GET /definitions/{definition_id}
func (s *DefinitionsService) Retrieve(ctx context.Context, definitionID string, opts ...RequestOption) (*Definition, error) {
	req := request{
		Method:     "GET",
		Path:       fmt.Sprintf("/definitions/%s", url.PathEscape(definitionID)),
		Errors:     map[string]func(int, []byte, string) error{"401": newUnauthorizedError, "403": newForbiddenError, "404": newNotFoundError, "429": newRateLimitedError},
		SchemaKey:  "definitions.retrieve",
		Idempotent: true,
	}
	var out Definition
	if err := s.core.do(ctx, req, &out, opts...); err != nil {
		return nil, err
	}
	return &out, nil
}

// Update and resolve a Definition.
//
// Resolves the complete document graph and records a new immutable revision before saving.
//
// PATCH /definitions/{definition_id}
func (s *DefinitionsService) Update(ctx context.Context, definitionID string, body DefinitionUpdateRequest, opts ...RequestOption) (*Definition, error) {
	req := request{
		Method:    "PATCH",
		Path:      fmt.Sprintf("/definitions/%s", url.PathEscape(definitionID)),
		Body:      body,
		Errors:    map[string]func(int, []byte, string) error{"400": newBadRequestError, "401": newUnauthorizedError, "403": newForbiddenError, "404": newNotFoundError, "422": newUnprocessableEntityError, "429": newRateLimitedError},
		SchemaKey: "definitions.update",
	}
	var out Definition
	if err := s.core.do(ctx, req, &out, opts...); err != nil {
		return nil, err
	}
	return &out, nil
}
