// typeship — definitionRevisions.
// Generated by typeship — https://typeship.dev — do not edit by hand.
package typeship

import (
	"context"
	"fmt"
	"net/url"
)

// DefinitionRevisionsService accesses the definitionRevisions endpoints.
type DefinitionRevisionsService struct {
	core *core
}

// DefinitionRevisionsListParams are the inputs for DefinitionRevisionsService.List.
type DefinitionRevisionsListParams struct {
	// Limit Maximum number of resources to return.
	Limit *int64 `json:"-"`
	// Cursor Opaque cursor from the preceding page's next_cursor.
	Cursor *string `json:"-"`
}

// List Definition Revisions.
//
// Immutable snapshots of the complete resolved document graph this Definition observed, newest first. Content is available from the revision and document endpoints and is never embedded in a list response.
//
// GET /definitions/{definition_id}/revisions
//
// Returns an iterator that fetches pages lazily:
//
//	it := client.DefinitionRevisions.List(ctx, id, nil)
//	for it.Next() {
//		item := it.Value()
//	}
//	if err := it.Err(); err != nil { ... }
func (s *DefinitionRevisionsService) List(ctx context.Context, definitionID string, params *DefinitionRevisionsListParams, opts ...RequestOption) *Iter[DefinitionRevision] {
	query := map[string]any{}
	if params != nil {
		if params.Limit != nil {
			query["limit"] = *params.Limit
		}
		if params.Cursor != nil {
			query["cursor"] = *params.Cursor
		}
	}
	req := request{
		Method:     "GET",
		Path:       fmt.Sprintf("/definitions/%s/revisions", url.PathEscape(definitionID)),
		Query:      query,
		Errors:     map[string]func(int, []byte, string) error{"400": newBadRequestError, "401": newUnauthorizedError, "403": newForbiddenError, "404": newNotFoundError, "429": newRateLimitedError},
		SchemaKey:  "definitionRevisions.list",
		Idempotent: true,
	}
	return newIter[DefinitionRevision](ctx, s.core, req, opts, pageConfig{
		Style:           "cursor",
		ItemsField:      "data",
		CursorParam:     "cursor",
		NextCursorField: "next_cursor",
		HasMoreField:    "has_more",
		LimitParam:      "limit",
	})
}

// Retrieve a Definition Revision.
//
// Metadata for one immutable resolved document graph. Fetch its canonical content or individual source documents from the content endpoints.
//
// GET /definition_revisions/{definition_revision_id}
func (s *DefinitionRevisionsService) Retrieve(ctx context.Context, definitionRevisionID string, opts ...RequestOption) (*DefinitionRevision, error) {
	req := request{
		Method:     "GET",
		Path:       fmt.Sprintf("/definition_revisions/%s", url.PathEscape(definitionRevisionID)),
		Errors:     map[string]func(int, []byte, string) error{"401": newUnauthorizedError, "403": newForbiddenError, "404": newNotFoundError, "429": newRateLimitedError},
		SchemaKey:  "definitionRevisions.retrieve",
		Idempotent: true,
	}
	var out DefinitionRevision
	if err := s.core.do(ctx, req, &out, opts...); err != nil {
		return nil, err
	}
	return &out, nil
}

// RetrieveContent — retrieve a Definition Revision's canonical content.
//
// Returns the exact canonical resolved content identified by the revision's graph digest, suitable for saving or piping into a diff.
//
// GET /definition_revisions/{definition_revision_id}/content
func (s *DefinitionRevisionsService) RetrieveContent(ctx context.Context, definitionRevisionID string, opts ...RequestOption) (string, error) {
	req := request{
		Method:     "GET",
		Path:       fmt.Sprintf("/definition_revisions/%s/content", url.PathEscape(definitionRevisionID)),
		Errors:     map[string]func(int, []byte, string) error{"401": newUnauthorizedError, "403": newForbiddenError, "404": newNotFoundError, "429": newRateLimitedError},
		SchemaKey:  "definitionRevisions.retrieveContent",
		Idempotent: true,
	}
	var out string
	if err := s.core.do(ctx, req, &out, opts...); err != nil {
		return "", err
	}
	return out, nil
}

// RetrieveDocumentContent — retrieve one source document from a Definition Revision.
//
// GET /definition_revisions/{definition_revision_id}/documents/{document_id}/content
func (s *DefinitionRevisionsService) RetrieveDocumentContent(ctx context.Context, definitionRevisionID string, documentID string, opts ...RequestOption) (string, error) {
	req := request{
		Method:     "GET",
		Path:       fmt.Sprintf("/definition_revisions/%s/documents/%s/content", url.PathEscape(definitionRevisionID), url.PathEscape(documentID)),
		Errors:     map[string]func(int, []byte, string) error{"401": newUnauthorizedError, "403": newForbiddenError, "404": newNotFoundError, "429": newRateLimitedError},
		SchemaKey:  "definitionRevisions.retrieveDocumentContent",
		Idempotent: true,
	}
	var out string
	if err := s.core.do(ctx, req, &out, opts...); err != nil {
		return "", err
	}
	return out, nil
}
