// typeship — definitions.
// Generated by typeship — https://typeship.dev
package typeship

import (
	"context"
	"fmt"
	"net/url"
)

// DefinitionsService accesses the definitions endpoints.
type DefinitionsService struct {
	core *core
}

// DefinitionsUpdateParams are the inputs for DefinitionsService.Update.
type DefinitionsUpdateParams struct {
	// IfMatch ETag from a preceding response. The write applies only if the resource still has that version; otherwise it returns 412 precondition_failed without changes. Omit to write the current version. See https://typeship.dev/docs/typeship-api#conditional-writes.
	IfMatch *string `json:"-"`
	// IdempotencyKey Identifies one logical write for 24 hours. The key is scoped to the authenticated account and operation; account-less generation uses a hashed network identity. Retrying the same method, path, query, If-Match header, and JSON body replays the original response. Reusing the key with changed intent returns 409. After expiry the key starts a new write.
	IdempotencyKey *string `json:"-"`
}

// Retrieve a Definition.
//
// GET /definitions/{definition_id}
func (s *DefinitionsService) Retrieve(ctx context.Context, definitionID string, opts ...RequestOption) (*Definition, error) {
	req := request{
		Method:     "GET",
		Path:       fmt.Sprintf("/definitions/%s", url.PathEscape(definitionID)),
		Errors:     map[string]func(int, []byte, string) error{"401": newUnauthorizedError, "403": newForbiddenError, "404": newNotFoundError, "429": newRateLimitedError, "500": newInternalServerError},
		Security:   []map[string][]string{{"apiKey": {}}},
		SchemaKey:  "definitions.retrieve",
		Idempotent: true,
	}
	var out Definition
	if err := s.core.do(ctx, req, &out, opts...); err != nil {
		return nil, err
	}
	return &out, nil
}

// Update and resolve a Definition.
//
// Resolves the source documents before saving the update and records a new Definition Revision when the source changes.
// Omitted fields remain unchanged; supplied objects and arrays replace the whole field.
// If the Definition or its Project configuration changes during validation, returns 409 definition_changed without saving the rejected update. Retrieve the current Definition and Project, reconcile your changes,
// and submit a new request with a new Idempotency-Key if using one.
//
// See [conditional writes](https://typeship.dev/docs/typeship-api#conditional-writes) for ETag and If-Match.
//
// PATCH /definitions/{definition_id}
func (s *DefinitionsService) Update(ctx context.Context, definitionID string, body DefinitionUpdateRequest, params *DefinitionsUpdateParams, opts ...RequestOption) (*Definition, error) {
	headers := map[string]string{}
	if params != nil {
		if params.IfMatch != nil {
			headers["If-Match"] = fmt.Sprint(*params.IfMatch)
		}
		if params.IdempotencyKey != nil {
			headers["Idempotency-Key"] = fmt.Sprint(*params.IdempotencyKey)
		}
	}
	req := request{
		Method:            "PATCH",
		Path:              fmt.Sprintf("/definitions/%s", url.PathEscape(definitionID)),
		Headers:           headers,
		Body:              body,
		Errors:            map[string]func(int, []byte, string) error{"400": newBadRequestError, "401": newUnauthorizedError, "403": newForbiddenError, "404": newNotFoundError, "409": newConflictError, "412": newPreconditionFailedError, "422": newUnprocessableEntityError, "429": newRateLimitedError, "500": newInternalServerError},
		Security:          []map[string][]string{{"apiKey": {}}},
		SchemaKey:         "definitions.update",
		IdempotencyHeader: "Idempotency-Key",
	}
	var out Definition
	if err := s.core.do(ctx, req, &out, opts...); err != nil {
		return nil, err
	}
	return &out, nil
}
