// typeship — definitionRevisions.
// Generated by typeship — https://typeship.dev
package typeship

import (
	"context"
	"fmt"
	"net/url"
)

// DefinitionRevisionsService accesses the definitionRevisions endpoints.
type DefinitionRevisionsService struct {
	core *core
}

// DefinitionRevisionsListParams are the inputs for DefinitionRevisionsService.List.
type DefinitionRevisionsListParams struct {
	// Limit Maximum number of resources to return. Omit for 20; otherwise supply base-10 digits representing an integer from 1 to 100. Empty, malformed, or out-of-range values return 400 invalid_request. List query parameters must appear only once; unrecognized parameters also return 400.
	Limit *int64 `json:"-"`
	// Cursor Opaque cursor from the preceding page's next_cursor. Valid only for the same account, operation, filters, and ordering that issued it. Omit to start at the first page. Empty, malformed, or repeated cursors return 400 invalid_request. The page limit may change between requests.
	Cursor *string `json:"-"`
}

// List Definition Revisions.
//
// Lists the Definition's revisions, newest first. Source content is not included; retrieve the revision content or individual documents separately.
//
// GET /definitions/{definition_id}/revisions
//
// Returns an iterator that fetches pages lazily:
//
//	it := client.DefinitionRevisions.List(ctx, id, nil)
//	for it.Next() {
//		item := it.Value()
//	}
//	if err := it.Err(); err != nil { ... }
func (s *DefinitionRevisionsService) List(ctx context.Context, definitionID string, params *DefinitionRevisionsListParams, opts ...RequestOption) *Iter[DefinitionRevision] {
	query := map[string]any{}
	if params != nil {
		if params.Limit != nil {
			query["limit"] = *params.Limit
		}
		if params.Cursor != nil {
			query["cursor"] = *params.Cursor
		}
	}
	req := request{
		Method:     "GET",
		Path:       fmt.Sprintf("/definitions/%s/revisions", url.PathEscape(definitionID)),
		Query:      query,
		Errors:     map[string]func(int, []byte, string) error{"400": newBadRequestError, "401": newUnauthorizedError, "403": newForbiddenError, "404": newNotFoundError, "429": newRateLimitedError, "500": newInternalServerError},
		Security:   []map[string][]string{{"apiKey": {}}},
		SchemaKey:  "definitionRevisions.list",
		Idempotent: true,
	}
	return newIter[DefinitionRevision](ctx, s.core, req, opts, pageConfig{
		Style:           "cursor",
		ItemsField:      "data",
		CursorParam:     "cursor",
		NextCursorField: "next_cursor",
		HasMoreField:    "has_more",
		LimitParam:      "limit",
	})
}

// Retrieve a Definition Revision.
//
// Returns metadata for a saved Definition Revision. Retrieve its resolved content or individual source documents separately.
//
// GET /definition-revisions/{definition_revision_id}
func (s *DefinitionRevisionsService) Retrieve(ctx context.Context, definitionRevisionID string, opts ...RequestOption) (*DefinitionRevisionResponse, error) {
	req := request{
		Method:     "GET",
		Path:       fmt.Sprintf("/definition-revisions/%s", url.PathEscape(definitionRevisionID)),
		Errors:     map[string]func(int, []byte, string) error{"401": newUnauthorizedError, "403": newForbiddenError, "404": newNotFoundError, "429": newRateLimitedError, "500": newInternalServerError},
		Security:   []map[string][]string{{"apiKey": {}}},
		SchemaKey:  "definitionRevisions.retrieve",
		Idempotent: true,
	}
	var out DefinitionRevisionResponse
	if err := s.core.do(ctx, req, &out, opts...); err != nil {
		return nil, err
	}
	return &out, nil
}

// RetrieveContent — retrieve a Definition Revision's canonical content.
//
// Returns the saved, resolved content for this revision. Save it locally or compare it with another revision.
//
// GET /definition-revisions/{definition_revision_id}/content
func (s *DefinitionRevisionsService) RetrieveContent(ctx context.Context, definitionRevisionID string, opts ...RequestOption) (string, error) {
	req := request{
		Method:     "GET",
		Path:       fmt.Sprintf("/definition-revisions/%s/content", url.PathEscape(definitionRevisionID)),
		Errors:     map[string]func(int, []byte, string) error{"401": newUnauthorizedError, "403": newForbiddenError, "404": newNotFoundError, "429": newRateLimitedError, "500": newInternalServerError},
		Security:   []map[string][]string{{"apiKey": {}}},
		SchemaKey:  "definitionRevisions.retrieveContent",
		Idempotent: true,
	}
	var out string
	if err := s.core.do(ctx, req, &out, opts...); err != nil {
		return "", err
	}
	return out, nil
}

// RetrieveDocumentContent — retrieve one source document from a Definition Revision.
//
// GET /definition-revisions/{definition_revision_id}/documents/{document_id}/content
func (s *DefinitionRevisionsService) RetrieveDocumentContent(ctx context.Context, definitionRevisionID string, documentID string, opts ...RequestOption) (string, error) {
	req := request{
		Method:     "GET",
		Path:       fmt.Sprintf("/definition-revisions/%s/documents/%s/content", url.PathEscape(definitionRevisionID), url.PathEscape(documentID)),
		Errors:     map[string]func(int, []byte, string) error{"401": newUnauthorizedError, "403": newForbiddenError, "404": newNotFoundError, "429": newRateLimitedError, "500": newInternalServerError},
		Security:   []map[string][]string{{"apiKey": {}}},
		SchemaKey:  "definitionRevisions.retrieveDocumentContent",
		Idempotent: true,
	}
	var out string
	if err := s.core.do(ctx, req, &out, opts...); err != nil {
		return "", err
	}
	return out, nil
}

// RetrieveDocument — retrieve a Definition Document.
//
// Returns metadata for one source document captured in a Definition Revision. Retrieve its content through the revision's document content endpoint. A document in another organization returns 404 not_found.
//
// GET /definition-documents/{definition_document_id}
func (s *DefinitionRevisionsService) RetrieveDocument(ctx context.Context, definitionDocumentID string, opts ...RequestOption) (*DefinitionDocumentResponse, error) {
	req := request{
		Method:     "GET",
		Path:       fmt.Sprintf("/definition-documents/%s", url.PathEscape(definitionDocumentID)),
		Errors:     map[string]func(int, []byte, string) error{"401": newUnauthorizedError, "403": newForbiddenError, "404": newNotFoundError, "429": newRateLimitedError, "500": newInternalServerError},
		Security:   []map[string][]string{{"apiKey": {}}},
		SchemaKey:  "definitionRevisions.retrieveDocument",
		Idempotent: true,
	}
	var out DefinitionDocumentResponse
	if err := s.core.do(ctx, req, &out, opts...); err != nil {
		return nil, err
	}
	return &out, nil
}
