// typeship — deliveries.
// Generated by typeship — https://typeship.dev
package typeship

import (
	"context"
	"fmt"
	"net/url"
)

// DeliveriesService accesses the deliveries endpoints.
type DeliveriesService struct {
	core *core
}

// DeliveriesListParams are the inputs for DeliveriesService.List.
type DeliveriesListParams struct {
	// Limit Maximum number of resources to return. Omit for 20; otherwise supply base-10 digits representing an integer from 1 to 100. Empty, malformed, or out-of-range values return 400 input_invalid. List query parameters must appear only once; repeated or unrecognized parameters return 400 query_param_invalid.
	Limit *int64 `json:"-"`
	// Cursor Opaque cursor from the preceding page's next_cursor. Valid only for the same organization, operation, filters, and ordering that issued it. Omit to start at the first page. Empty or malformed cursors, and cursors issued for different filters, return 400 cursor_invalid; start again from the first page. Repeated cursors return 400 query_param_invalid. The page limit may change between requests.
	Cursor *string `json:"-"`
	// TargetID Only Deliveries of this Target.
	TargetID *TargetID `json:"-"`
}

// List Deliveries.
//
// GET /deliveries
//
// Returns an iterator that fetches pages lazily:
//
//	it := client.Deliveries.List(ctx, nil)
//	for it.Next() {
//		item := it.Value()
//	}
//	if err := it.Err(); err != nil { ... }
func (s *DeliveriesService) List(ctx context.Context, params *DeliveriesListParams, opts ...RequestOption) *Iter[Delivery] {
	query := map[string]any{}
	if params != nil {
		if params.Limit != nil {
			query["limit"] = *params.Limit
		}
		if params.Cursor != nil {
			query["cursor"] = *params.Cursor
		}
		if params.TargetID != nil {
			query["target_id"] = *params.TargetID
		}
	}
	req := request{
		Method:     "GET",
		Path:       "/deliveries",
		Query:      query,
		Errors:     map[string]func(int, []byte, string) error{"400": newBadRequestError, "401": newUnauthorizedError, "403": newForbiddenError, "404": newNotFoundError, "429": newRateLimitedError, "500": newInternalServerError},
		Security:   []map[string][]string{{"apiKey": {}}},
		SchemaKey:  "deliveries.list",
		Idempotent: true,
	}
	return newIter[Delivery](ctx, s.core, req, opts, pageConfig{
		Style:           "cursor",
		ItemsField:      "data",
		CursorParam:     "cursor",
		NextCursorField: "next_cursor",
		HasMoreField:    "has_more",
		LimitParam:      "limit",
	})
}

// Get a Delivery.
//
// Returns the configured repository or hosted MCP Delivery for a Target. A Delivery in another organization returns 404 resource_not_found.
//
// GET /deliveries/{delivery_id}
func (s *DeliveriesService) Get(ctx context.Context, deliveryID string, opts ...RequestOption) (*DeliveryResponse, error) {
	req := request{
		Method:     "GET",
		Path:       fmt.Sprintf("/deliveries/%s", url.PathEscape(deliveryID)),
		Errors:     map[string]func(int, []byte, string) error{"401": newUnauthorizedError, "403": newForbiddenError, "404": newNotFoundError, "429": newRateLimitedError, "500": newInternalServerError},
		Security:   []map[string][]string{{"apiKey": {}}},
		SchemaKey:  "deliveries.get",
		Idempotent: true,
	}
	var out DeliveryResponse
	if err := s.core.do(ctx, req, &out, opts...); err != nil {
		return nil, err
	}
	return &out, nil
}
