// typeship — drafts.
// Generated by typeship — https://typeship.dev
package typeship

import (
	"context"
	"fmt"
	"net/url"
)

// DraftsService accesses the drafts endpoints.
type DraftsService struct {
	core *core
}

// DraftsListParams are the inputs for DraftsService.List.
type DraftsListParams struct {
	// Limit Maximum number of resources to return. Omit for 20; otherwise supply base-10 digits representing an integer from 1 to 100. Empty, malformed, or out-of-range values return 400 input_invalid. List query parameters must appear only once; repeated or unrecognized parameters return 400 query_param_invalid.
	Limit *int64 `json:"-"`
	// Cursor Opaque cursor from the preceding page's next_cursor. Valid only for the same organization, operation, filters, and ordering that issued it. Omit to start at the first page. Empty or malformed cursors, and cursors issued for different filters, return 400 cursor_invalid; start again from the first page. Repeated cursors return 400 query_param_invalid. The page limit may change between requests.
	Cursor *string `json:"-"`
	// TargetID Only Drafts of this Target.
	TargetID *TargetID `json:"-"`
	// Status Only Drafts with this status.
	Status *DraftStatus `json:"-"`
}

// DraftsUpdateParams are the inputs for DraftsService.Update.
type DraftsUpdateParams struct {
	// IfMatch ETag from a preceding response. The write applies only if the resource still has that version; otherwise it returns 412 precondition_failed without changes. Omit to write the current version. See https://typeship.dev/docs/typeship-api#conditional-writes.
	IfMatch *string `json:"-"`
}

// DraftsListFilesParams are the inputs for DraftsService.ListFiles.
type DraftsListFilesParams struct {
	// Filter conflicted: conflicts only. customized: files that differ from the last merged package. history: files affected by a default-branch history rewrite. Omit for conflicted and customized files.
	Filter *DraftsListFilesParamsFilter `json:"-"`
	// Limit Maximum number of resources to return. Omit for 20; otherwise supply base-10 digits representing an integer from 1 to 100. Empty, malformed, or out-of-range values return 400 input_invalid. List query parameters must appear only once; repeated or unrecognized parameters return 400 query_param_invalid.
	Limit *int64 `json:"-"`
	// Cursor Opaque cursor from the preceding page's next_cursor. Valid only for the same organization, operation, filters, and ordering that issued it. Omit to start at the first page. Empty or malformed cursors, and cursors issued for different filters, return 400 cursor_invalid; start again from the first page. Repeated cursors return 400 query_param_invalid. The page limit may change between requests.
	Cursor *string `json:"-"`
}

// List Drafts.
//
// Lists open and merged Drafts, newest first. Each Target has one open Draft; each merge adds a merged Draft.
//
// GET /drafts
//
// Returns an iterator that fetches pages lazily:
//
//	it := client.Drafts.List(ctx, nil)
//	for it.Next() {
//		item := it.Value()
//	}
//	if err := it.Err(); err != nil { ... }
func (s *DraftsService) List(ctx context.Context, params *DraftsListParams, opts ...RequestOption) *Iter[Draft] {
	query := map[string]any{}
	if params != nil {
		if params.Limit != nil {
			query["limit"] = *params.Limit
		}
		if params.Cursor != nil {
			query["cursor"] = *params.Cursor
		}
		if params.TargetID != nil {
			query["target_id"] = *params.TargetID
		}
		if params.Status != nil {
			query["status"] = *params.Status
		}
	}
	req := request{
		Method:     "GET",
		Path:       "/drafts",
		Query:      query,
		Errors:     map[string]func(int, []byte, string) error{"400": newBadRequestError, "401": newUnauthorizedError, "403": newForbiddenError, "404": newNotFoundError, "429": newRateLimitedError, "500": newInternalServerError},
		Security:   []map[string][]string{{"apiKey": {}}},
		SchemaKey:  "drafts.list",
		Idempotent: true,
	}
	return newIter[Draft](ctx, s.core, req, opts, pageConfig{
		Style:           "cursor",
		ItemsField:      "data",
		CursorParam:     "cursor",
		NextCursorField: "next_cursor",
		HasMoreField:    "has_more",
		LimitParam:      "limit",
	})
}

// Get a Draft.
//
// Returns the Draft's status. An open Draft also reports its typed reason when action is required, next version and its source, compatibility and version assessment, blocking errors, checks, and conflict counts. The response carries an `ETag`; send it in `If-Match` when updating the Draft to avoid changing a newer version selection.
//
// GET /drafts/{draft_id}
func (s *DraftsService) Get(ctx context.Context, draftID string, opts ...RequestOption) (*DraftResponse, error) {
	req := request{
		Method:     "GET",
		Path:       fmt.Sprintf("/drafts/%s", url.PathEscape(draftID)),
		Errors:     map[string]func(int, []byte, string) error{"401": newUnauthorizedError, "403": newForbiddenError, "404": newNotFoundError, "429": newRateLimitedError, "500": newInternalServerError},
		Security:   []map[string][]string{{"apiKey": {}}},
		SchemaKey:  "drafts.get",
		Idempotent: true,
	}
	var out DraftResponse
	if err := s.core.do(ctx, req, &out, opts...); err != nil {
		return nil, notModified(err)
	}
	return &out, nil
}

// Update a Draft.
//
// Checks your version choice against the required version bump, then regenerates the existing Draft pull request.
//
// Send the Draft's `ETag` in `If-Match` to reject an intervening change with 412 precondition_failed before saving or regenerating. Omitting `If-Match` applies the selection to the current Draft. version_next is required; null restores automatic selection.
//
// A `502` response means the selected version was saved, but regeneration failed. Follow the error's retryable and suggested_action fields. Repeating an unfinished selection resumes generation; repeating a completed selection starts no new work. If using If-Match, retrieve the Draft and confirm the saved selection before retrying with its current ETag.
// A `409 draft_merged` means the Draft merged; retrieve the Target and select a version on its `draft_id`. A `409 target_busy` means the Target is publishing; wait and retry. A `409 version_occupied` means the version is already released; retrieve the Draft and releases, choose a new version, and retry.
// See [conditional writes](https://typeship.dev/docs/typeship-api#conditional-writes) for ETag and If-Match.
//
// PATCH /drafts/{draft_id}
func (s *DraftsService) Update(ctx context.Context, draftID string, body DraftUpdateRequest, params *DraftsUpdateParams, opts ...RequestOption) (*DraftResponse, error) {
	headers := map[string]string{}
	if params != nil {
		if params.IfMatch != nil {
			headers["If-Match"] = fmt.Sprint(*params.IfMatch)
		}
	}
	req := request{
		Method:    "PATCH",
		Path:      fmt.Sprintf("/drafts/%s", url.PathEscape(draftID)),
		Headers:   headers,
		Body:      body,
		Errors:    map[string]func(int, []byte, string) error{"400": newBadRequestError, "401": newUnauthorizedError, "403": newForbiddenError, "404": newNotFoundError, "409": newConflictError, "412": newPreconditionFailedError, "422": newUnprocessableEntityError, "429": newRateLimitedError, "500": newInternalServerError, "502": newBadGatewayError},
		Security:  []map[string][]string{{"apiKey": {}}},
		SchemaKey: "drafts.update",
	}
	var out DraftResponse
	if err := s.core.do(ctx, req, &out, opts...); err != nil {
		return nil, notModified(err)
	}
	return &out, nil
}

// ListFiles — list a Draft's files.
//
// Lists the Draft's files that differ from the last merged package or need a conflict decision, ordered by path, without file content. Each conflict names its kind, the saved decision, and the sides you can read with getFile. With `filter=history`, lists files affected by a default-branch history rewrite; the list is empty when none is pending.
//
// Returns `409 resource_changed` while Typeship is carrying the Draft's latest commit forward (status working), or when the Draft changes between pages.
//
// GET /drafts/{draft_id}/files
//
// Returns an iterator that fetches pages lazily:
//
//	it := client.Drafts.ListFiles(ctx, id, nil)
//	for it.Next() {
//		item := it.Value()
//	}
//	if err := it.Err(); err != nil { ... }
func (s *DraftsService) ListFiles(ctx context.Context, draftID string, params *DraftsListFilesParams, opts ...RequestOption) *Iter[DraftFile] {
	query := map[string]any{}
	if params != nil {
		if params.Filter != nil {
			query["filter"] = *params.Filter
		}
		if params.Limit != nil {
			query["limit"] = *params.Limit
		}
		if params.Cursor != nil {
			query["cursor"] = *params.Cursor
		}
	}
	req := request{
		Method:     "GET",
		Path:       fmt.Sprintf("/drafts/%s/files", url.PathEscape(draftID)),
		Query:      query,
		Errors:     map[string]func(int, []byte, string) error{"400": newBadRequestError, "401": newUnauthorizedError, "403": newForbiddenError, "404": newNotFoundError, "409": newConflictError, "429": newRateLimitedError, "500": newInternalServerError},
		Security:   []map[string][]string{{"apiKey": {}}},
		SchemaKey:  "drafts.listFiles",
		Idempotent: true,
	}
	return newIter[DraftFile](ctx, s.core, req, opts, pageConfig{
		Style:           "cursor",
		ItemsField:      "data",
		CursorParam:     "cursor",
		NextCursorField: "next_cursor",
		HasMoreField:    "has_more",
		LimitParam:      "limit",
	})
}

// Resolve Draft conflicts.
//
// Resolves conflicts on the Draft's head_sha: keep yours or generated, or supply final content as text or, for binary files, base64. Choosing generated for a customized path replaces it with the generated file, or deletes a Draft-only file.
//
// Conflict decisions are saved together and can be replaced until applied. Choosing generated for customized paths commits those changes together on the Draft branch. Returns the Draft. When every conflict has a decision, `conflicts.decided` equals `conflicts.total` and Typeship continues the Draft and runs checks. Paths that already match the Draft change nothing.
//
// POST /drafts/{draft_id}/resolve
func (s *DraftsService) Resolve(ctx context.Context, draftID string, body DraftResolveRequest, opts ...RequestOption) (*DraftResponse, error) {
	req := request{
		Method:    "POST",
		Path:      fmt.Sprintf("/drafts/%s/resolve", url.PathEscape(draftID)),
		Body:      body,
		Errors:    map[string]func(int, []byte, string) error{"400": newBadRequestError, "401": newUnauthorizedError, "403": newForbiddenError, "404": newNotFoundError, "409": newConflictError, "429": newRateLimitedError, "500": newInternalServerError},
		Security:  []map[string][]string{{"apiKey": {}}},
		SchemaKey: "drafts.resolve",
	}
	var out DraftResponse
	if err := s.core.do(ctx, req, &out, opts...); err != nil {
		return nil, notModified(err)
	}
	return &out, nil
}

// Recover a Draft's history.
//
// When the Draft has status `action_required` and reason `history_rewritten`, review affected files with `listDraftFiles` and `filter=history`, then approve with the Draft's `history_recovery` revisions. Approval saves the recovery without changing Git and returns the Draft; the next generation rebuilds it from the rewritten default branch. The previous Draft branch stays available, and overlapping code comes back as conflicts to resolve. A rewritten Draft branch alone needs no approval.
//
// POST /drafts/{draft_id}/recover
func (s *DraftsService) Recover(ctx context.Context, draftID string, body DraftRecoverRequest, opts ...RequestOption) (*DraftResponse, error) {
	req := request{
		Method:    "POST",
		Path:      fmt.Sprintf("/drafts/%s/recover", url.PathEscape(draftID)),
		Body:      body,
		Errors:    map[string]func(int, []byte, string) error{"400": newBadRequestError, "401": newUnauthorizedError, "403": newForbiddenError, "404": newNotFoundError, "409": newConflictError, "429": newRateLimitedError, "500": newInternalServerError},
		Security:  []map[string][]string{{"apiKey": {}}},
		SchemaKey: "drafts.recover",
	}
	var out DraftResponse
	if err := s.core.do(ctx, req, &out, opts...); err != nil {
		return nil, notModified(err)
	}
	return &out, nil
}
