// typeship — typed error responses.
// Generated by typeship — https://typeship.dev — do not edit by hand.
package typeship

import "fmt"

// UnauthorizedError is returned for 401 responses. Missing or invalid API key.
type UnauthorizedError struct {
	APIError
}

// Unwrap returns the underlying *APIError, so errors.As can match either type.
func (e *UnauthorizedError) Unwrap() error { return &e.APIError }

// PayloadTooLargeError is returned for 413 responses. Spec exceeds the 10MB limit.
type PayloadTooLargeError struct {
	APIError
}

// Unwrap returns the underlying *APIError, so errors.As can match either type.
func (e *PayloadTooLargeError) Unwrap() error { return &e.APIError }

// UnprocessableEntityError is returned for 422 responses. The spec could not be understood.
type UnprocessableEntityError struct {
	APIError
}

// Unwrap returns the underlying *APIError, so errors.As can match either type.
func (e *UnprocessableEntityError) Unwrap() error { return &e.APIError }

// APIResponseError is returned for default responses. Unexpected error.
type APIResponseError struct {
	APIError
}

// Unwrap returns the underlying *APIError, so errors.As can match either type.
func (e *APIResponseError) Unwrap() error { return &e.APIError }

// BadRequestError is returned for 400 responses. Invalid name, spec source, or field value.
type BadRequestError struct {
	APIError
}

// Unwrap returns the underlying *APIError, so errors.As can match either type.
func (e *BadRequestError) Unwrap() error { return &e.APIError }

// PaymentRequiredError is returned for 402 responses. The plan does not include another project or the requested output configuration.
type PaymentRequiredError struct {
	APIError
}

// Unwrap returns the underlying *APIError, so errors.As can match either type.
func (e *PaymentRequiredError) Unwrap() error { return &e.APIError }

// NotFoundError is returned for 404 responses. No such resource in this account.
type NotFoundError struct {
	APIError
}

// Unwrap returns the underlying *APIError, so errors.As can match either type.
func (e *NotFoundError) Unwrap() error { return &e.APIError }

// InternalServerError is returned for 500 responses. Generation or pull-request setup failed unexpectedly.
type InternalServerError struct {
	APIError
}

// Unwrap returns the underlying *APIError, so errors.As can match either type.
func (e *InternalServerError) Unwrap() error { return &e.APIError }

// apiError maps a status onto the documented error type for an operation.
func apiError(status int, body []byte, requestID string, errs map[string]func(int, []byte, string) error) error {
	base := APIError{Status: status, Body: body, RequestID: requestID, Message: messageFromBody(body)}
	if errs != nil {
		keys := []string{fmt.Sprintf("%d", status), fmt.Sprintf("%dXX", status/100), "default"}
		for _, key := range keys {
			if ctor, ok := errs[key]; ok {
				return ctor(status, body, requestID)
			}
		}
	}
	return &base
}

func newUnauthorizedError(status int, body []byte, requestID string) error {
	return &UnauthorizedError{APIError: APIError{Status: status, Body: body, RequestID: requestID, Message: messageFromBody(body)}}
}

func newPayloadTooLargeError(status int, body []byte, requestID string) error {
	return &PayloadTooLargeError{APIError: APIError{Status: status, Body: body, RequestID: requestID, Message: messageFromBody(body)}}
}

func newUnprocessableEntityError(status int, body []byte, requestID string) error {
	return &UnprocessableEntityError{APIError: APIError{Status: status, Body: body, RequestID: requestID, Message: messageFromBody(body)}}
}

func newAPIResponseError(status int, body []byte, requestID string) error {
	return &APIResponseError{APIError: APIError{Status: status, Body: body, RequestID: requestID, Message: messageFromBody(body)}}
}

func newBadRequestError(status int, body []byte, requestID string) error {
	return &BadRequestError{APIError: APIError{Status: status, Body: body, RequestID: requestID, Message: messageFromBody(body)}}
}

func newPaymentRequiredError(status int, body []byte, requestID string) error {
	return &PaymentRequiredError{APIError: APIError{Status: status, Body: body, RequestID: requestID, Message: messageFromBody(body)}}
}

func newNotFoundError(status int, body []byte, requestID string) error {
	return &NotFoundError{APIError: APIError{Status: status, Body: body, RequestID: requestID, Message: messageFromBody(body)}}
}

func newInternalServerError(status int, body []byte, requestID string) error {
	return &InternalServerError{APIError: APIError{Status: status, Body: body, RequestID: requestID, Message: messageFromBody(body)}}
}
