// Package typeship — error types.
// Generated by typeship — https://typeship.dev
package typeship

import (
	"encoding/json"
	"fmt"
	"math"
	"net/http"
	"strconv"
	"strings"
	"time"
)

// APIError is any error response from the API. Every generated per-status
// type embeds it, so errors.As works at whichever precision you need:
//
//	var notFound *NotFoundError
//	if errors.As(err, &notFound) { ... }
//
//	var apiErr *APIError
//	if errors.As(err, &apiErr) { fmt.Println(apiErr.Status) }
type APIError struct {
	Code      string
	Status    int
	Body      []byte
	RequestID string
	Message   string
	// RateLimit is set when the API said the call was rate limited (a 429,
	// or a 403 whose headers say the quota is spent): when to retry.
	RateLimit *RateLimit
}

func (e *APIError) Error() string {
	msg := fmt.Sprintf("http %d", e.Status)
	if e.Message != "" {
		// An API message usually ends its own sentence; do not double it.
		msg += ": " + strings.TrimRight(e.Message, ".!?")
	}
	if e.RequestID != "" {
		msg += " (request " + e.RequestID + ")"
	}
	if e.RateLimit != nil {
		return msg + ". " + e.RateLimit.step()
	}
	return msg + ". " + nextStep(e.Status)
}

// apiErr exposes the embedded *APIError of every generated error type.
func (e *APIError) apiErr() *APIError { return e }

// RateLimit says when a rate-limited call can be retried. RetryAt and
// RetryAfter are nil when the API did not say.
type RateLimit struct {
	// RetryAt is when the limit resets (Retry-After or x-ratelimit-reset).
	RetryAt *time.Time
	// RetryAfter is the wait from when the response arrived until RetryAt.
	RetryAfter *time.Duration
}

func (r *RateLimit) step() string {
	if r.RetryAt == nil {
		return "Rate limited: wait before retrying."
	}
	// Round up to the second so "wait until" is never early.
	at := r.RetryAt.UTC()
	if at.Nanosecond() > 0 {
		at = at.Truncate(time.Second).Add(time.Second)
	}
	return "Rate limited: wait until " + at.Format("2006-01-02T15:04:05Z") + ", then retry."
}

// rateLimitInfo reports whether a response is a rate limit, and when to
// retry. A 429 always is; a 403 is when it says the quota is spent
// (x-ratelimit-remaining: 0) or asks the caller to wait (Retry-After), which
// is how GitHub signals its limits. Nil for every other response.
func rateLimitInfo(status int, header http.Header, now time.Time) *RateLimit {
	retryAfter := strings.TrimSpace(header.Get("Retry-After"))
	remaining := header.Get("X-Ratelimit-Remaining")
	if remaining == "" {
		remaining = header.Get("Ratelimit-Remaining")
	}
	limited := status == 429 || (status == 403 && (header.Get("Retry-After") != "" || strings.TrimSpace(remaining) == "0"))
	if !limited {
		return nil
	}
	var wait *time.Duration
	if retryAfter != "" {
		if seconds, err := strconv.ParseFloat(retryAfter, 64); err == nil {
			d := time.Duration(math.Max(seconds, 0) * float64(time.Second))
			wait = &d
		} else if when, err := http.ParseTime(retryAfter); err == nil {
			d := when.Sub(now)
			if d < 0 {
				d = 0
			}
			wait = &d
		}
	}
	reset := strings.TrimSpace(header.Get("X-Ratelimit-Reset"))
	if reset == "" {
		reset = strings.TrimSpace(header.Get("Ratelimit-Reset"))
	}
	if wait == nil && reset != "" {
		if value, err := strconv.ParseFloat(reset, 64); err == nil {
			// An epoch timestamp (GitHub) or seconds until the reset (IETF).
			var d time.Duration
			if value > 1e9 {
				d = time.Unix(0, int64(value*float64(time.Second))).Sub(now)
			} else {
				d = time.Duration(value * float64(time.Second))
			}
			if d < 0 {
				d = 0
			}
			wait = &d
		}
	}
	if wait == nil {
		return &RateLimit{}
	}
	at := now.Add(*wait)
	return &RateLimit{RetryAt: &at, RetryAfter: wait}
}

// RateLimitError is a rate-limited call: a 403 whose headers say the quota
// is spent, or a 429 the spec did not document. RateLimit.RetryAt says when
// to try again; every APIError carries RateLimit when it applies.
type RateLimitError struct {
	APIError
}

// Unwrap returns the underlying *APIError, so errors.As can match either type.
func (e *RateLimitError) Unwrap() error { return &e.APIError }

// PayloadError is a 2xx response whose payload reported a failure: a
// declared envelope flag set to false ({"ok": false}, {"success": false}),
// or a GraphQL result that is one of the schema's error types (Typename).
type PayloadError struct {
	APIError
	// Typename is the GraphQL error type the result resolved to, if any.
	Typename string
}

// Unwrap returns the underlying *APIError, so errors.As can match either type.
func (e *PayloadError) Unwrap() error { return &e.APIError }

func (e *PayloadError) Error() string {
	msg := "the API reported a failure"
	if e.Typename != "" {
		msg = "the operation returned " + e.Typename
	}
	if e.Message != "" {
		msg += ": " + strings.TrimRight(e.Message, ".!?")
	}
	if e.RequestID != "" {
		msg += " (request " + e.RequestID + ")"
	}
	return msg + ". It arrived in a successful HTTP response; the body says why."
}

func newPayloadError(status int, body []byte, requestID string, typename string) error {
	return &PayloadError{APIError: APIError{Code: codeFromBody(body, status), Status: status, Body: body, RequestID: requestID, Message: messageFromBody(body)}, Typename: typename}
}

func nextStep(status int) string {
	switch status {
	case 401:
		return "Check the credential and retry."
	case 403:
		return "Check the credential's permissions and retry."
	case 404:
		return "Check the requested identifier or path."
	case 409:
		return "Refresh the resource and retry the change."
	case 400, 422:
		return "Correct the request and retry."
	case 429:
		return "Wait before retrying the request."
	}
	if status >= 500 {
		return "Retry later; contact the API provider if this continues."
	}
	return "Inspect the error body and correct the request before retrying."
}

func codeFromBody(body []byte, status int) string {
	var probe map[string]any
	if json.Unmarshal(body, &probe) == nil {
		if code, ok := probe["code"].(string); ok && code != "" {
			return code
		}
		if errors, ok := probe["errors"].([]any); ok && len(errors) > 0 {
			if first, ok := errors[0].(map[string]any); ok {
				if code, ok := first["code"].(string); ok && code != "" {
					return code
				}
				if code, ok := first["code"].(float64); ok {
					return strconv.FormatFloat(code, 'f', -1, 64)
				}
			}
		}
		// Slack-style {"ok": false, "error": "invalid_auth"}: the error is a code.
		if code, ok := probe["error"].(string); ok && looksLikeCode(code) {
			return code
		}
	}
	return fmt.Sprintf("http_%d", status)
}

func looksLikeCode(value string) bool {
	if value == "" || len(value) > 64 || !((value[0] >= 'a' && value[0] <= 'z') || (value[0] >= 'A' && value[0] <= 'Z')) {
		return false
	}
	for _, r := range value {
		if !(r == '_' || r == '.' || r == '-' || (r >= '0' && r <= '9') || (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z')) {
			return false
		}
	}
	return true
}

// Decode unmarshals the raw error body into v.
func (e *APIError) Decode(v any) error {
	return json.Unmarshal(e.Body, v)
}

// TransportError means no HTTP response arrived at all: a network failure,
// DNS problem, timeout, or cancelled context.
type TransportError struct {
	Code      string
	Status    int
	RequestID string
	Body      []byte
	Method    string
	URL       string
	Err       error
}

func (e *TransportError) Error() string {
	return fmt.Sprintf("%s %s failed: %v. Check the connection and retry.", e.Method, e.URL, e.Err)
}

func (e *TransportError) Unwrap() error { return e.Err }

// ResponseParseError preserves a malformed successful response and its cause.
type ResponseParseError struct {
	Code      string
	Status    int
	RequestID string
	Body      []byte
	Err       error
}

func (e *ResponseParseError) Error() string {
	return fmt.Sprintf("HTTP %d response body could not be decoded. Check the API response or contact its provider.", e.Status)
}

func (e *ResponseParseError) Unwrap() error { return e.Err }

func responseParseError(status int, body []byte, requestID string, err error) error {
	return &ResponseParseError{Code: "response_parse_error", Status: status, Body: body, RequestID: requestID, Err: err}
}

// messageFromBody pulls a human message out of a JSON error payload so
// err.Error() says something useful without the caller decoding first.
func messageFromBody(body []byte) string {
	var probe map[string]any
	if err := json.Unmarshal(body, &probe); err != nil {
		return ""
	}
	for _, key := range []string{"message", "error", "detail", "error_description"} {
		if value, ok := probe[key].(string); ok && value != "" {
			return value
		}
	}
	if errors, ok := probe["errors"].([]any); ok && len(errors) > 0 {
		if first, ok := errors[0].(map[string]any); ok {
			if value, ok := first["message"].(string); ok {
				return value
			}
		}
	}
	return ""
}
