// Code generated by Typeship. DO NOT EDIT.

// Typeship — typed error responses.

package typeship

import (
	"fmt"
	"net/http"
	"time"
)

// PaymentRequiredError is returned for HTTP 402 responses.
type PaymentRequiredError struct {
	APIError
}

// Unwrap returns the underlying *APIError, so errors.As can match either type.
func (e *PaymentRequiredError) Unwrap() error {
	return &e.APIError
}

// RateLimitedError is an alias of RateLimitError.
//
// Deprecated: use RateLimitError, returned for every HTTP 429 response.
type RateLimitedError = RateLimitError

// InternalServerError is an alias of ServerError.
//
// Deprecated: use ServerError, returned for every 5xx response.
type InternalServerError = ServerError

// PreconditionFailedError is returned for HTTP 412 responses.
type PreconditionFailedError struct {
	APIError
}

// Unwrap returns the underlying *APIError, so errors.As can match either type.
func (e *PreconditionFailedError) Unwrap() error {
	return &e.APIError
}

// BadGatewayError is an alias of ServerError.
//
// Deprecated: use ServerError, returned for every 5xx response.
type BadGatewayError = ServerError

// PayloadTooLargeError is returned for HTTP 413 responses.
type PayloadTooLargeError struct {
	APIError
}

// Unwrap returns the underlying *APIError, so errors.As can match either type.
func (e *PayloadTooLargeError) Unwrap() error {
	return &e.APIError
}

// APIResponseError is returned for "default" responses.
type APIResponseError struct {
	APIError
}

// Unwrap returns the underlying *APIError, so errors.As can match either type.
func (e *APIResponseError) Unwrap() error {
	return &e.APIError
}

// apiError maps a status onto its error type: a status the operation
// documents keeps its own type, a family status (404, 429, 5xx) returns
// the family type whether documented or not, and ranges and default
// cover the rest.
func apiError(status int, body []byte, requestID string, header http.Header, errs map[string]func(int, []byte, string) error) error {
	base := APIError{Code: codeFromBody(body, status), Status: status, Body: body, RequestID: requestID, Message: messageFromBody(body)}
	limit := rateLimitInfo(status, header, time.Now())
	if limit != nil {
		base.RateLimit = limit
		if base.Code == fmt.Sprintf("http_%d", status) {
			base.Code = "rate_limited"
		}
		// A rate limit is its own error whatever the status: a 403 that means
		// "wait" must not read as "your credential lacks access".
		return &RateLimitError{APIError: base}
	}
	if ctor, ok := errs[fmt.Sprintf("%d", status)]; ok {
		return ctor(status, body, requestID)
	}
	if err := statusError(base); err != nil {
		return err
	}
	for _, key := range []string{fmt.Sprintf("%dXX", status/100), "default"} {
		if ctor, ok := errs[key]; ok {
			return ctor(status, body, requestID)
		}
	}
	return &base
}

func newPaymentRequiredError(status int, body []byte, requestID string) error {
	return &PaymentRequiredError{APIError: APIError{Code: codeFromBody(body, status), Status: status, Body: body, RequestID: requestID, Message: messageFromBody(body)}}
}

func newPreconditionFailedError(status int, body []byte, requestID string) error {
	return &PreconditionFailedError{APIError: APIError{Code: codeFromBody(body, status), Status: status, Body: body, RequestID: requestID, Message: messageFromBody(body)}}
}

func newPayloadTooLargeError(status int, body []byte, requestID string) error {
	return &PayloadTooLargeError{APIError: APIError{Code: codeFromBody(body, status), Status: status, Body: body, RequestID: requestID, Message: messageFromBody(body)}}
}

func newAPIResponseError(status int, body []byte, requestID string) error {
	return &APIResponseError{APIError: APIError{Code: codeFromBody(body, status), Status: status, Body: body, RequestID: requestID, Message: messageFromBody(body)}}
}
