// typeship — typed error responses.
// Generated by typeship — https://typeship.dev — do not edit by hand.
package typeship

import "fmt"

// BadRequestError is returned for 400 responses. The request body, Definition source, target selection, or package name is invalid.
type BadRequestError struct {
	APIError
}

// Unwrap returns the underlying *APIError, so errors.As can match either type.
func (e *BadRequestError) Unwrap() error { return &e.APIError }

// UnauthorizedError is returned for 401 responses. Missing, invalid, expired, or revoked credentials.
type UnauthorizedError struct {
	APIError
}

// Unwrap returns the underlying *APIError, so errors.As can match either type.
func (e *UnauthorizedError) Unwrap() error { return &e.APIError }

// ForbiddenError is returned for 403 responses. The credentials are valid but cannot act on the requested organization.
type ForbiddenError struct {
	APIError
}

// Unwrap returns the underlying *APIError, so errors.As can match either type.
func (e *ForbiddenError) Unwrap() error { return &e.APIError }

// ConflictError is returned for 409 responses. The key identifies changed intent.
type ConflictError struct {
	APIError
}

// Unwrap returns the underlying *APIError, so errors.As can match either type.
func (e *ConflictError) Unwrap() error { return &e.APIError }

// PayloadTooLargeError is returned for 413 responses. Spec exceeds the 10MB limit.
type PayloadTooLargeError struct {
	APIError
}

// Unwrap returns the underlying *APIError, so errors.As can match either type.
func (e *PayloadTooLargeError) Unwrap() error { return &e.APIError }

// UnprocessableEntityError is returned for 422 responses. The Definition could not be resolved or understood.
type UnprocessableEntityError struct {
	APIError
}

// Unwrap returns the underlying *APIError, so errors.As can match either type.
func (e *UnprocessableEntityError) Unwrap() error { return &e.APIError }

// RateLimitedError is returned for 429 responses. Too many requests, or an identical write is still in progress. Wait for Retry-After before retrying.
type RateLimitedError struct {
	APIError
}

// Unwrap returns the underlying *APIError, so errors.As can match either type.
func (e *RateLimitedError) Unwrap() error { return &e.APIError }

// APIResponseError is returned for default responses. Unexpected error.
type APIResponseError struct {
	APIError
}

// Unwrap returns the underlying *APIError, so errors.As can match either type.
func (e *APIResponseError) Unwrap() error { return &e.APIError }

// PaymentRequiredError is returned for 402 responses. The plan does not include another project or the requested target configuration.
type PaymentRequiredError struct {
	APIError
}

// Unwrap returns the underlying *APIError, so errors.As can match either type.
func (e *PaymentRequiredError) Unwrap() error { return &e.APIError }

// InternalServerError is returned for 500 responses. Project setup failed unexpectedly; the key reservation is released.
type InternalServerError struct {
	APIError
}

// Unwrap returns the underlying *APIError, so errors.As can match either type.
func (e *InternalServerError) Unwrap() error { return &e.APIError }

// NotFoundError is returned for 404 responses. No such resource in this account.
type NotFoundError struct {
	APIError
}

// Unwrap returns the underlying *APIError, so errors.As can match either type.
func (e *NotFoundError) Unwrap() error { return &e.APIError }

// BadGatewayError is returned for 502 responses. The Project was saved, but an obsolete release pull request could not be retired.
type BadGatewayError struct {
	APIError
}

// Unwrap returns the underlying *APIError, so errors.As can match either type.
func (e *BadGatewayError) Unwrap() error { return &e.APIError }

// apiError maps a status onto the documented error type for an operation.
func apiError(status int, body []byte, requestID string, errs map[string]func(int, []byte, string) error) error {
	base := APIError{Status: status, Body: body, RequestID: requestID, Message: messageFromBody(body)}
	if errs != nil {
		keys := []string{fmt.Sprintf("%d", status), fmt.Sprintf("%dXX", status/100), "default"}
		for _, key := range keys {
			if ctor, ok := errs[key]; ok {
				return ctor(status, body, requestID)
			}
		}
	}
	return &base
}

func newBadRequestError(status int, body []byte, requestID string) error {
	return &BadRequestError{APIError: APIError{Status: status, Body: body, RequestID: requestID, Message: messageFromBody(body)}}
}

func newUnauthorizedError(status int, body []byte, requestID string) error {
	return &UnauthorizedError{APIError: APIError{Status: status, Body: body, RequestID: requestID, Message: messageFromBody(body)}}
}

func newForbiddenError(status int, body []byte, requestID string) error {
	return &ForbiddenError{APIError: APIError{Status: status, Body: body, RequestID: requestID, Message: messageFromBody(body)}}
}

func newConflictError(status int, body []byte, requestID string) error {
	return &ConflictError{APIError: APIError{Status: status, Body: body, RequestID: requestID, Message: messageFromBody(body)}}
}

func newPayloadTooLargeError(status int, body []byte, requestID string) error {
	return &PayloadTooLargeError{APIError: APIError{Status: status, Body: body, RequestID: requestID, Message: messageFromBody(body)}}
}

func newUnprocessableEntityError(status int, body []byte, requestID string) error {
	return &UnprocessableEntityError{APIError: APIError{Status: status, Body: body, RequestID: requestID, Message: messageFromBody(body)}}
}

func newRateLimitedError(status int, body []byte, requestID string) error {
	return &RateLimitedError{APIError: APIError{Status: status, Body: body, RequestID: requestID, Message: messageFromBody(body)}}
}

func newAPIResponseError(status int, body []byte, requestID string) error {
	return &APIResponseError{APIError: APIError{Status: status, Body: body, RequestID: requestID, Message: messageFromBody(body)}}
}

func newPaymentRequiredError(status int, body []byte, requestID string) error {
	return &PaymentRequiredError{APIError: APIError{Status: status, Body: body, RequestID: requestID, Message: messageFromBody(body)}}
}

func newInternalServerError(status int, body []byte, requestID string) error {
	return &InternalServerError{APIError: APIError{Status: status, Body: body, RequestID: requestID, Message: messageFromBody(body)}}
}

func newNotFoundError(status int, body []byte, requestID string) error {
	return &NotFoundError{APIError: APIError{Status: status, Body: body, RequestID: requestID, Message: messageFromBody(body)}}
}

func newBadGatewayError(status int, body []byte, requestID string) error {
	return &BadGatewayError{APIError: APIError{Status: status, Body: body, RequestID: requestID, Message: messageFromBody(body)}}
}
