// Package typeship — error types.
// Generated by typeship — https://typeship.dev — do not edit by hand.
package typeship

import (
	"encoding/json"
	"fmt"
)

// APIError is any error response from the API. Every generated per-status
// type embeds it, so errors.As works at whichever precision you need:
//
//	var notFound *NotFoundError
//	if errors.As(err, &notFound) { ... }
//
//	var apiErr *APIError
//	if errors.As(err, &apiErr) { fmt.Println(apiErr.Status) }
type APIError struct {
	Status    int
	Body      []byte
	RequestID string
	Message   string
}

func (e *APIError) Error() string {
	msg := fmt.Sprintf("http %d", e.Status)
	if e.Message != "" {
		msg += ": " + e.Message
	}
	if e.RequestID != "" {
		msg += " (request " + e.RequestID + ")"
	}
	return msg
}

// Decode unmarshals the raw error body into v.
func (e *APIError) Decode(v any) error {
	return json.Unmarshal(e.Body, v)
}

// TransportError means no HTTP response arrived at all: a network failure,
// DNS problem, timeout, or cancelled context.
type TransportError struct {
	Method string
	URL    string
	Err    error
}

func (e *TransportError) Error() string {
	return fmt.Sprintf("%s %s failed: %v", e.Method, e.URL, e.Err)
}

func (e *TransportError) Unwrap() error { return e.Err }

// messageFromBody pulls a human message out of a JSON error payload so
// err.Error() says something useful without the caller decoding first.
func messageFromBody(body []byte) string {
	var probe map[string]any
	if err := json.Unmarshal(body, &probe); err != nil {
		return ""
	}
	for _, key := range []string{"message", "error", "detail", "error_description"} {
		if value, ok := probe[key].(string); ok && value != "" {
			return value
		}
	}
	return ""
}
