// typeship — files.
// Generated by typeship — https://typeship.dev
package typeship

import (
	"context"
	"fmt"
	"net/url"
)

// FilesService accesses the files endpoints.
type FilesService struct {
	core *core
}

// FilesGetParams are the inputs for FilesService.Get.
type FilesGetParams struct {
	// Cursor next_cursor from the preceding chunk of this file.
	Cursor *string `json:"-"`
}

// Get a File.
//
// Returns one bounded chunk of an immutable file: at most 24 KiB, as UTF-8 text or, for binary bytes, base64. When next_cursor is not null, repeat the request with cursor and concatenate the chunks in order. A file ID always returns the same bytes.
//
// GET /files/{file_id}
func (s *FilesService) Get(ctx context.Context, fileID string, params *FilesGetParams, opts ...RequestOption) (*FileResponse, error) {
	query := map[string]any{}
	if params != nil {
		if params.Cursor != nil {
			query["cursor"] = *params.Cursor
		}
	}
	req := request{
		Method:     "GET",
		Path:       fmt.Sprintf("/files/%s", url.PathEscape(fileID)),
		Query:      query,
		Errors:     map[string]func(int, []byte, string) error{"400": newBadRequestError, "401": newUnauthorizedError, "403": newForbiddenError, "404": newNotFoundError, "429": newRateLimitedError, "500": newInternalServerError},
		Security:   []map[string][]string{{"apiKey": {}}},
		SchemaKey:  "files.get",
		Idempotent: true,
	}
	var out FileResponse
	if err := s.core.do(ctx, req, &out, opts...); err != nil {
		return nil, err
	}
	return &out, nil
}
