// typeship — generations.
// Generated by typeship — https://typeship.dev — do not edit by hand.
package typeship

import (
	"context"
	"fmt"
	"net/url"
)

// GenerationsService accesses the generations endpoints.
type GenerationsService struct {
	core *core
}

// GenerationsRetrieveFileParams are the inputs for GenerationsService.RetrieveFile.
type GenerationsRetrieveFileParams struct {
	// Path Repo-relative path inside the generated package.
	Path string `json:"-"`
}

// Retrieve a generation.
//
// Includes the generated files when the generation succeeded.
//
// GET /generations/{generation_id}
func (s *GenerationsService) Retrieve(ctx context.Context, generationID string, opts ...RequestOption) (*Generation, error) {
	req := request{
		Method:     "GET",
		Path:       fmt.Sprintf("/generations/%s", url.PathEscape(generationID)),
		Errors:     map[string]func(int, []byte, string) error{"401": newUnauthorizedError, "403": newForbiddenError, "404": newNotFoundError, "429": newRateLimitedError},
		SchemaKey:  "generations.retrieve",
		Idempotent: true,
	}
	var out Generation
	if err := s.core.do(ctx, req, &out, opts...); err != nil {
		return nil, err
	}
	return &out, nil
}

// RetrieveFile — fetch one file from a generation.
//
// Raw file content, for generations whose output was too large to inline (files_omitted true). The generation's files_index lists valid paths.
//
// GET /generations/{generation_id}/file
func (s *GenerationsService) RetrieveFile(ctx context.Context, generationID string, params GenerationsRetrieveFileParams, opts ...RequestOption) (string, error) {
	query := map[string]any{}
	query["path"] = params.Path
	req := request{
		Method:     "GET",
		Path:       fmt.Sprintf("/generations/%s/file", url.PathEscape(generationID)),
		Query:      query,
		Errors:     map[string]func(int, []byte, string) error{"400": newBadRequestError, "401": newUnauthorizedError, "403": newForbiddenError, "404": newNotFoundError, "429": newRateLimitedError},
		SchemaKey:  "generations.retrieveFile",
		Idempotent: true,
	}
	var out string
	if err := s.core.do(ctx, req, &out, opts...); err != nil {
		return "", err
	}
	return out, nil
}
