// typeship — generate.
// Generated by typeship — https://typeship.dev — do not edit by hand.
package typeship

import (
	"context"
	"fmt"
)

// GenerateService accesses the generate endpoints.
type GenerateService struct {
	core *core
}

// GenerateRunParams are the inputs for GenerateService.Run.
type GenerateRunParams struct {
	// IdempotencyKey Identifies one logical write for 24 hours. The key is scoped to the authenticated account and operation; account-less generation uses a hashed network identity. Retrying the same method, path, query, and JSON body replays the original response. Reusing the key with changed intent returns 409. After expiry the key starts a new write.
	IdempotencyKey *string `json:"-"`
}

// Run — generate one package from a Definition.
//
// Returns one generated package without creating a Project.
//
// Supports [idempotent retries](https://typeship.dev/docs/typeship-api/idempotency); keyed responses include generated files in the replay cache.
//
// Anonymous and Free requests include the first 25 operations. Paid plans include all operations. Anonymous requests are rate limited by IP address. Check `limits` for omitted operations; an invalid API key returns `401`.
//
// An anonymous URL request without source headers may return `claim.url`. Sign in through that link within seven days to save the recipe as a Project.
//
// POST /generate
func (s *GenerateService) Run(ctx context.Context, body GenerateRequest, params *GenerateRunParams, opts ...RequestOption) (*GenerationResult, error) {
	headers := map[string]string{}
	if params != nil {
		if params.IdempotencyKey != nil {
			headers["Idempotency-Key"] = fmt.Sprint(*params.IdempotencyKey)
		}
	}
	req := request{
		Method:            "POST",
		Path:              "/generate",
		Headers:           headers,
		Body:              body,
		Errors:            map[string]func(int, []byte, string) error{"400": newBadRequestError, "401": newUnauthorizedError, "403": newForbiddenError, "409": newConflictError, "413": newPayloadTooLargeError, "422": newUnprocessableEntityError, "429": newRateLimitedError, "500": newInternalServerError, "default": newAPIResponseError},
		Security:          []map[string][]string{{}, {"apiKey": {}}},
		SchemaKey:         "generate.run",
		IdempotencyHeader: "Idempotency-Key",
	}
	var out GenerationResult
	if err := s.core.do(ctx, req, &out, opts...); err != nil {
		return nil, err
	}
	return &out, nil
}
