// typeship — generations.
// Generated by typeship — https://typeship.dev
package typeship

import (
	"context"
	"fmt"
	"net/url"
	"time"
)

// GenerationsService accesses the generations endpoints.
type GenerationsService struct {
	core *core
}

// GenerationsListParams are the inputs for GenerationsService.List.
type GenerationsListParams struct {
	// Limit Maximum number of resources to return. Omit for 20; otherwise supply base-10 digits representing an integer from 1 to 100. Empty, malformed, or out-of-range values return 400 input_invalid. List query parameters must appear only once; repeated or unrecognized parameters return 400 query_param_invalid.
	Limit *int64 `json:"-"`
	// Cursor Opaque cursor from the preceding page's next_cursor. Valid only for the same organization, operation, filters, and ordering that issued it. Omit to start at the first page. Empty or malformed cursors, and cursors issued for different filters, return 400 cursor_invalid; start again from the first page. Repeated cursors return 400 query_param_invalid. The page limit may change between requests.
	Cursor *string `json:"-"`
	// ProjectID Only Generations in this Project.
	ProjectID *ProjectID `json:"-"`
	// TargetID Only Generations of this Target.
	TargetID *TargetID `json:"-"`
	// Status Only Generations with this status.
	Status *GenerationStatus `json:"-"`
}

// GenerationsListFilesParams are the inputs for GenerationsService.ListFiles.
type GenerationsListFilesParams struct {
	// Limit Maximum number of resources to return. Omit for 20; otherwise supply base-10 digits representing an integer from 1 to 100. Empty, malformed, or out-of-range values return 400 input_invalid. List query parameters must appear only once; repeated or unrecognized parameters return 400 query_param_invalid.
	Limit *int64 `json:"-"`
	// Cursor Opaque cursor from the preceding page's next_cursor. Valid only for the same organization, operation, filters, and ordering that issued it. Omit to start at the first page. Empty or malformed cursors, and cursors issued for different filters, return 400 cursor_invalid; start again from the first page. Repeated cursors return 400 query_param_invalid. The page limit may change between requests.
	Cursor *string `json:"-"`
}

// Get a Generation.
//
// Returns the status of that Generation. `queued` and `running` mean generation is still in progress. `completed` means generated files are saved, not that repository delivery or a Draft is complete. List its files with listGenerationFiles and read each with getFile.
//
// GET /generations/{generation_id}
func (s *GenerationsService) Get(ctx context.Context, generationID string, opts ...RequestOption) (*GenerationResponse, error) {
	req := request{
		Method:     "GET",
		Path:       fmt.Sprintf("/generations/%s", url.PathEscape(generationID)),
		Errors:     map[string]func(int, []byte, string) error{"401": newUnauthorizedError, "403": newForbiddenError, "404": newNotFoundError, "429": newRateLimitedError, "500": newInternalServerError},
		Security:   []map[string][]string{{"apiKey": {}}},
		SchemaKey:  "generations.get",
		Idempotent: true,
	}
	var out GenerationResponse
	if err := s.core.do(ctx, req, &out, opts...); err != nil {
		return nil, notModified(err)
	}
	return &out, nil
}

// List Generations.
//
// GET /generations
//
// Returns an iterator that fetches pages lazily:
//
//	it := client.Generations.List(ctx, nil)
//	for it.Next() {
//		item := it.Value()
//	}
//	if err := it.Err(); err != nil { ... }
func (s *GenerationsService) List(ctx context.Context, params *GenerationsListParams, opts ...RequestOption) *Iter[Generation] {
	query := map[string]any{}
	if params != nil {
		if params.Limit != nil {
			query["limit"] = *params.Limit
		}
		if params.Cursor != nil {
			query["cursor"] = *params.Cursor
		}
		if params.ProjectID != nil {
			query["project_id"] = *params.ProjectID
		}
		if params.TargetID != nil {
			query["target_id"] = *params.TargetID
		}
		if params.Status != nil {
			query["status"] = *params.Status
		}
	}
	req := request{
		Method:     "GET",
		Path:       "/generations",
		Query:      query,
		Errors:     map[string]func(int, []byte, string) error{"400": newBadRequestError, "401": newUnauthorizedError, "403": newForbiddenError, "404": newNotFoundError, "429": newRateLimitedError, "500": newInternalServerError},
		Security:   []map[string][]string{{"apiKey": {}}},
		SchemaKey:  "generations.list",
		Idempotent: true,
	}
	return newIter[Generation](ctx, s.core, req, opts, pageConfig{
		Style:           "cursor",
		ItemsField:      "data",
		CursorParam:     "cursor",
		NextCursorField: "next_cursor",
		HasMoreField:    "has_more",
		LimitParam:      "limit",
	})
}

// ListFiles — list a Generation's files.
//
// Lists the generated package's files, ordered by path. Read content with getFile.
//
// GET /generations/{generation_id}/files
//
// Returns an iterator that fetches pages lazily:
//
//	it := client.Generations.ListFiles(ctx, id, nil)
//	for it.Next() {
//		item := it.Value()
//	}
//	if err := it.Err(); err != nil { ... }
func (s *GenerationsService) ListFiles(ctx context.Context, generationID string, params *GenerationsListFilesParams, opts ...RequestOption) *Iter[File] {
	query := map[string]any{}
	if params != nil {
		if params.Limit != nil {
			query["limit"] = *params.Limit
		}
		if params.Cursor != nil {
			query["cursor"] = *params.Cursor
		}
	}
	req := request{
		Method:     "GET",
		Path:       fmt.Sprintf("/generations/%s/files", url.PathEscape(generationID)),
		Query:      query,
		Errors:     map[string]func(int, []byte, string) error{"400": newBadRequestError, "401": newUnauthorizedError, "403": newForbiddenError, "404": newNotFoundError, "429": newRateLimitedError, "500": newInternalServerError},
		Security:   []map[string][]string{{"apiKey": {}}},
		SchemaKey:  "generations.listFiles",
		Idempotent: true,
	}
	return newIter[File](ctx, s.core, req, opts, pageConfig{
		Style:           "cursor",
		ItemsField:      "data",
		CursorParam:     "cursor",
		NextCursorField: "next_cursor",
		HasMoreField:    "has_more",
		LimitParam:      "limit",
	})
}

// Wait polls until generated files are saved or the Generation fails. Cancel ctx to stop waiting.
func (s *GenerationsService) Wait(ctx context.Context, generationID string, opts ...RequestOption) (*GenerationResponse, error) {
	for {
		result, err := s.Get(ctx, generationID, opts...)
		if err != nil {
			return nil, err
		}
		if result.Status != "queued" && result.Status != "running" {
			return result, nil
		}
		select {
		case <-ctx.Done():
			return nil, ctx.Err()
		case <-time.After(3 * time.Second):
		}
	}
}
