// typeship — generations.
// Generated by typeship — https://typeship.dev — do not edit by hand.
package typeship

import (
	"context"
	"fmt"
	"net/url"
)

// GenerationsService accesses the generations endpoints.
type GenerationsService struct {
	core *core
}

// GenerationsGetFileParams are the inputs for GenerationsService.GetFile.
type GenerationsGetFileParams struct {
	// Path Repo-relative path inside the generated package.
	Path *string `json:"-"`
}

// Get — retrieve a generation.
//
// Includes the generated files when the generation succeeded.
//
// GET /generations/{generation_id}
func (s *GenerationsService) Get(ctx context.Context, generationID string, opts ...RequestOption) (*Generation, error) {
	req := request{
		Method:     "GET",
		Path:       fmt.Sprintf("/generations/%s", url.PathEscape(generationID)),
		Errors:     map[string]func(int, []byte, string) error{"401": newUnauthorizedError, "404": newNotFoundError},
		SchemaKey:  "generations.get",
		Idempotent: true,
	}
	var out Generation
	if err := s.core.do(ctx, req, &out, opts...); err != nil {
		return nil, err
	}
	return &out, nil
}

// GetFile — fetch one file from a generation.
//
// Raw file content, for generations whose output was too large to inline (files_omitted true). The generation's files_index lists valid paths.
//
// GET /generations/{generation_id}/file
func (s *GenerationsService) GetFile(ctx context.Context, generationID string, params *GenerationsGetFileParams, opts ...RequestOption) (string, error) {
	query := map[string]any{}
	if params != nil {
		if params.Path != nil {
			query["path"] = *params.Path
		}
	}
	req := request{
		Method:     "GET",
		Path:       fmt.Sprintf("/generations/%s/file", url.PathEscape(generationID)),
		Query:      query,
		Errors:     map[string]func(int, []byte, string) error{"401": newUnauthorizedError, "404": newNotFoundError},
		SchemaKey:  "generations.getFile",
		Idempotent: true,
	}
	var out string
	if err := s.core.do(ctx, req, &out, opts...); err != nil {
		return "", err
	}
	return out, nil
}
