// typeship — API types.
// Generated by typeship — https://typeship.dev — do not edit by hand.
package typeship

import "encoding/json"

type GenerateRequest struct {
	Spec SpecInput `json:"spec"`
	// Outputs Outputs for one delivery package. Choose one SDK output, or TypeScript SDK, CLI, and MCP in any combination. Linked projects can generate outputs in all ecosystems.
	Outputs []OutputID `json:"outputs"`
	// PackageName Registry name for the selected delivery package: an npm package, Python distribution, or Go module path. Defaults to a name derived from the API title.
	PackageName *string `json:"package_name,omitempty"`
	Config      *Config `json:"config,omitempty"`
}

// SpecInput is one of URLSpecInput, InlineSpecInput — The specification for stateless generation, provided as exactly one URL or inline document.
// Go has no sum types, so it holds the JSON as received and decodes on
// request: try the As* accessors, or switch on Discriminator() when the
// spec names one.
type SpecInput struct {
	union json.RawMessage
}

// MarshalJSON writes the value as it was set or received.
func (u SpecInput) MarshalJSON() ([]byte, error) {
	if u.union == nil {
		return []byte("null"), nil
	}
	return u.union, nil
}

// UnmarshalJSON keeps the raw JSON so any variant can be decoded later.
func (u *SpecInput) UnmarshalJSON(data []byte) error {
	u.union = append(u.union[:0], data...)
	return nil
}

// Raw returns the JSON exactly as received.
func (u SpecInput) Raw() json.RawMessage {
	return u.union
}

// AsURLSpecInput decodes the value as URLSpecInput.
func (u SpecInput) AsURLSpecInput() (URLSpecInput, error) {
	var v URLSpecInput
	err := json.Unmarshal(u.union, &v)
	return v, err
}

// FromURLSpecInput sets the value to a URLSpecInput.
func (u *SpecInput) FromURLSpecInput(v URLSpecInput) error {
	encoded, err := json.Marshal(v)
	if err != nil {
		return err
	}
	u.union = encoded
	return nil
}

// AsInlineSpecInput decodes the value as InlineSpecInput.
func (u SpecInput) AsInlineSpecInput() (InlineSpecInput, error) {
	var v InlineSpecInput
	err := json.Unmarshal(u.union, &v)
	return v, err
}

// FromInlineSpecInput sets the value to a InlineSpecInput.
func (u *SpecInput) FromInlineSpecInput(v InlineSpecInput) error {
	encoded, err := json.Marshal(v)
	if err != nil {
		return err
	}
	u.union = encoded
	return nil
}

type URLSpecInput struct {
	// URL URL of an OpenAPI document, a GraphQL SDL file, or a GraphQL endpoint (introspected automatically). Fetched server-side.
	URL string `json:"url"`
	// Headers Request headers for a protected URL. Sent on the document GET and GraphQL introspection POST, never returned or retained by stateless generation.
	Headers map[string]string `json:"headers,omitempty"`
}

type InlineSpecInput struct {
	// Inline Raw spec text (OpenAPI JSON/YAML or GraphQL SDL). Up to 10MB.
	Inline string `json:"inline"`
}

// OutputID is one of "typescript-sdk", "python-sdk", "go-sdk", "cli", "mcp". One customer-selected output. CLI and MCP include the private TypeScript request runtime they need; that dependency is not a selected or billable TypeScript SDK.
type OutputID string

const (
	OutputIDTypescriptSDK OutputID = "typescript-sdk"
	OutputIDPythonSDK     OutputID = "python-sdk"
	OutputIDGoSDK         OutputID = "go-sdk"
	OutputIDCLI           OutputID = "cli"
	OutputIDMCP           OutputID = "mcp"
)

// Config Everything typeship needs beyond the spec, in one object: generation customization (globals, retries, pagination) and how the generated tooling behaves (cli, mcp, package, docs_url). Plain configuration. typeship never requires vendor extensions inside the spec itself. The same shape is accepted on a project and on POST /generate.
type Config struct {
	// Globals Wire names of query/header parameters that become settable once on the generated client and auto-apply to every operation that accepts them; per-call values win. Names that match nothing are reported as generation warnings.
	Globals []string     `json:"globals,omitempty"`
	Retries *RetryTuning `json:"retries,omitempty"`
	// Pagination Per-operation pagination control, keyed by operationId or "METHOD /path". Unmatched keys are reported as generation warnings.
	Pagination map[string]ConfigPaginationValue `json:"pagination,omitempty"`
	Graphql    *GraphqlSettings                 `json:"graphql,omitempty"`
	CLI        *CLIBehavior                     `json:"cli,omitempty"`
	MCP        *MCPBehavior                     `json:"mcp,omitempty"`
	Package    *PackageBehavior                 `json:"package,omitempty"`
	// DocsURL The API's documentation site. Read through its llms.txt by the generated CLI's docs command, the MCP server's docs tools, and the package's AGENTS.md. Defaults to the spec's externalDocs URL.
	DocsURL *string `json:"docs_url,omitempty"`
}

// RetryTuning Retry behavior. Top-level fields adjust every operation; operations maps operationId or "METHOD /path" keys to per-operation overrides.
type RetryTuning struct {
	MaxRetries *int64 `json:"max_retries,omitempty"`
	// Statuses Replaces the default retryable set (408, 429, 500, 502, 503, 504).
	Statuses       []int64 `json:"statuses,omitempty"`
	InitialDelayMs *int64  `json:"initial_delay_ms,omitempty"`
	MaxDelayMs     *int64  `json:"max_delay_ms,omitempty"`
	// RetryNonIdempotent Also retry non-idempotent methods (POST/PATCH).
	RetryNonIdempotent *bool `json:"retry_non_idempotent,omitempty"`
	// Disabled Shorthand for max_retries 0.
	Disabled   *bool                  `json:"disabled,omitempty"`
	Operations map[string]RetryTuning `json:"operations,omitempty"`
}

// ConfigPaginationValue is one of PaginationRule, bool.
// Go has no sum types, so it holds the JSON as received and decodes on
// request: try the As* accessors, or switch on Discriminator() when the
// spec names one.
type ConfigPaginationValue struct {
	union json.RawMessage
}

// MarshalJSON writes the value as it was set or received.
func (u ConfigPaginationValue) MarshalJSON() ([]byte, error) {
	if u.union == nil {
		return []byte("null"), nil
	}
	return u.union, nil
}

// UnmarshalJSON keeps the raw JSON so any variant can be decoded later.
func (u *ConfigPaginationValue) UnmarshalJSON(data []byte) error {
	u.union = append(u.union[:0], data...)
	return nil
}

// Raw returns the JSON exactly as received.
func (u ConfigPaginationValue) Raw() json.RawMessage {
	return u.union
}

// AsPaginationRule decodes the value as PaginationRule.
func (u ConfigPaginationValue) AsPaginationRule() (PaginationRule, error) {
	var v PaginationRule
	err := json.Unmarshal(u.union, &v)
	return v, err
}

// FromPaginationRule sets the value to a PaginationRule.
func (u *ConfigPaginationValue) FromPaginationRule(v PaginationRule) error {
	encoded, err := json.Marshal(v)
	if err != nil {
		return err
	}
	u.union = encoded
	return nil
}

// AsBool decodes the value as bool.
func (u ConfigPaginationValue) AsBool() (bool, error) {
	var v bool
	err := json.Unmarshal(u.union, &v)
	return v, err
}

// FromBool sets the value to a bool.
func (u *ConfigPaginationValue) FromBool(v bool) error {
	encoded, err := json.Marshal(v)
	if err != nil {
		return err
	}
	u.union = encoded
	return nil
}

type PaginationRule struct {
	Style *PaginationRuleStyle `json:"style,omitempty"`
	// ItemsField Response field holding the item array.
	ItemsField      string  `json:"items_field"`
	CursorParam     *string `json:"cursor_param,omitempty"`
	NextCursorField *string `json:"next_cursor_field,omitempty"`
	HasMoreField    *string `json:"has_more_field,omitempty"`
	IDField         *string `json:"id_field,omitempty"`
	PageParam       *string `json:"page_param,omitempty"`
	OffsetParam     *string `json:"offset_param,omitempty"`
	LimitParam      *string `json:"limit_param,omitempty"`
}

// PaginationRuleStyle is one of "cursor", "cursorFromLastId", "page", "offset".
type PaginationRuleStyle string

const (
	PaginationRuleStyleCursor           PaginationRuleStyle = "cursor"
	PaginationRuleStyleCursorFromLastID PaginationRuleStyle = "cursorFromLastId"
	PaginationRuleStylePage             PaginationRuleStyle = "page"
	PaginationRuleStyleOffset           PaginationRuleStyle = "offset"
)

// GraphqlSettings What a GraphQL schema cannot say about itself. Ignored for OpenAPI specs.
type GraphqlSettings struct {
	// Endpoint The URL every request is POSTed to; the generated client's default baseUrl. Defaults to the URL the schema was fetched from. Without either, baseUrl is a required client option.
	Endpoint *string `json:"endpoint,omitempty"`
	// Environments Named endpoints (sandbox, production). Each becomes a client environment; the first is the default unless endpoint is set.
	Environments []GraphqlSettingsEnvironmentsItem `json:"environments,omitempty"`
	// Auth How requests authenticate. bearer sends Authorization: Bearer; basic is for key-pair APIs (public key as username, private key as password); api_key sends a header named by api_key_header; none generates no auth option.
	Auth *GraphqlSettingsAuth `json:"auth,omitempty"`
	// APIKeyHeader Header carrying the key when auth is api_key. Required for that mode; Typeship does not invent a vendor-specific header name.
	APIKeyHeader *string `json:"api_key_header,omitempty"`
	// Title The API's name; drives the package and client names ("Braintree" gives braintree and BraintreeClient). Defaults to a name derived from the endpoint's host.
	Title *string `json:"title,omitempty"`
	// Scalars JSON representation of each custom scalar, keyed by GraphQL scalar name. Unmapped scalars generate as the language's untyped JSON value and produce a warning. Unmatched keys warn.
	Scalars map[string]GraphqlSettingsScalarsValue `json:"scalars,omitempty"`
}

type GraphqlSettingsEnvironmentsItem struct {
	Name string `json:"name"`
	URL  string `json:"url"`
}

// GraphqlSettingsAuth is one of "bearer", "basic", "api_key", "none". How requests authenticate. bearer sends Authorization: Bearer; basic is for key-pair APIs (public key as username, private key as password); api_key sends a header named by api_key_header; none generates no auth option.
type GraphqlSettingsAuth string

const (
	GraphqlSettingsAuthBearer GraphqlSettingsAuth = "bearer"
	GraphqlSettingsAuthBasic  GraphqlSettingsAuth = "basic"
	GraphqlSettingsAuthAPIKey GraphqlSettingsAuth = "api_key"
	GraphqlSettingsAuthNone   GraphqlSettingsAuth = "none"
)

// GraphqlSettingsScalarsValue is one of "string", "integer", "number", "boolean", "json".
type GraphqlSettingsScalarsValue string

const (
	GraphqlSettingsScalarsValueString  GraphqlSettingsScalarsValue = "string"
	GraphqlSettingsScalarsValueInteger GraphqlSettingsScalarsValue = "integer"
	GraphqlSettingsScalarsValueNumber  GraphqlSettingsScalarsValue = "number"
	GraphqlSettingsScalarsValueBoolean GraphqlSettingsScalarsValue = "boolean"
	GraphqlSettingsScalarsValueJSON    GraphqlSettingsScalarsValue = "json"
)

// CLIBehavior How the generated CLI behaves. Part of Config.
type CLIBehavior struct {
	// WhoamiOperation resource.method of a zero-argument GET that the generated CLI's whoami command calls. Overrides auto-detection; a value that matches nothing is reported as a generation warning.
	WhoamiOperation *string `json:"whoami_operation,omitempty"`
	// OauthClientID OAuth client id baked into the generated CLI for device-flow login. Without it, login prompts for a pasted credential.
	OauthClientID *string `json:"oauth_client_id,omitempty"`
	// OauthScopes Scopes requested during device-flow login. Include offline_access if the authorization server gates refresh tokens behind it.
	OauthScopes []string `json:"oauth_scopes,omitempty"`
	// OauthAudience Audience sent with the device-authorization request, for authorization servers that require one to issue API-valid access tokens.
	OauthAudience *string `json:"oauth_audience,omitempty"`
	// UpdateNotice Opt in to a once-a-day registry check that prints an upgrade hint. Off by default; generated code phones nobody unless this is enabled.
	UpdateNotice *bool `json:"update_notice,omitempty"`
	// SupportURL Where the generated CLI's feedback command sends users. GitHub issues/new URLs get a prefilled title and environment details.
	SupportURL *string `json:"support_url,omitempty"`
	// AuthURL Base URL of the browser-approval endpoint pair used by CLI login. The CLI keeps the verifier and receives the credential directly; no key is pasted through a conversation.
	AuthURL *string `json:"auth_url,omitempty"`
	// MCPURL Hosted MCP endpoint installed by the generated CLI instead of launching the package's local stdio server.
	MCPURL *string `json:"mcp_url,omitempty"`
	// SkillsRepo GitHub owner/name of the skills package the generated CLI offers to install during init.
	SkillsRepo *string `json:"skills_repo,omitempty"`
}

// MCPBehavior How the generated MCP server and the hosted endpoint behave. Part of Config.
type MCPBehavior struct {
	// ToolMode MCP tool shape. meta collapses per-operation tools into search_docs, read_docs, and execute so large APIs don't flood an agent's context window. Auto considers the serialized tool schemas, switching near 10k tokens or above 100 operations.
	ToolMode *MCPBehaviorToolMode `json:"tool_mode,omitempty"`
	// Instructions Guidance appended to the MCP server's instructions, which agents read once when they connect (server/discover): what to call first, conventions the spec does not state, what not to do. Carried by the package's server and the hosted endpoint alike.
	Instructions *string `json:"instructions,omitempty"`
	// ToolDescriptions Hand-written MCP tool descriptions keyed by operationId or "METHOD /path". Each replaces the text typeship derives for that operation (summary, first sentence, method and path, deprecation and auth notes). For flows the spec cannot describe, such as a multi-step upload. Keys that match no operation are reported as generation warnings.
	ToolDescriptions map[string]string `json:"tool_descriptions,omitempty"`
}

// MCPBehaviorToolMode is one of "auto", "operations", "meta". MCP tool shape. meta collapses per-operation tools into search_docs, read_docs, and execute so large APIs don't flood an agent's context window. Auto considers the serialized tool schemas, switching near 10k tokens or above 100 operations.
type MCPBehaviorToolMode string

const (
	MCPBehaviorToolModeAuto       MCPBehaviorToolMode = "auto"
	MCPBehaviorToolModeOperations MCPBehaviorToolMode = "operations"
	MCPBehaviorToolModeMeta       MCPBehaviorToolMode = "meta"
)

// PackageBehavior Published-package metadata the API spec does not own. Use version only when the client intentionally releases on a different cadence from info.version; repository is derived from each destination.
type PackageBehavior struct {
	// Version Semantic version for the generated packages. Defaults to info.version.
	Version *string `json:"version,omitempty"`
	// Homepage Homepage written into registry metadata.
	Homepage *string `json:"homepage,omitempty"`
	// License SPDX identifier written into registry metadata. Defaults to info.license.
	License *string `json:"license,omitempty"`
	// LicenseText Exact LICENSE file contents. Supply this for licences the engine does not build in; MIT is built in when copyright is also set.
	LicenseText *string `json:"license_text,omitempty"`
	// Copyright Copyright line used in generated license files.
	Copyright *string `json:"copyright,omitempty"`
	// BinName CLI executable name when it differs from the npm package name.
	BinName *string `json:"bin_name,omitempty"`
	// GoPackageName Go identifier when the destination repository name is unsuitable.
	GoPackageName *string `json:"go_package_name,omitempty"`
	// MCPName Official MCP registry name written into package.json.
	MCPName *string `json:"mcp_name,omitempty"`
}

type GenerationResult struct {
	Files    []GeneratedFile   `json:"files"`
	Warnings []string          `json:"warnings"`
	Meta     GenerationMeta    `json:"meta"`
	Limits   *GenerationLimits `json:"limits,omitempty"`
	// Claim Anonymous, URL-sourced generations only. A link a signed-in person can open to turn this run into a project in their organization (same spec, outputs, and config). Lasts seven days. Null for inline specs; absent on keyed calls.
	Claim *GenerationResultClaim `json:"claim,omitempty"`
}

type GeneratedFile struct {
	// Path Repo-relative path inside the generated package.
	Path    string `json:"path"`
	Content string `json:"content"`
}

type GenerationMeta struct {
	Title      string                    `json:"title"`
	Version    string                    `json:"version"`
	SpecFormat *GenerationMetaSpecFormat `json:"spec_format,omitempty"`
	// OasVersion Detected spec version, "2.0", "3.0", or "3.1".
	OasVersion string `json:"oas_version"`
	// Converted True when the input was Swagger 2.0 and was converted.
	Converted   *bool  `json:"converted,omitempty"`
	PackageName string `json:"package_name"`
	ClientName  string `json:"client_name"`
	// Outputs Customer-selected outputs present in this delivery package.
	Outputs                 []OutputID `json:"outputs"`
	ResourceCount           *int64     `json:"resource_count,omitempty"`
	OperationCount          *int64     `json:"operation_count,omitempty"`
	SchemaCount             *int64     `json:"schema_count,omitempty"`
	PaginatedOperationCount *int64     `json:"paginated_operation_count,omitempty"`
	// OmittedOperationCount Operations beyond the plan's endpoint allowance, not generated.
	OmittedOperationCount *int64 `json:"omitted_operation_count,omitempty"`
	// PrURL Pull request opened by this regeneration, when one was.
	PrURL    *string `json:"pr_url,omitempty"`
	PrNumber *int64  `json:"pr_number,omitempty"`
	// PrStatus Whether a destination pull request opened, was unnecessary because the generated tree already matched, or could not be opened.
	PrStatus *GenerationMetaPrStatus `json:"pr_status,omitempty"`
	// PrError Why the configured destination pull request was not opened. Generation itself still succeeded; fix this action and regenerate.
	PrError *string `json:"pr_error,omitempty"`
	// Changelog Markdown changelog entry for this regeneration, from the API surface diff. Absent on a first generation or when nothing changed.
	Changelog *string `json:"changelog,omitempty"`
	// BreakingCount Breaking changes in the diff; removed methods and fields, changed types, inputs that became required.
	BreakingCount *int64 `json:"breaking_count,omitempty"`
	// Baseline What the diff was measured against; "destination" means the .typeship/surface.json merged in the destination repository.
	Baseline *GenerationMetaBaseline `json:"baseline,omitempty"`
	// PackageCompatibility The package compatibility verdict on the regeneration pull request; failure means breaking changes without a major version bump.
	PackageCompatibility *GenerationMetaPackageCompatibility `json:"package_compatibility,omitempty"`
	// PackageCompatibilityNote The verdict in one line, as the commit status describes it.
	PackageCompatibilityNote *string `json:"package_compatibility_note,omitempty"`
	// PreviousVersion The package version the destination had before this regeneration.
	PreviousVersion *string `json:"previous_version,omitempty"`
	FileCount       *int64  `json:"file_count,omitempty"`
	TotalLines      *int64  `json:"total_lines,omitempty"`
}

// GenerationMetaSpecFormat is one of "openapi", "graphql".
type GenerationMetaSpecFormat string

const (
	GenerationMetaSpecFormatOpenapi GenerationMetaSpecFormat = "openapi"
	GenerationMetaSpecFormatGraphql GenerationMetaSpecFormat = "graphql"
)

// GenerationMetaPrStatus is one of "opened", "no_changes", "blocked". Whether a destination pull request opened, was unnecessary because the generated tree already matched, or could not be opened.
type GenerationMetaPrStatus string

const (
	GenerationMetaPrStatusOpened    GenerationMetaPrStatus = "opened"
	GenerationMetaPrStatusNoChanges GenerationMetaPrStatus = "no_changes"
	GenerationMetaPrStatusBlocked   GenerationMetaPrStatus = "blocked"
)

// GenerationMetaBaseline is one of "destination", "last-generation", "none". What the diff was measured against; "destination" means the .typeship/surface.json merged in the destination repository.
type GenerationMetaBaseline string

const (
	GenerationMetaBaselineDestination    GenerationMetaBaseline = "destination"
	GenerationMetaBaselineLastGeneration GenerationMetaBaseline = "last-generation"
	GenerationMetaBaselineNone           GenerationMetaBaseline = "none"
)

// GenerationMetaPackageCompatibility is one of "success", "failure". The package compatibility verdict on the regeneration pull request; failure means breaking changes without a major version bump.
type GenerationMetaPackageCompatibility string

const (
	GenerationMetaPackageCompatibilitySuccess GenerationMetaPackageCompatibility = "success"
	GenerationMetaPackageCompatibilityFailure GenerationMetaPackageCompatibility = "failure"
)

// GenerationLimits Present when the generation was capped: by the free plan, or because the call was anonymous. Absent on uncapped generations.
type GenerationLimits struct {
	// MaxOperations How many operations this generation was allowed to include.
	MaxOperations int64 `json:"max_operations"`
	// OmittedOperations How many operations in the spec were left out.
	OmittedOperations int64                  `json:"omitted_operations"`
	Reason            GenerationLimitsReason `json:"reason"`
	// SignupURL Anonymous calls only. Where to create an account.
	SignupURL *string `json:"signup_url,omitempty"`
	// UpgradeURL Where the cap is lifted.
	UpgradeURL string `json:"upgrade_url"`
}

// GenerationLimitsReason is one of "anonymous", "free_plan".
type GenerationLimitsReason string

const (
	GenerationLimitsReasonAnonymous GenerationLimitsReason = "anonymous"
	GenerationLimitsReasonFreePlan  GenerationLimitsReason = "free_plan"
)

type GenerationResultClaim struct {
	URL       string `json:"url"`
	ExpiresAt string `json:"expires_at"`
}

type ProjectList struct {
	Object ListObject `json:"object"`
	Data   []Project  `json:"data"`
	// HasMore Whether another page is available after this one.
	HasMore bool `json:"has_more"`
	// NextCursor Pass this value as cursor to retrieve the next page; null on the last page.
	NextCursor string `json:"next_cursor"`
}

type ListObject string

type Project struct {
	ID       ProjectID       `json:"id"`
	Object   string          `json:"object"`
	Name     string          `json:"name"`
	Source   ProjectSource   `json:"source"`
	Packages ProjectPackages `json:"packages"`
	// AutoRegen Regenerate when the spec changes: on every push to the default branch for a repository source, every 30 minutes for a URL source. Off by default: the first generation is always one you asked for. Off means only "generate now" and POST /projects/{project_id}/generations regenerate.
	AutoRegen   bool        `json:"auto_regen"`
	SpecPatches []SpecPatch `json:"spec_patches"`
	Config      Config      `json:"config"`
	// MCPEnabled Whether the hosted MCP endpoint is on. Requires the MCP output and Enterprise; turning the output off turns this off.
	MCPEnabled bool `json:"mcp_enabled"`
	// MCPURL Path of the hosted MCP endpoint while it is on; read-only.
	MCPURL string `json:"mcp_url"`
	// RelayEnabled Whether the webhook relay is on, letting the generated CLI's webhooks listen command mint relay sessions. Requires the cli output and Pro; turning the output off turns this off.
	RelayEnabled bool `json:"relay_enabled"`
	// Outputs First-class generated outputs. Any non-empty combination is valid. Free keeps every selected output current for the first 25 operations in one linked project. On Pro, each selected output is billed once; shared implementation runtimes are included.
	Outputs   []OutputID `json:"outputs"`
	CreatedAt string     `json:"created_at"`
	// UpdatedAt When the project configuration last changed.
	UpdatedAt string `json:"updated_at"`
}

type ProjectID string

// ProjectSource is one of URLProjectSource, GithubProjectSource — The single source of truth for where a project's specification lives.
// Go has no sum types, so it holds the JSON as received and decodes on
// request: try the As* accessors, or switch on Discriminator() when the
// spec names one.
type ProjectSource struct {
	union json.RawMessage
}

// MarshalJSON writes the value as it was set or received.
func (u ProjectSource) MarshalJSON() ([]byte, error) {
	if u.union == nil {
		return []byte("null"), nil
	}
	return u.union, nil
}

// UnmarshalJSON keeps the raw JSON so any variant can be decoded later.
func (u *ProjectSource) UnmarshalJSON(data []byte) error {
	u.union = append(u.union[:0], data...)
	return nil
}

// Raw returns the JSON exactly as received.
func (u ProjectSource) Raw() json.RawMessage {
	return u.union
}

// Discriminator returns the "kind" field, which names the variant.
func (u ProjectSource) Discriminator() (string, error) {
	var probe struct {
		Kind string `json:"kind"`
	}
	if err := json.Unmarshal(u.union, &probe); err != nil {
		return "", err
	}
	return probe.Kind, nil
}

// AsURLProjectSource decodes the value as URLProjectSource.
func (u ProjectSource) AsURLProjectSource() (URLProjectSource, error) {
	var v URLProjectSource
	err := json.Unmarshal(u.union, &v)
	return v, err
}

// FromURLProjectSource sets the value to a URLProjectSource.
func (u *ProjectSource) FromURLProjectSource(v URLProjectSource) error {
	encoded, err := json.Marshal(v)
	if err != nil {
		return err
	}
	u.union = encoded
	return nil
}

// AsGithubProjectSource decodes the value as GithubProjectSource.
func (u ProjectSource) AsGithubProjectSource() (GithubProjectSource, error) {
	var v GithubProjectSource
	err := json.Unmarshal(u.union, &v)
	return v, err
}

// FromGithubProjectSource sets the value to a GithubProjectSource.
func (u *ProjectSource) FromGithubProjectSource(v GithubProjectSource) error {
	encoded, err := json.Marshal(v)
	if err != nil {
		return err
	}
	u.union = encoded
	return nil
}

type URLProjectSource struct {
	Kind string `json:"kind"`
	// URL URL fetched for every generation.
	URL string `json:"url"`
	// HeadersConfigured Whether Typeship has stored write-only request headers for this URL.
	HeadersConfigured bool `json:"headers_configured"`
}

type GithubProjectSource struct {
	Kind string `json:"kind"`
	// Repository GitHub repository in owner/name form.
	Repository string `json:"repository"`
	// Path Repository-relative path to the specification.
	Path string `json:"path"`
}

// ProjectPackages Complete package configuration. All ecosystems are returned even when their output is not selected, so saved delivery settings do not disappear when an output is disabled.
type ProjectPackages struct {
	Npm    ProjectPackageDelivery `json:"npm"`
	Python ProjectPackageDelivery `json:"python"`
	Go     ProjectPackageDelivery `json:"go"`
}

type ProjectPackageDelivery struct {
	Name        string             `json:"name"`
	Destination ProjectDestination `json:"destination"`
}

type ProjectDestination struct {
	Repo      string `json:"repo"`
	Directory string `json:"directory"`
}

// SpecPatch A fix applied to the spec before generation. Targets are JSON Pointers into the document. A patch whose target no longer exists is skipped and reported as a warning on the generation, never silently.
type SpecPatch struct {
	Op SpecPatchOp `json:"op"`
	// Path JSON-Pointer-style path. Pattern segments enable bulk fixes: * (any child), ** (any depth), [key=value] (filter), e.g. /paths/**/parameters/[name=account_id]/schema/type. Renaming a schema under /components/schemas also rewrites its $refs.
	Path string `json:"path"`
	// Value set only; the replacement value.
	Value any `json:"value,omitempty"`
	// To rename only; the new key name.
	To     *string `json:"to,omitempty"`
	Reason *string `json:"reason,omitempty"`
}

// SpecPatchOp is one of "set", "append", "remove", "rename".
type SpecPatchOp string

const (
	SpecPatchOpSet    SpecPatchOp = "set"
	SpecPatchOpAppend SpecPatchOp = "append"
	SpecPatchOpRemove SpecPatchOp = "remove"
	SpecPatchOpRename SpecPatchOp = "rename"
)

type CreateProjectRequest struct {
	Name   string             `json:"name"`
	Source ProjectSourceInput `json:"source"`
	// Outputs First-class outputs Typeship will keep current for this project.
	Outputs []OutputID `json:"outputs"`
	// Packages Initial package names and destinations. Omitted ecosystems use derived names and no destination.
	Packages *Packages `json:"packages,omitempty"`
	// AutoRegen Whether Typeship should regenerate automatically when the source changes.
	AutoRegen *bool `json:"auto_regen,omitempty"`
	// SpecPatches Initial patches. Omit or pass an empty array for none.
	SpecPatches []SpecPatch `json:"spec_patches,omitempty"`
	// MCPEnabled Serve this project as a hosted MCP endpoint. Requires the MCP output and Enterprise.
	MCPEnabled *bool `json:"mcp_enabled,omitempty"`
	// RelayEnabled Enable webhook relay sessions. Requires the CLI output and Pro.
	RelayEnabled *bool             `json:"relay_enabled,omitempty"`
	Config       *Nullable[Config] `json:"config,omitempty"`
}

// ProjectSourceInput is one of URLProjectSourceInput, GithubProjectSourceInput.
// Go has no sum types, so it holds the JSON as received and decodes on
// request: try the As* accessors, or switch on Discriminator() when the
// spec names one.
type ProjectSourceInput struct {
	union json.RawMessage
}

// MarshalJSON writes the value as it was set or received.
func (u ProjectSourceInput) MarshalJSON() ([]byte, error) {
	if u.union == nil {
		return []byte("null"), nil
	}
	return u.union, nil
}

// UnmarshalJSON keeps the raw JSON so any variant can be decoded later.
func (u *ProjectSourceInput) UnmarshalJSON(data []byte) error {
	u.union = append(u.union[:0], data...)
	return nil
}

// Raw returns the JSON exactly as received.
func (u ProjectSourceInput) Raw() json.RawMessage {
	return u.union
}

// Discriminator returns the "kind" field, which names the variant.
func (u ProjectSourceInput) Discriminator() (string, error) {
	var probe struct {
		Kind string `json:"kind"`
	}
	if err := json.Unmarshal(u.union, &probe); err != nil {
		return "", err
	}
	return probe.Kind, nil
}

// AsURLProjectSourceInput decodes the value as URLProjectSourceInput.
func (u ProjectSourceInput) AsURLProjectSourceInput() (URLProjectSourceInput, error) {
	var v URLProjectSourceInput
	err := json.Unmarshal(u.union, &v)
	return v, err
}

// FromURLProjectSourceInput sets the value to a URLProjectSourceInput.
func (u *ProjectSourceInput) FromURLProjectSourceInput(v URLProjectSourceInput) error {
	encoded, err := json.Marshal(v)
	if err != nil {
		return err
	}
	u.union = encoded
	return nil
}

// AsGithubProjectSourceInput decodes the value as GithubProjectSourceInput.
func (u ProjectSourceInput) AsGithubProjectSourceInput() (GithubProjectSourceInput, error) {
	var v GithubProjectSourceInput
	err := json.Unmarshal(u.union, &v)
	return v, err
}

// FromGithubProjectSourceInput sets the value to a GithubProjectSourceInput.
func (u *ProjectSourceInput) FromGithubProjectSourceInput(v GithubProjectSourceInput) error {
	encoded, err := json.Marshal(v)
	if err != nil {
		return err
	}
	u.union = encoded
	return nil
}

type URLProjectSourceInput struct {
	Kind string `json:"kind"`
	// URL URL of an OpenAPI document, GraphQL SDL file, or GraphQL endpoint.
	URL string `json:"url"`
	// Headers Request headers for a protected URL. Values are never returned or recorded in revision history. When updating the same URL, omit headers to preserve the stored values or pass null to remove them. Changing the URL without headers clears the old values so a credential is never forwarded to a different source.
	Headers map[string]string `json:"headers,omitempty"`
}

type GithubProjectSourceInput struct {
	Kind string `json:"kind"`
	// Repository GitHub repository in owner/name form.
	Repository string `json:"repository"`
	// Path Repository-relative path to the specification.
	Path string `json:"path"`
}

// Packages Delivery packages keyed by registry ecosystem. TypeScript SDK, CLI, and MCP share npm delivery without becoming the same output. Python and Go SDKs use their own package ecosystems.
type Packages struct {
	Npm    *PackageDelivery `json:"npm,omitempty"`
	Python *PackageDelivery `json:"python,omitempty"`
	Go     *PackageDelivery `json:"go,omitempty"`
}

// PackageDelivery Registry identity and reviewed pull-request destination for one delivery package.
type PackageDelivery struct {
	// Name npm package name, Python distribution name, or Go module path. Null derives a name from the API title.
	Name        *string      `json:"name,omitempty"`
	Destination *Destination `json:"destination,omitempty"`
}

// Destination Where regeneration pull requests land.
type Destination struct {
	// Repo Defaults to the source repository when the source is a repo.
	Repo *string `json:"repo,omitempty"`
	// Directory Directory the generated package is written to.
	Directory *string `json:"directory,omitempty"`
}

type DeletedProject struct {
	ID      ProjectID `json:"id"`
	Object  string    `json:"object"`
	Deleted bool      `json:"deleted"`
}

type UpdateProjectRequest struct {
	Name   *string             `json:"name,omitempty"`
	Source *ProjectSourceInput `json:"source,omitempty"`
	// Outputs Replaces the selected outputs; delivered files are not deleted.
	Outputs []OutputID `json:"outputs,omitempty"`
	// Packages Replaces package configuration for every ecosystem. Include any existing ecosystem settings you want to keep.
	Packages  *Packages `json:"packages,omitempty"`
	AutoRegen *bool     `json:"auto_regen,omitempty"`
	// SpecPatches Replaces the full patch list. Pass an empty array to clear it.
	SpecPatches []SpecPatch `json:"spec_patches,omitempty"`
	// MCPEnabled Serve this project as a hosted MCP endpoint. Requires the MCP output and Enterprise.
	MCPEnabled *bool `json:"mcp_enabled,omitempty"`
	// RelayEnabled Enable webhook relay sessions. Requires the CLI output and Pro.
	RelayEnabled *bool `json:"relay_enabled,omitempty"`
	// Config Replaces the entire configuration; pass null to clear it.
	Config *Nullable[Config] `json:"config,omitempty"`
}

// Language is one of "typescript", "python", "go".
type Language string

const (
	LanguageTypescript Language = "typescript"
	LanguagePython     Language = "python"
	LanguageGo         Language = "go"
)

type GenerationList struct {
	Object ListObject   `json:"object"`
	Data   []Generation `json:"data"`
	// HasMore Whether another page is available after this one.
	HasMore bool `json:"has_more"`
	// NextCursor Pass this value as cursor to retrieve the next page; null on the last page.
	NextCursor string `json:"next_cursor"`
}

type Generation struct {
	ID     GenerationID `json:"id"`
	Object string       `json:"object"`
	// FilesOmitted Present and true when the generated output was too large to inline; files_index lists paths, fetched one at a time via GET /generations/{generation_id}/file.
	FilesOmitted *bool             `json:"files_omitted,omitempty"`
	FilesIndex   []FileStub        `json:"files_index,omitempty"`
	ProjectID    ProjectID         `json:"project_id"`
	Status       GenerationStatus  `json:"status"`
	Trigger      GenerationTrigger `json:"trigger"`
	// Language Language this run generated. Null on generations recorded before projects had a language axis.
	Language Language `json:"language"`
	// Meta Null only for a failed or legacy generation that produced no metadata.
	Meta     GenerationMeta `json:"meta"`
	Warnings []string       `json:"warnings"`
	// Files Present on retrieve and create; omitted in lists.
	Files     []GeneratedFile `json:"files,omitempty"`
	Error     string          `json:"error"`
	CreatedAt string          `json:"created_at"`
}

type GenerationID string

type FileStub struct {
	Path  string `json:"path"`
	Bytes int64  `json:"bytes"`
}

// GenerationStatus is one of "succeeded", "failed".
type GenerationStatus string

const (
	GenerationStatusSucceeded GenerationStatus = "succeeded"
	GenerationStatusFailed    GenerationStatus = "failed"
)

// GenerationTrigger is one of "manual", "webhook", "poll", "preview".
type GenerationTrigger string

const (
	GenerationTriggerManual  GenerationTrigger = "manual"
	GenerationTriggerWebhook GenerationTrigger = "webhook"
	GenerationTriggerPoll    GenerationTrigger = "poll"
	GenerationTriggerPreview GenerationTrigger = "preview"
)

type GenerationBatch struct {
	Data []GenerationBatchDataItem `json:"data"`
}

// GenerationBatchDataItem is one of Generation, GenerationFailure.
// Go has no sum types, so it holds the JSON as received and decodes on
// request: try the As* accessors, or switch on Discriminator() when the
// spec names one.
type GenerationBatchDataItem struct {
	union json.RawMessage
}

// MarshalJSON writes the value as it was set or received.
func (u GenerationBatchDataItem) MarshalJSON() ([]byte, error) {
	if u.union == nil {
		return []byte("null"), nil
	}
	return u.union, nil
}

// UnmarshalJSON keeps the raw JSON so any variant can be decoded later.
func (u *GenerationBatchDataItem) UnmarshalJSON(data []byte) error {
	u.union = append(u.union[:0], data...)
	return nil
}

// Raw returns the JSON exactly as received.
func (u GenerationBatchDataItem) Raw() json.RawMessage {
	return u.union
}

// AsGeneration decodes the value as Generation.
func (u GenerationBatchDataItem) AsGeneration() (Generation, error) {
	var v Generation
	err := json.Unmarshal(u.union, &v)
	return v, err
}

// FromGeneration sets the value to a Generation.
func (u *GenerationBatchDataItem) FromGeneration(v Generation) error {
	encoded, err := json.Marshal(v)
	if err != nil {
		return err
	}
	u.union = encoded
	return nil
}

// AsGenerationFailure decodes the value as GenerationFailure.
func (u GenerationBatchDataItem) AsGenerationFailure() (GenerationFailure, error) {
	var v GenerationFailure
	err := json.Unmarshal(u.union, &v)
	return v, err
}

// FromGenerationFailure sets the value to a GenerationFailure.
func (u *GenerationBatchDataItem) FromGenerationFailure(v GenerationFailure) error {
	encoded, err := json.Marshal(v)
	if err != nil {
		return err
	}
	u.union = encoded
	return nil
}

// GenerationFailure A language that did not generate in a multi-language run.
type GenerationFailure struct {
	Language Language `json:"language"`
	Status   string   `json:"status"`
	Error    string   `json:"error"`
}

type SpecRevisionList struct {
	Object ListObject     `json:"object"`
	Data   []SpecRevision `json:"data"`
	// HasMore Whether another page is available after this one.
	HasMore bool `json:"has_more"`
	// NextCursor Pass this value as cursor to retrieve the next page; null on the last page.
	NextCursor string `json:"next_cursor"`
}

type SpecRevision struct {
	ID        SpecRevisionID `json:"id"`
	Object    string         `json:"object"`
	ProjectID ProjectID      `json:"project_id"`
	// Sha256 SHA-256 digest of the exact raw specification text.
	Sha256 string `json:"sha256"`
	// SizeBytes Size of the raw specification text in bytes.
	SizeBytes int64 `json:"size_bytes"`
	// Source Origin recorded when this immutable revision was created.
	Source    SpecRevisionSource `json:"source"`
	CreatedAt string             `json:"created_at"`
}

type SpecRevisionID string

// SpecRevisionSource is one of URLSpecRevisionSource, GithubSpecRevisionSource.
// Go has no sum types, so it holds the JSON as received and decodes on
// request: try the As* accessors, or switch on Discriminator() when the
// spec names one.
type SpecRevisionSource struct {
	union json.RawMessage
}

// MarshalJSON writes the value as it was set or received.
func (u SpecRevisionSource) MarshalJSON() ([]byte, error) {
	if u.union == nil {
		return []byte("null"), nil
	}
	return u.union, nil
}

// UnmarshalJSON keeps the raw JSON so any variant can be decoded later.
func (u *SpecRevisionSource) UnmarshalJSON(data []byte) error {
	u.union = append(u.union[:0], data...)
	return nil
}

// Raw returns the JSON exactly as received.
func (u SpecRevisionSource) Raw() json.RawMessage {
	return u.union
}

// Discriminator returns the "kind" field, which names the variant.
func (u SpecRevisionSource) Discriminator() (string, error) {
	var probe struct {
		Kind string `json:"kind"`
	}
	if err := json.Unmarshal(u.union, &probe); err != nil {
		return "", err
	}
	return probe.Kind, nil
}

// AsURLSpecRevisionSource decodes the value as URLSpecRevisionSource.
func (u SpecRevisionSource) AsURLSpecRevisionSource() (URLSpecRevisionSource, error) {
	var v URLSpecRevisionSource
	err := json.Unmarshal(u.union, &v)
	return v, err
}

// FromURLSpecRevisionSource sets the value to a URLSpecRevisionSource.
func (u *SpecRevisionSource) FromURLSpecRevisionSource(v URLSpecRevisionSource) error {
	encoded, err := json.Marshal(v)
	if err != nil {
		return err
	}
	u.union = encoded
	return nil
}

// AsGithubSpecRevisionSource decodes the value as GithubSpecRevisionSource.
func (u SpecRevisionSource) AsGithubSpecRevisionSource() (GithubSpecRevisionSource, error) {
	var v GithubSpecRevisionSource
	err := json.Unmarshal(u.union, &v)
	return v, err
}

// FromGithubSpecRevisionSource sets the value to a GithubSpecRevisionSource.
func (u *SpecRevisionSource) FromGithubSpecRevisionSource(v GithubSpecRevisionSource) error {
	encoded, err := json.Marshal(v)
	if err != nil {
		return err
	}
	u.union = encoded
	return nil
}

type URLSpecRevisionSource struct {
	Kind string `json:"kind"`
	URL  string `json:"url"`
}

type GithubSpecRevisionSource struct {
	Kind string `json:"kind"`
	// Repository GitHub repository in owner/name form.
	Repository string `json:"repository"`
	// Path Repository-relative specification path.
	Path string `json:"path"`
	// Ref Git ref resolved for this revision, when recorded.
	Ref *string `json:"ref,omitempty"`
	// CommitSha Exact Git commit consumed, when recorded.
	CommitSha *string `json:"commit_sha,omitempty"`
}

// Account The organization an API key belongs to. Members share its projects, keys, and plan; sign-in identity is not part of the API.
type Account struct {
	ID     string `json:"id"`
	Object string `json:"object"`
	// Name The organization's display name.
	Name      string      `json:"name"`
	Plan      AccountPlan `json:"plan"`
	CreatedAt string      `json:"created_at"`
}

// AccountPlan is one of "free", "pro", "enterprise".
type AccountPlan string

const (
	AccountPlanFree       AccountPlan = "free"
	AccountPlanPro        AccountPlan = "pro"
	AccountPlanEnterprise AccountPlan = "enterprise"
)

type APIKeyList struct {
	Object ListObject `json:"object"`
	Data   []APIKey   `json:"data"`
	// HasMore Whether another page is available after this one.
	HasMore bool `json:"has_more"`
	// NextCursor Pass this value as cursor to retrieve the next page; null on the last page.
	NextCursor string `json:"next_cursor"`
}

type APIKey struct {
	ID     string `json:"id"`
	Object string `json:"object"`
	Name   string `json:"name"`
	// Last4 Last four characters of the secret; the secret itself is never stored.
	Last4      string `json:"last4"`
	Revoked    bool   `json:"revoked"`
	LastUsedAt string `json:"last_used_at"`
	CreatedAt  string `json:"created_at"`
}
