// typeship — API types.
// Generated by typeship — https://typeship.dev — do not edit by hand.
package typeship

import "encoding/json"

// SpecInput The spec to generate from. Provide exactly one of url or inline.
type SpecInput struct {
	// URL Publicly reachable URL of an OpenAPI document, a GraphQL SDL file, or a GraphQL endpoint (introspected automatically). Fetched server-side.
	URL *string `json:"url,omitempty"`
	// Inline Raw spec text (OpenAPI JSON/YAML or GraphQL SDL). Up to 10MB.
	Inline *string `json:"inline,omitempty"`
}

// Platform is one of "sdk", "cli", "mcp".
type Platform string

const (
	PlatformSDK Platform = "sdk"
	PlatformCLI Platform = "cli"
	PlatformMCP Platform = "mcp"
)

// Language is one of "typescript", "python", "go".
type Language string

const (
	LanguageTypescript Language = "typescript"
	LanguagePython     Language = "python"
	LanguageGo         Language = "go"
)

// Config Everything typeship needs beyond the spec, in one object: generation customization (globals, retries, pagination) and how the generated tooling behaves (cli, mcp, docs_url). Plain configuration. typeship never requires vendor extensions inside the spec itself. The same shape is accepted on a project and on POST /generate.
type Config struct {
	// Globals Wire names of query/header parameters that become settable once on the generated client and auto-apply to every operation that accepts them; per-call values win. Names that match nothing are reported as generation warnings.
	Globals []string     `json:"globals,omitempty"`
	Retries *RetryTuning `json:"retries,omitempty"`
	// Pagination Per-operation pagination control, keyed by operationId or "METHOD /path". Unmatched keys are reported as generation warnings.
	Pagination map[string]ConfigPaginationValue `json:"pagination,omitempty"`
	Graphql    *GraphqlSettings                 `json:"graphql,omitempty"`
	CLI        *CLIBehavior                     `json:"cli,omitempty"`
	MCP        *MCPBehavior                     `json:"mcp,omitempty"`
	// DocsURL The API's documentation site. Read through its llms.txt by the generated CLI's docs command, the MCP server's docs tools, and the package's AGENTS.md. Defaults to the spec's externalDocs URL.
	DocsURL *string `json:"docs_url,omitempty"`
}

// RetryTuning Retry behavior. Top-level fields adjust every operation; operations maps operationId or "METHOD /path" keys to per-operation overrides.
type RetryTuning struct {
	MaxRetries *int64 `json:"max_retries,omitempty"`
	// Statuses Replaces the default retryable set (408, 429, 500, 502, 503, 504).
	Statuses       []int64 `json:"statuses,omitempty"`
	InitialDelayMs *int64  `json:"initial_delay_ms,omitempty"`
	MaxDelayMs     *int64  `json:"max_delay_ms,omitempty"`
	// RetryNonIdempotent Also retry non-idempotent methods (POST/PATCH).
	RetryNonIdempotent *bool `json:"retry_non_idempotent,omitempty"`
	// Disabled Shorthand for max_retries 0.
	Disabled   *bool                  `json:"disabled,omitempty"`
	Operations map[string]RetryTuning `json:"operations,omitempty"`
}

// ConfigPaginationValue is one of PaginationRule, bool.
// Go has no sum types, so it holds the JSON as received and decodes on
// request: try the As* accessors, or switch on Discriminator() when the
// spec names one.
type ConfigPaginationValue struct {
	union json.RawMessage
}

// MarshalJSON writes the value as it was set or received.
func (u ConfigPaginationValue) MarshalJSON() ([]byte, error) {
	if u.union == nil {
		return []byte("null"), nil
	}
	return u.union, nil
}

// UnmarshalJSON keeps the raw JSON so any variant can be decoded later.
func (u *ConfigPaginationValue) UnmarshalJSON(data []byte) error {
	u.union = append(u.union[:0], data...)
	return nil
}

// Raw returns the JSON exactly as received.
func (u ConfigPaginationValue) Raw() json.RawMessage {
	return u.union
}

// AsPaginationRule decodes the value as PaginationRule.
func (u ConfigPaginationValue) AsPaginationRule() (PaginationRule, error) {
	var v PaginationRule
	err := json.Unmarshal(u.union, &v)
	return v, err
}

// FromPaginationRule sets the value to a PaginationRule.
func (u *ConfigPaginationValue) FromPaginationRule(v PaginationRule) error {
	encoded, err := json.Marshal(v)
	if err != nil {
		return err
	}
	u.union = encoded
	return nil
}

// AsBool decodes the value as bool.
func (u ConfigPaginationValue) AsBool() (bool, error) {
	var v bool
	err := json.Unmarshal(u.union, &v)
	return v, err
}

// FromBool sets the value to a bool.
func (u *ConfigPaginationValue) FromBool(v bool) error {
	encoded, err := json.Marshal(v)
	if err != nil {
		return err
	}
	u.union = encoded
	return nil
}

type PaginationRule struct {
	Style *PaginationRuleStyle `json:"style,omitempty"`
	// ItemsField Response field holding the item array.
	ItemsField      string  `json:"items_field"`
	CursorParam     *string `json:"cursor_param,omitempty"`
	NextCursorField *string `json:"next_cursor_field,omitempty"`
	HasMoreField    *string `json:"has_more_field,omitempty"`
	IDField         *string `json:"id_field,omitempty"`
	PageParam       *string `json:"page_param,omitempty"`
	OffsetParam     *string `json:"offset_param,omitempty"`
	LimitParam      *string `json:"limit_param,omitempty"`
}

// PaginationRuleStyle is one of "cursor", "cursorFromLastId", "page", "offset".
type PaginationRuleStyle string

const (
	PaginationRuleStyleCursor           PaginationRuleStyle = "cursor"
	PaginationRuleStyleCursorFromLastID PaginationRuleStyle = "cursorFromLastId"
	PaginationRuleStylePage             PaginationRuleStyle = "page"
	PaginationRuleStyleOffset           PaginationRuleStyle = "offset"
)

// GraphqlSettings What a GraphQL schema cannot say about itself. Ignored for OpenAPI specs.
type GraphqlSettings struct {
	// Endpoint The URL every request is POSTed to; the generated client's default baseUrl. Defaults to the URL the schema was fetched from. Without either, baseUrl is a required client option.
	Endpoint *string `json:"endpoint,omitempty"`
	// Environments Named endpoints (sandbox, production). Each becomes a client environment; the first is the default unless endpoint is set.
	Environments []GraphqlSettingsEnvironmentsItem `json:"environments,omitempty"`
	// Auth How requests authenticate. bearer sends Authorization: Bearer; basic is for key-pair APIs (public key as username, private key as password); api_key sends a header named by api_key_header; none generates no auth option.
	Auth *GraphqlSettingsAuth `json:"auth,omitempty"`
	// APIKeyHeader Header carrying the key when auth is api_key. Default X-API-Key.
	APIKeyHeader *string `json:"api_key_header,omitempty"`
	// Title The API's name; drives the package and client names ("Braintree" gives braintree and BraintreeClient). Defaults to a name derived from the endpoint's host.
	Title *string `json:"title,omitempty"`
}

type GraphqlSettingsEnvironmentsItem struct {
	Name string `json:"name"`
	URL  string `json:"url"`
}

// GraphqlSettingsAuth is one of "bearer", "basic", "api_key", "none". How requests authenticate. bearer sends Authorization: Bearer; basic is for key-pair APIs (public key as username, private key as password); api_key sends a header named by api_key_header; none generates no auth option.
type GraphqlSettingsAuth string

const (
	GraphqlSettingsAuthBearer GraphqlSettingsAuth = "bearer"
	GraphqlSettingsAuthBasic  GraphqlSettingsAuth = "basic"
	GraphqlSettingsAuthAPIKey GraphqlSettingsAuth = "api_key"
	GraphqlSettingsAuthNone   GraphqlSettingsAuth = "none"
)

// CLIBehavior How the generated CLI behaves. Part of Config.
type CLIBehavior struct {
	// WhoamiOperation resource.method of a zero-argument GET that the generated CLI's whoami command calls. Overrides auto-detection; a value that matches nothing is reported as a generation warning.
	WhoamiOperation *string `json:"whoami_operation,omitempty"`
	// OauthClientID OAuth client id baked into the generated CLI for device-flow login. Without it, login prompts for a pasted credential.
	OauthClientID *string `json:"oauth_client_id,omitempty"`
	// OauthScopes Scopes requested during device-flow login. Include offline_access if the authorization server gates refresh tokens behind it.
	OauthScopes []string `json:"oauth_scopes,omitempty"`
	// OauthAudience Audience sent with the device-authorization request, for authorization servers that require one to issue API-valid access tokens.
	OauthAudience *string `json:"oauth_audience,omitempty"`
	// UpdateNotice Opt in to a once-a-day registry check that prints an upgrade hint. Off by default; generated code phones nobody unless this is enabled.
	UpdateNotice *bool `json:"update_notice,omitempty"`
	// SupportURL Where the generated CLI's feedback command sends users. GitHub issues/new URLs get a prefilled title and environment details.
	SupportURL *string `json:"support_url,omitempty"`
}

// MCPBehavior How the generated MCP server and the hosted endpoint behave. Part of Config.
type MCPBehavior struct {
	// ToolMode MCP tool shape. meta collapses per-operation tools into search_docs, read_docs, and execute so large APIs don't flood an agent's context window; auto switches to meta above 100 operations.
	ToolMode *MCPBehaviorToolMode `json:"tool_mode,omitempty"`
	// Instructions Guidance appended to the MCP server's instructions, which agents read once when they connect (server/discover): what to call first, conventions the spec does not state, what not to do. Carried by the package's server and the hosted endpoint alike.
	Instructions *string `json:"instructions,omitempty"`
	// ToolDescriptions Hand-written MCP tool descriptions keyed by operationId or "METHOD /path". Each replaces the text typeship derives for that operation (summary, first sentence, method and path, deprecation and auth notes). For flows the spec cannot describe, such as a multi-step upload. Keys that match no operation are reported as generation warnings.
	ToolDescriptions map[string]string `json:"tool_descriptions,omitempty"`
}

// MCPBehaviorToolMode is one of "auto", "operations", "meta". MCP tool shape. meta collapses per-operation tools into search_docs, read_docs, and execute so large APIs don't flood an agent's context window; auto switches to meta above 100 operations.
type MCPBehaviorToolMode string

const (
	MCPBehaviorToolModeAuto       MCPBehaviorToolMode = "auto"
	MCPBehaviorToolModeOperations MCPBehaviorToolMode = "operations"
	MCPBehaviorToolModeMeta       MCPBehaviorToolMode = "meta"
)

type GenerationResult struct {
	Files    []GeneratedFile   `json:"files"`
	Warnings []string          `json:"warnings"`
	Meta     GenerationMeta    `json:"meta"`
	Limits   *GenerationLimits `json:"limits,omitempty"`
	// Claim Anonymous, URL-sourced generations only. A link a signed-in person can open to turn this run into a project in their organization (same spec, language, platforms, config). Lasts seven days. Null for inline specs; absent on keyed calls.
	Claim *GenerationResultClaim `json:"claim,omitempty"`
}

type GeneratedFile struct {
	// Path Repo-relative path inside the generated package.
	Path    string `json:"path"`
	Content string `json:"content"`
}

type GenerationMeta struct {
	Title      string                    `json:"title"`
	Version    string                    `json:"version"`
	SpecFormat *GenerationMetaSpecFormat `json:"spec_format,omitempty"`
	// OasVersion Detected spec version, "2.0", "3.0", or "3.1".
	OasVersion string `json:"oas_version"`
	// Converted True when the input was Swagger 2.0 and was converted.
	Converted               *bool      `json:"converted,omitempty"`
	PackageName             string     `json:"package_name"`
	ClientName              string     `json:"client_name"`
	Targets                 []Platform `json:"targets"`
	ResourceCount           *int64     `json:"resource_count,omitempty"`
	OperationCount          *int64     `json:"operation_count,omitempty"`
	SchemaCount             *int64     `json:"schema_count,omitempty"`
	PaginatedOperationCount *int64     `json:"paginated_operation_count,omitempty"`
	// OmittedOperationCount Operations beyond the plan's endpoint allowance, not generated.
	OmittedOperationCount *int64 `json:"omitted_operation_count,omitempty"`
	// PrURL Pull request opened by this regeneration, when one was.
	PrURL    *string `json:"pr_url,omitempty"`
	PrNumber *int64  `json:"pr_number,omitempty"`
	// Changelog Markdown changelog entry for this regeneration, from the API surface diff. Absent on a first generation or when nothing changed.
	Changelog *string `json:"changelog,omitempty"`
	// BreakingCount Breaking changes in the diff; removed methods and fields, changed types, inputs that became required.
	BreakingCount *int64 `json:"breaking_count,omitempty"`
	// Baseline What the diff was measured against; "destination" means the .typeship/surface.json merged in the destination repository.
	Baseline *GenerationMetaBaseline `json:"baseline,omitempty"`
	// Semver The typeship/semver verdict on the regeneration pull request; failure means breaking changes without a major version bump.
	Semver *GenerationMetaSemver `json:"semver,omitempty"`
	// SemverNote The verdict in one line, as the commit status describes it.
	SemverNote *string `json:"semver_note,omitempty"`
	// PreviousVersion The package version the destination had before this regeneration.
	PreviousVersion *string `json:"previous_version,omitempty"`
	FileCount       *int64  `json:"file_count,omitempty"`
	TotalLines      *int64  `json:"total_lines,omitempty"`
}

// GenerationMetaSpecFormat is one of "openapi", "graphql".
type GenerationMetaSpecFormat string

const (
	GenerationMetaSpecFormatOpenapi GenerationMetaSpecFormat = "openapi"
	GenerationMetaSpecFormatGraphql GenerationMetaSpecFormat = "graphql"
)

// GenerationMetaBaseline is one of "destination", "last-generation", "none". What the diff was measured against; "destination" means the .typeship/surface.json merged in the destination repository.
type GenerationMetaBaseline string

const (
	GenerationMetaBaselineDestination    GenerationMetaBaseline = "destination"
	GenerationMetaBaselineLastGeneration GenerationMetaBaseline = "last-generation"
	GenerationMetaBaselineNone           GenerationMetaBaseline = "none"
)

// GenerationMetaSemver is one of "success", "failure". The typeship/semver verdict on the regeneration pull request; failure means breaking changes without a major version bump.
type GenerationMetaSemver string

const (
	GenerationMetaSemverSuccess GenerationMetaSemver = "success"
	GenerationMetaSemverFailure GenerationMetaSemver = "failure"
)

// GenerationLimits Present when the generation was capped: by the free plan, or because the call was anonymous. Absent on uncapped generations.
type GenerationLimits struct {
	// MaxOperations How many operations this generation was allowed to include.
	MaxOperations int64 `json:"max_operations"`
	// OmittedOperations How many operations in the spec were left out.
	OmittedOperations int64                  `json:"omitted_operations"`
	Reason            GenerationLimitsReason `json:"reason"`
	// SignupURL Anonymous calls only. Where to create an account.
	SignupURL *string `json:"signup_url,omitempty"`
	// UpgradeURL Where the cap is lifted.
	UpgradeURL string `json:"upgrade_url"`
}

// GenerationLimitsReason is one of "anonymous", "free_plan".
type GenerationLimitsReason string

const (
	GenerationLimitsReasonAnonymous GenerationLimitsReason = "anonymous"
	GenerationLimitsReasonFreePlan  GenerationLimitsReason = "free_plan"
)

type GenerationResultClaim struct {
	URL       string `json:"url"`
	ExpiresAt string `json:"expires_at"`
}

type ProjectsListResponse struct {
	Data       []Project `json:"data"`
	NextCursor *string   `json:"next_cursor,omitempty"`
}

type Project struct {
	ID     string `json:"id"`
	Object string `json:"object"`
	Name   string `json:"name"`
	// SpecURL The source URL when the source kind is url; null otherwise.
	SpecURL     *string      `json:"spec_url,omitempty"`
	Source      Source       `json:"source"`
	Destination *Destination `json:"destination,omitempty"`
	// Languages Languages this project generates. Each is a separate package, a separate pull request, and a separate hosted generation. Defaults to typescript alone.
	Languages []Language `json:"languages,omitempty"`
	// Destinations Where each language's pull request lands, keyed by language. A repository each is the convention API vendors follow, and Go requires it since `go get` resolves a module to the repository root. Several languages may share a repository with different directories, producing one pull request.
	Destinations map[string]Destination `json:"destinations,omitempty"`
	// PackageNames Registry name per language. The ecosystems disagree about what a name is: npm takes an optional @scope, PyPI normalizes to lowercase-with-hyphens, and Go's name is the module path that `go get` resolves. Unset means the name is derived from the API's title.
	PackageNames map[string]string `json:"package_names,omitempty"`
	// AutoRegen Regenerate when the spec changes: on every push to the default branch for a repository source, every 30 minutes for a URL source. Off by default: the first generation is always one you asked for. Off means only "generate now" and POST /projects/{project_id}/generations regenerate.
	AutoRegen bool `json:"auto_regen"`
	// PackageName npm name override for generated output; supports @scope/name.
	PackageName *string     `json:"package_name,omitempty"`
	SpecPatches []SpecPatch `json:"spec_patches,omitempty"`
	Config      *Config     `json:"config,omitempty"`
	// MCPEnabled Whether the hosted MCP endpoint is on. Requires the mcp platform and Enterprise; turning the platform off turns this off.
	MCPEnabled *bool `json:"mcp_enabled,omitempty"`
	// MCPURL Path of the hosted MCP endpoint while it is on; read-only.
	MCPURL *string `json:"mcp_url,omitempty"`
	// RelayEnabled Whether the webhook relay is on, letting the generated CLI's webhooks listen command mint relay sessions. Requires the cli platform and Pro; turning the platform off turns this off.
	RelayEnabled *bool `json:"relay_enabled,omitempty"`
	// Platforms Artifacts this project builds from its spec. sdk is always present and stands for the SDK in each of `languages`; cli and mcp are built on the TypeScript SDK and ship in its package, so they require typescript among the languages. Each SDK language and each of cli and mcp is one platform for billing.
	Platforms []Platform `json:"platforms"`
	CreatedAt string     `json:"created_at"`
}

// Source Where the project's spec lives.
type Source struct {
	Kind SourceKind `json:"kind"`
	// URL kind url. Fetched server-side for every generation.
	URL *string `json:"url,omitempty"`
	// Repo kind repo, "owner/name". Watched via the GitHub App.
	Repo *string `json:"repo,omitempty"`
	// Path Path of the spec file inside the repository.
	Path *string `json:"path,omitempty"`
}

// SourceKind is one of "url", "repo".
type SourceKind string

const (
	SourceKindURL  SourceKind = "url"
	SourceKindRepo SourceKind = "repo"
)

// Destination Where regeneration pull requests land.
type Destination struct {
	// Repo Defaults to the source repository when the source is a repo.
	Repo *string `json:"repo,omitempty"`
	// Directory Directory the generated package is written to.
	Directory *string `json:"directory,omitempty"`
}

// SpecPatch A fix applied to the spec before generation. Targets are JSON Pointers into the document. A patch whose target no longer exists is skipped and reported as a warning on the generation, never silently.
type SpecPatch struct {
	Op SpecPatchOp `json:"op"`
	// Path JSON-Pointer-style path. Pattern segments enable bulk fixes: * (any child), ** (any depth), [key=value] (filter), e.g. /paths/**/parameters/[name=account_id]/schema/type. Renaming a schema under /components/schemas also rewrites its $refs.
	Path string `json:"path"`
	// Value set only; the replacement value.
	Value any `json:"value,omitempty"`
	// To rename only; the new key name.
	To     *string `json:"to,omitempty"`
	Reason *string `json:"reason,omitempty"`
}

// SpecPatchOp is one of "set", "append", "remove", "rename".
type SpecPatchOp string

const (
	SpecPatchOpSet    SpecPatchOp = "set"
	SpecPatchOpAppend SpecPatchOp = "append"
	SpecPatchOpRemove SpecPatchOp = "remove"
	SpecPatchOpRename SpecPatchOp = "rename"
)

type ProjectsDeleteResponse struct {
	Deleted bool `json:"deleted"`
}

type ProjectsListGenerationsResponse struct {
	Data       []Generation `json:"data"`
	NextCursor *string      `json:"next_cursor,omitempty"`
}

type Generation struct {
	ID     string `json:"id"`
	Object string `json:"object"`
	// FilesOmitted Present and true when the generated output was too large to inline; files_index lists paths, fetched one at a time via GET /generations/{generation_id}/file.
	FilesOmitted *bool             `json:"files_omitted,omitempty"`
	FilesIndex   []FileStub        `json:"files_index,omitempty"`
	ProjectID    *string           `json:"project_id,omitempty"`
	Status       GenerationStatus  `json:"status"`
	Trigger      GenerationTrigger `json:"trigger"`
	// Language Language this run generated. Null on generations recorded before projects had a language axis.
	Language *Language       `json:"language,omitempty"`
	Meta     *GenerationMeta `json:"meta,omitempty"`
	Warnings []string        `json:"warnings,omitempty"`
	// Files Present on retrieve and create; omitted in lists.
	Files     []GeneratedFile `json:"files,omitempty"`
	Error     *string         `json:"error,omitempty"`
	CreatedAt string          `json:"created_at"`
}

type FileStub struct {
	Path  string `json:"path"`
	Bytes int64  `json:"bytes"`
}

// GenerationStatus is one of "succeeded", "failed".
type GenerationStatus string

const (
	GenerationStatusSucceeded GenerationStatus = "succeeded"
	GenerationStatusFailed    GenerationStatus = "failed"
)

// GenerationTrigger is one of "manual", "webhook", "poll", "preview".
type GenerationTrigger string

const (
	GenerationTriggerManual  GenerationTrigger = "manual"
	GenerationTriggerWebhook GenerationTrigger = "webhook"
	GenerationTriggerPoll    GenerationTrigger = "poll"
	GenerationTriggerPreview GenerationTrigger = "preview"
)

type ProjectsGenerateResponse struct {
	Data []ProjectsGenerateResponseDataItem `json:"data"`
}

// ProjectsGenerateResponseDataItem is one of Generation, GenerationFailure.
// Go has no sum types, so it holds the JSON as received and decodes on
// request: try the As* accessors, or switch on Discriminator() when the
// spec names one.
type ProjectsGenerateResponseDataItem struct {
	union json.RawMessage
}

// MarshalJSON writes the value as it was set or received.
func (u ProjectsGenerateResponseDataItem) MarshalJSON() ([]byte, error) {
	if u.union == nil {
		return []byte("null"), nil
	}
	return u.union, nil
}

// UnmarshalJSON keeps the raw JSON so any variant can be decoded later.
func (u *ProjectsGenerateResponseDataItem) UnmarshalJSON(data []byte) error {
	u.union = append(u.union[:0], data...)
	return nil
}

// Raw returns the JSON exactly as received.
func (u ProjectsGenerateResponseDataItem) Raw() json.RawMessage {
	return u.union
}

// AsGeneration decodes the value as Generation.
func (u ProjectsGenerateResponseDataItem) AsGeneration() (Generation, error) {
	var v Generation
	err := json.Unmarshal(u.union, &v)
	return v, err
}

// FromGeneration sets the value to a Generation.
func (u *ProjectsGenerateResponseDataItem) FromGeneration(v Generation) error {
	encoded, err := json.Marshal(v)
	if err != nil {
		return err
	}
	u.union = encoded
	return nil
}

// AsGenerationFailure decodes the value as GenerationFailure.
func (u ProjectsGenerateResponseDataItem) AsGenerationFailure() (GenerationFailure, error) {
	var v GenerationFailure
	err := json.Unmarshal(u.union, &v)
	return v, err
}

// FromGenerationFailure sets the value to a GenerationFailure.
func (u *ProjectsGenerateResponseDataItem) FromGenerationFailure(v GenerationFailure) error {
	encoded, err := json.Marshal(v)
	if err != nil {
		return err
	}
	u.union = encoded
	return nil
}

// GenerationFailure A language that did not generate in a multi-language run.
type GenerationFailure struct {
	Language Language `json:"language"`
	Status   string   `json:"status"`
	Error    string   `json:"error"`
}

type MCPUsage struct {
	Object    string `json:"object"`
	ProjectID string `json:"project_id"`
	// MCPURL The hosted endpoint URL, or null when it is off.
	MCPURL *string `json:"mcp_url,omitempty"`
	// Days The window these numbers cover.
	Days int64 `json:"days"`
	// Calls Tool calls served, including ones that returned an error.
	Calls int64 `json:"calls"`
	// Errors Calls whose result was a tool error (API failures, bad arguments).
	Errors int64 `json:"errors"`
	// RateLimited Calls turned away by the per-caller or per-endpoint limit.
	RateLimited int64 `json:"rate_limited"`
	// AvgDurationMs Mean upstream request time across served calls.
	AvgDurationMs int64                `json:"avg_duration_ms"`
	ByTool        []MCPUsageByToolItem `json:"by_tool"`
}

type MCPUsageByToolItem struct {
	Tool   string `json:"tool"`
	Calls  int64  `json:"calls"`
	Errors int64  `json:"errors"`
}

type SpecVersionsListResponse struct {
	Data       []SpecVersion `json:"data"`
	NextCursor *string       `json:"next_cursor,omitempty"`
}

type SpecVersion struct {
	ID        string `json:"id"`
	Object    string `json:"object"`
	ProjectID string `json:"project_id"`
	// Hash sha256 of the raw spec text; the version's identity.
	Hash  string `json:"hash"`
	Bytes *int64 `json:"bytes,omitempty"`
	// Source Where this spec came from — a URL, or a repo and path.
	Source map[string]any `json:"source,omitempty"`
	// Content The raw spec text. Present on retrieve, omitted from lists, and replaced by content_omitted when the spec is too large to inline.
	Content *string `json:"content,omitempty"`
	// ContentOmitted Present and true when the spec was too large to inline; fetch it from /spec_versions/{spec_version_id}/content.
	ContentOmitted *bool  `json:"content_omitted,omitempty"`
	CreatedAt      string `json:"created_at"`
}

// Account The organization an API key belongs to. Members share its projects, keys, and plan; sign-in identity is not part of the API.
type Account struct {
	ID     string `json:"id"`
	Object string `json:"object"`
	// Name The organization's display name.
	Name      string      `json:"name"`
	Plan      AccountPlan `json:"plan"`
	CreatedAt string      `json:"created_at"`
}

// AccountPlan is one of "free", "pro", "enterprise".
type AccountPlan string

const (
	AccountPlanFree       AccountPlan = "free"
	AccountPlanPro        AccountPlan = "pro"
	AccountPlanEnterprise AccountPlan = "enterprise"
)

type Usage struct {
	Object            string                 `json:"object"`
	HostedGenerations UsageHostedGenerations `json:"hosted_generations"`
	// IncludedEndpoints Endpoints included before per-endpoint billing applies.
	IncludedEndpoints int64 `json:"included_endpoints"`
	// Requests Who called the API in the last 30 days, read from the User-Agent the generated tooling sends: by surface (cli, mcp, sdk, http) and by agent harness (claude-code, codex, cursor, ...), and the share of requests that came through an agent.
	Requests *UsageRequests `json:"requests,omitempty"`
}

type UsageHostedGenerations struct {
	Used int64 `json:"used"`
	// Included Null on paid plans, which meter rather than cap.
	Included  *int64 `json:"included,omitempty"`
	Remaining *int64 `json:"remaining,omitempty"`
}

// UsageRequests Who called the API in the last 30 days, read from the User-Agent the generated tooling sends: by surface (cli, mcp, sdk, http) and by agent harness (claude-code, codex, cursor, ...), and the share of requests that came through an agent.
type UsageRequests struct {
	Days      int64            `json:"days"`
	Requests  int64            `json:"requests"`
	BySurface map[string]int64 `json:"by_surface"`
	ByHarness map[string]int64 `json:"by_harness"`
	// AgentShare 0 to 1.
	AgentShare float64 `json:"agent_share"`
}

type APIKeysListResponse struct {
	Data       []APIKey `json:"data"`
	NextCursor *string  `json:"next_cursor,omitempty"`
}

type APIKey struct {
	ID     string `json:"id"`
	Object string `json:"object"`
	Name   string `json:"name"`
	// Last4 Last four characters of the secret; the secret itself is never stored.
	Last4      string  `json:"last4"`
	Revoked    bool    `json:"revoked"`
	LastUsedAt *string `json:"last_used_at,omitempty"`
	CreatedAt  string  `json:"created_at"`
}
