// typeship — organization.
// Generated by typeship — https://typeship.dev
package typeship

import (
	"context"
)

// OrganizationService accesses the organization endpoints.
type OrganizationService struct {
	core *core
}

// Get the Organization.
//
// Returns the organization associated with your credential. The Typeship CLI uses this endpoint for `whoami`.
//
// GET /organization
func (s *OrganizationService) Get(ctx context.Context, opts ...RequestOption) (*Organization, error) {
	req := request{
		Method:     "GET",
		Path:       "/organization",
		Errors:     map[string]func(int, []byte, string) error{"401": newUnauthorizedError, "403": newForbiddenError, "429": newRateLimitedError, "500": newInternalServerError},
		Security:   []map[string][]string{{"apiKey": {}}},
		SchemaKey:  "organization.get",
		Idempotent: true,
	}
	var out Organization
	if err := s.core.do(ctx, req, &out, opts...); err != nil {
		return nil, err
	}
	return &out, nil
}
