// typeship — packages.
// Generated by typeship — https://typeship.dev
package typeship

import (
	"context"
	"fmt"
)

// PackagesService accesses the packages endpoints.
type PackagesService struct {
	core *core
}

// PackagesGenerateParams are the inputs for PackagesService.Generate.
type PackagesGenerateParams struct {
	// IdempotencyKey Identifies one logical write for 24 hours. The key is scoped to the authenticated organization and operation; generation without an organization uses a hashed network identity. Retrying the same method, path, query, If-Match header, and JSON body replays the original response. Reusing the key with changed intent returns 409. After expiry the key starts a new write.
	IdempotencyKey *string `json:"-"`
}

// PackagesDownloadParams are the inputs for PackagesService.Download.
type PackagesDownloadParams struct {
	// Token Private download token from download.url in the generation result.
	Token string `json:"-"`
}

// Generate a package.
//
// Returns one generated package without creating a Project.
//
// Supports [idempotent retries](https://typeship.dev/docs/typeship-api/idempotency); keyed responses include generated files in the replay cache.
//
// Use `download.url` to save the complete ZIP, verify `download.sha256`, and extract it into an empty directory. The link expires at `download.expires_at` and grants access to anyone who has it. CLI, MCP, and SDK calls supply an idempotency key automatically. Agents should request `fields=["download","coverage","warnings","claim"]` to keep the MCP result compact; files can exceed the response limit. Download the ZIP instead of repeating generation to retrieve omitted files.
//
// Anonymous and Free requests include the first 25 operations. Paid plans include all operations. Anonymous requests are rate limited by IP address. Check `coverage` for omitted operations; an invalid API key returns `401`.
//
// An anonymous URL request without source headers may return `claim.url`. Sign in through that link within seven days to save the recipe as a Project.
//
// POST /generate
func (s *PackagesService) Generate(ctx context.Context, body GenerateRequest, params *PackagesGenerateParams, opts ...RequestOption) (*GenerationResult, error) {
	headers := map[string]string{}
	if params != nil {
		if params.IdempotencyKey != nil {
			headers["Idempotency-Key"] = fmt.Sprint(*params.IdempotencyKey)
		}
	}
	req := request{
		Method:            "POST",
		Path:              "/generate",
		Headers:           headers,
		Body:              body,
		Errors:            map[string]func(int, []byte, string) error{"400": newBadRequestError, "401": newUnauthorizedError, "403": newForbiddenError, "409": newConflictError, "413": newPayloadTooLargeError, "422": newUnprocessableEntityError, "429": newRateLimitedError, "500": newInternalServerError, "default": newAPIResponseError},
		Security:          []map[string][]string{{}, {"apiKey": {}}},
		SchemaKey:         "packages.generate",
		IdempotencyHeader: "Idempotency-Key",
	}
	var out GenerationResult
	if err := s.core.do(ctx, req, &out, opts...); err != nil {
		return nil, notModified(err)
	}
	return &out, nil
}

// Download a generated package.
//
// Download the complete ZIP referenced by `packages_generate`'s `download.url`. Pass the token from that URL. No API key is needed; the token grants access only to that exact package until its replay window expires. Keep the token private.
//
// The local MCP server saves this binary response to disk. On a hosted MCP connection, download the original URL directly to your workspace. Verify the ZIP against `download.sha256` before extracting it into an empty directory. Expired or invalid tokens return `404`; a new generation creates a new download.
//
// GET /generate/download
func (s *PackagesService) Download(ctx context.Context, params PackagesDownloadParams, opts ...RequestOption) ([]byte, error) {
	query := map[string]any{}
	query["token"] = params.Token
	req := request{
		Method:     "GET",
		Path:       "/generate/download",
		Query:      query,
		Errors:     map[string]func(int, []byte, string) error{"400": newBadRequestError, "404": newNotFoundError, "429": newRateLimitedError, "500": newInternalServerError},
		Security:   []map[string][]string{{}},
		SchemaKey:  "packages.download",
		Idempotent: true,
	}
	var out []byte
	if err := s.core.do(ctx, req, &out, opts...); err != nil {
		return nil, notModified(err)
	}
	return out, nil
}
