// Pagination.
// Generated by typeship — https://typeship.dev — do not edit by hand.
package typeship

import (
	"context"
	"encoding/json"
	"strings"
)

type pageConfig struct {
	Style           string
	ItemsField      string
	CursorParam     string
	NextCursorField string
	HasMoreField    string
	IDField         string
	PageParam       string
	OffsetParam     string
	LimitParam      string
}

// Iter walks every page of a list endpoint, fetching lazily:
//
//	it := client.Accounts.List(ctx, nil)
//	for it.Next() {
//		account := it.Value()
//	}
//	if err := it.Err(); err != nil {
//		return err
//	}
type Iter[T any] struct {
	ctx     context.Context
	core    *core
	req     request
	opts    []RequestOption
	cfg     pageConfig
	items   []T
	index   int
	current T
	done    bool
	page    int
	offset  int
	err     error
	started bool
}

func newIter[T any](ctx context.Context, c *core, req request, opts []RequestOption, cfg pageConfig) *Iter[T] {
	if req.Query == nil {
		req.Query = map[string]any{}
	}
	it := &Iter[T]{ctx: ctx, core: c, req: req, opts: opts, cfg: cfg, page: 1}
	// Start where the caller pointed: list(page=3) walks 3, 4, 5, ...
	if cfg.PageParam != "" {
		if page, ok := queryInt(req.Query[cfg.PageParam]); ok && page > 0 {
			it.page = page
		}
	}
	if cfg.OffsetParam != "" {
		if offset, ok := queryInt(req.Query[cfg.OffsetParam]); ok && offset > 0 {
			it.offset = offset
		}
	}
	return it
}

// queryInt reads an integer query value however the params struct typed it.
func queryInt(value any) (int, bool) {
	switch typed := value.(type) {
	case int:
		return typed, true
	case int32:
		return int(typed), true
	case int64:
		return int(typed), true
	case float64:
		return int(typed), true
	}
	return 0, false
}

// pageExhausted reports whether a page/offset walk can stop early: a page
// shorter than the requested limit is the last one, which spares a final
// empty request — and ends the walk on servers that answer out-of-range
// pages by repeating the last one.
func (it *Iter[T]) pageExhausted(count int) bool {
	if it.cfg.LimitParam == "" {
		return false
	}
	limit, ok := queryInt(it.req.Query[it.cfg.LimitParam])
	return ok && limit > 0 && count < limit
}

// Next advances to the next item, fetching another page when the current one
// is exhausted. It reports false when the pages run out or a fetch fails.
func (it *Iter[T]) Next() bool {
	if it.err != nil {
		return false
	}
	if it.index < len(it.items) {
		it.current = it.items[it.index]
		it.index++
		return true
	}
	if it.done || (it.started && len(it.items) == 0) {
		return false
	}
	if !it.fetch() {
		return false
	}
	return it.Next()
}

// Value returns the item Next just advanced to.
func (it *Iter[T]) Value() T { return it.current }

// Err returns the first error encountered, if any.
func (it *Iter[T]) Err() error { return it.err }

func (it *Iter[T]) fetch() bool {
	var raw map[string]json.RawMessage
	if err := it.core.do(it.ctx, it.req, &raw, it.opts...); err != nil {
		it.err = err
		return false
	}
	it.started = true

	itemsRaw, ok := lookupPath(raw, it.cfg.ItemsField)
	if !ok {
		it.done = true
		return false
	}
	var items []T
	if err := json.Unmarshal(itemsRaw, &items); err != nil {
		it.err = err
		return false
	}
	it.items = items
	it.index = 0
	if len(items) == 0 {
		it.done = true
		return false
	}

	if it.cfg.HasMoreField != "" {
		if moreRaw, ok := lookupPath(raw, it.cfg.HasMoreField); ok {
			var more bool
			if err := json.Unmarshal(moreRaw, &more); err == nil && !more {
				it.done = true
				return true
			}
		}
	}

	switch it.cfg.Style {
	case "cursor":
		nextRaw, ok := lookupPath(raw, it.cfg.NextCursorField)
		if !ok {
			it.done = true
			return true
		}
		var cursor *string
		if err := json.Unmarshal(nextRaw, &cursor); err != nil || cursor == nil || *cursor == "" {
			it.done = true
			return true
		}
		it.req.Query[it.cfg.CursorParam] = *cursor
	case "cursorFromLastId":
		var rows []map[string]any
		if err := json.Unmarshal(itemsRaw, &rows); err != nil || len(rows) == 0 {
			it.done = true
			return true
		}
		field := it.cfg.IDField
		if field == "" {
			field = "id"
		}
		last, ok := rows[len(rows)-1][field].(string)
		if !ok || last == "" {
			it.done = true
			return true
		}
		it.req.Query[it.cfg.CursorParam] = last
	case "page":
		if it.pageExhausted(len(items)) {
			it.done = true
			return true
		}
		it.page++
		it.req.Query[it.cfg.PageParam] = it.page
	case "offset":
		if it.pageExhausted(len(items)) {
			it.done = true
			return true
		}
		it.offset += len(items)
		it.req.Query[it.cfg.OffsetParam] = it.offset
	default:
		it.done = true
	}
	return true
}

// lookupPath resolves a dot path so pagination can read meta.next_cursor.
func lookupPath(raw map[string]json.RawMessage, path string) (json.RawMessage, bool) {
	if path == "" {
		return nil, false
	}
	parts := strings.Split(path, ".")
	current := raw
	for i, part := range parts {
		value, ok := current[part]
		if !ok {
			return nil, false
		}
		if i == len(parts)-1 {
			return value, true
		}
		var nested map[string]json.RawMessage
		if err := json.Unmarshal(value, &nested); err != nil {
			return nil, false
		}
		current = nested
	}
	return nil, false
}
