// Pagination.
// Generated by typeship — https://typeship.dev — do not edit by hand.
package typeship

import (
	"context"
	"encoding/json"
	"strings"
)

type pageConfig struct {
	Style           string
	ItemsField      string
	CursorParam     string
	NextCursorField string
	HasMoreField    string
	IDField         string
	PageParam       string
	OffsetParam     string
	LimitParam      string
}

// Iter walks every page of a list endpoint, fetching lazily:
//
//	it := client.Accounts.List(ctx, nil)
//	for it.Next() {
//		account := it.Value()
//	}
//	if err := it.Err(); err != nil {
//		return err
//	}
type Iter[T any] struct {
	ctx     context.Context
	core    *core
	req     request
	opts    []RequestOption
	cfg     pageConfig
	items   []T
	index   int
	current T
	done    bool
	page    int
	offset  int
	err     error
	started bool
}

func newIter[T any](ctx context.Context, c *core, req request, opts []RequestOption, cfg pageConfig) *Iter[T] {
	if req.Query == nil {
		req.Query = map[string]any{}
	}
	it := &Iter[T]{ctx: ctx, core: c, req: req, opts: opts, cfg: cfg, page: 1}

	return it
}

// Next advances to the next item, fetching another page when the current one
// is exhausted. It reports false when the pages run out or a fetch fails.
func (it *Iter[T]) Next() bool {
	if it.err != nil {
		return false
	}
	if it.index < len(it.items) {
		it.current = it.items[it.index]
		it.index++
		return true
	}
	if it.done || (it.started && len(it.items) == 0 && it.cfg.Style != "cursor") {
		return false
	}
	if !it.fetch() {
		return false
	}
	return it.Next()
}

// Value returns the item Next just advanced to.
func (it *Iter[T]) Value() T { return it.current }

// Err returns the first error encountered, if any.
func (it *Iter[T]) Err() error { return it.err }

func (it *Iter[T]) fetch() bool {
	var raw map[string]json.RawMessage
	if err := it.core.do(it.ctx, it.req, &raw, it.opts...); err != nil {
		it.err = err
		return false
	}
	it.started = true

	itemsRaw, ok := lookupPath(raw, it.cfg.ItemsField)
	if !ok {
		it.done = true
		return false
	}
	var items []T
	if err := json.Unmarshal(itemsRaw, &items); err != nil {
		it.err = err
		return false
	}
	it.items = items
	it.index = 0
	if len(items) == 0 && it.cfg.Style != "cursor" {
		it.done = true
		return false
	}

	if it.cfg.HasMoreField != "" {
		if moreRaw, ok := lookupPath(raw, it.cfg.HasMoreField); ok {
			var more bool
			if err := json.Unmarshal(moreRaw, &more); err == nil && !more {
				it.done = true
				return true
			}
		}
	}

	switch it.cfg.Style {
	case "cursor":
		nextRaw, ok := lookupPath(raw, it.cfg.NextCursorField)
		if !ok {
			it.done = true
			return true
		}
		var cursor *string
		if err := json.Unmarshal(nextRaw, &cursor); err != nil || cursor == nil || *cursor == "" {
			it.done = true
			return true
		}
		if current, ok := it.req.Query[it.cfg.CursorParam].(string); ok && current == *cursor {
			it.done = true
			return true
		}
		it.req.Query[it.cfg.CursorParam] = *cursor

	default:
		it.done = true
	}
	return true
}

// lookupPath resolves a dot path so pagination can read meta.next_cursor.
func lookupPath(raw map[string]json.RawMessage, path string) (json.RawMessage, bool) {
	if path == "" {
		return nil, false
	}
	parts := strings.Split(path, ".")
	current := raw
	for i, part := range parts {
		value, ok := current[part]
		if !ok {
			return nil, false
		}
		if i == len(parts)-1 {
			return value, true
		}
		var nested map[string]json.RawMessage
		if err := json.Unmarshal(value, &nested); err != nil {
			return nil, false
		}
		current = nested
	}
	return nil, false
}
