// typeship — projects.
// Generated by typeship — https://typeship.dev — do not edit by hand.
package typeship

import (
	"context"
	"fmt"
	"net/url"
)

// ProjectsService accesses the projects endpoints.
type ProjectsService struct {
	core *core
}

// ProjectsListParams are the inputs for ProjectsService.List.
type ProjectsListParams struct {
	Limit  *int64  `json:"-"`
	Cursor *string `json:"-"`
}

// ProjectsCreateParams are the inputs for ProjectsService.Create.
type ProjectsCreateParams struct {
	Name string `json:"name"`
	// SpecURL Spec location for a URL-sourced project. Provide this or source; a project with neither has nothing to generate.
	SpecURL *string `json:"spec_url,omitempty"`
	Source  *Source `json:"source,omitempty"`
	// Platforms Artifacts to build. sdk is implied; cli and mcp require typescript among the languages. Free projects run one platform in total (one SDK language); more is a 402 until the account is on Pro.
	Platforms []Platform `json:"platforms,omitempty"`
	// Languages Languages to generate. Each is a separate package, a separate pull request, a separate hosted generation, and one platform for billing. Defaults to typescript alone.
	Languages []Language `json:"languages,omitempty"`
	// Destinations Per-language pull-request destination, keyed by language.
	Destinations map[string]Destination `json:"destinations,omitempty"`
	// PackageNames Registry name per language; unset derives from the API title.
	PackageNames map[string]string      `json:"package_names,omitempty"`
	Destination  *Nullable[Destination] `json:"destination,omitempty"`
	AutoRegen    *bool                  `json:"auto_regen,omitempty"`
	PackageName  *Nullable[string]      `json:"package_name,omitempty"`
	SpecPatches  []SpecPatch            `json:"spec_patches,omitempty"`
	// MCPEnabled Requires the mcp platform and Enterprise.
	MCPEnabled *bool `json:"mcp_enabled,omitempty"`
	// RelayEnabled Requires the cli platform and Pro.
	RelayEnabled *bool             `json:"relay_enabled,omitempty"`
	Config       *Nullable[Config] `json:"config,omitempty"`
}

// ProjectsUpdateParams are the inputs for ProjectsService.Update.
type ProjectsUpdateParams struct {
	Name    *string `json:"name,omitempty"`
	SpecURL *string `json:"spec_url,omitempty"`
	Source  *Source `json:"source,omitempty"`
	// Platforms Artifacts to build; replaces the list. Dropping cli or mcp turns off the hosted feature it serves. cli and mcp require typescript among the languages. Turning a platform off stops generating it; nothing already delivered is removed.
	Platforms   []Platform             `json:"platforms,omitempty"`
	Destination *Nullable[Destination] `json:"destination,omitempty"`
	// Languages Languages to generate; replaces the list. Each is its own hosted generation and one platform for billing.
	Languages []Language `json:"languages,omitempty"`
	// Destinations Per-language pull-request destination, keyed by language.
	Destinations map[string]Destination `json:"destinations,omitempty"`
	// PackageNames Registry name per language; unset derives from the API title.
	PackageNames map[string]string `json:"package_names,omitempty"`
	AutoRegen    *bool             `json:"auto_regen,omitempty"`
	PackageName  *Nullable[string] `json:"package_name,omitempty"`
	SpecPatches  []SpecPatch       `json:"spec_patches,omitempty"`
	// MCPEnabled Serve this project as a hosted remote MCP endpoint. Requires the mcp platform and Enterprise.
	MCPEnabled *bool `json:"mcp_enabled,omitempty"`
	// RelayEnabled Enable the webhook relay so the generated CLI's webhooks listen command works for this API's users. Requires the cli platform and Pro.
	RelayEnabled *bool `json:"relay_enabled,omitempty"`
	// Config Replaces the whole config. Pass null to clear it.
	Config *Nullable[Config] `json:"config,omitempty"`
}

// ProjectsListGenerationsParams are the inputs for ProjectsService.ListGenerations.
type ProjectsListGenerationsParams struct {
	Limit  *int64  `json:"-"`
	Cursor *string `json:"-"`
	// Language Only generations for this language.
	Language *Language `json:"-"`
}

// ProjectsMCPUsageParams are the inputs for ProjectsService.MCPUsage.
type ProjectsMCPUsageParams struct {
	// Days Window in days, 1 to 90.
	Days *int64 `json:"-"`
}

// List projects.
//
// GET /projects
//
// Returns an iterator that fetches pages lazily:
//
//	it := client.Projects.List(ctx, nil)
//	for it.Next() {
//		item := it.Value()
//	}
//	if err := it.Err(); err != nil { ... }
func (s *ProjectsService) List(ctx context.Context, params *ProjectsListParams, opts ...RequestOption) *Iter[Project] {
	query := map[string]any{}
	if params != nil {
		if params.Limit != nil {
			query["limit"] = *params.Limit
		}
		if params.Cursor != nil {
			query["cursor"] = *params.Cursor
		}
	}
	req := request{
		Method:     "GET",
		Path:       "/projects",
		Query:      query,
		Errors:     map[string]func(int, []byte, string) error{"401": newUnauthorizedError},
		SchemaKey:  "projects.list",
		Idempotent: true,
	}
	return newIter[Project](ctx, s.core, req, opts, pageConfig{
		Style:           "cursor",
		ItemsField:      "data",
		CursorParam:     "cursor",
		NextCursorField: "next_cursor",
		LimitParam:      "limit",
	})
}

// Create a project.
//
// POST /projects
func (s *ProjectsService) Create(ctx context.Context, params ProjectsCreateParams, opts ...RequestOption) (*Project, error) {
	req := request{
		Method:    "POST",
		Path:      "/projects",
		Body:      params,
		Errors:    map[string]func(int, []byte, string) error{"400": newBadRequestError, "401": newUnauthorizedError, "402": newPaymentRequiredError},
		SchemaKey: "projects.create",
	}
	var out Project
	if err := s.core.do(ctx, req, &out, opts...); err != nil {
		return nil, err
	}
	return &out, nil
}

// Get — retrieve a project.
//
// GET /projects/{project_id}
func (s *ProjectsService) Get(ctx context.Context, projectID string, opts ...RequestOption) (*Project, error) {
	req := request{
		Method:     "GET",
		Path:       fmt.Sprintf("/projects/%s", url.PathEscape(projectID)),
		Errors:     map[string]func(int, []byte, string) error{"401": newUnauthorizedError, "404": newNotFoundError},
		SchemaKey:  "projects.get",
		Idempotent: true,
	}
	var out Project
	if err := s.core.do(ctx, req, &out, opts...); err != nil {
		return nil, err
	}
	return &out, nil
}

// Delete a project.
//
// DELETE /projects/{project_id}
func (s *ProjectsService) Delete(ctx context.Context, projectID string, opts ...RequestOption) (*ProjectsDeleteResponse, error) {
	req := request{
		Method:     "DELETE",
		Path:       fmt.Sprintf("/projects/%s", url.PathEscape(projectID)),
		Errors:     map[string]func(int, []byte, string) error{"401": newUnauthorizedError, "404": newNotFoundError},
		SchemaKey:  "projects.delete",
		Idempotent: true,
	}
	var out ProjectsDeleteResponse
	if err := s.core.do(ctx, req, &out, opts...); err != nil {
		return nil, err
	}
	return &out, nil
}

// Update a project.
//
// PATCH /projects/{project_id}
func (s *ProjectsService) Update(ctx context.Context, projectID string, params *ProjectsUpdateParams, opts ...RequestOption) (*Project, error) {
	req := request{
		Method:    "PATCH",
		Path:      fmt.Sprintf("/projects/%s", url.PathEscape(projectID)),
		Body:      params,
		Errors:    map[string]func(int, []byte, string) error{"400": newBadRequestError, "401": newUnauthorizedError, "402": newPaymentRequiredError, "404": newNotFoundError},
		SchemaKey: "projects.update",
	}
	var out Project
	if err := s.core.do(ctx, req, &out, opts...); err != nil {
		return nil, err
	}
	return &out, nil
}

// ListGenerations — list a project's generations.
//
// GET /projects/{project_id}/generations
//
// Returns an iterator that fetches pages lazily:
//
//	it := client.Projects.ListGenerations(ctx, id, nil)
//	for it.Next() {
//		item := it.Value()
//	}
//	if err := it.Err(); err != nil { ... }
func (s *ProjectsService) ListGenerations(ctx context.Context, projectID string, params *ProjectsListGenerationsParams, opts ...RequestOption) *Iter[Generation] {
	query := map[string]any{}
	if params != nil {
		if params.Limit != nil {
			query["limit"] = *params.Limit
		}
		if params.Cursor != nil {
			query["cursor"] = *params.Cursor
		}
		if params.Language != nil {
			query["language"] = *params.Language
		}
	}
	req := request{
		Method:     "GET",
		Path:       fmt.Sprintf("/projects/%s/generations", url.PathEscape(projectID)),
		Query:      query,
		Errors:     map[string]func(int, []byte, string) error{"401": newUnauthorizedError, "404": newNotFoundError},
		SchemaKey:  "projects.listGenerations",
		Idempotent: true,
	}
	return newIter[Generation](ctx, s.core, req, opts, pageConfig{
		Style:           "cursor",
		ItemsField:      "data",
		CursorParam:     "cursor",
		NextCursorField: "next_cursor",
		LimitParam:      "limit",
	})
}

// Generate — run a hosted generation.
//
// Fetches the project's spec URL, generates every configured language,
// and stores each result in the project's history. Each language
// counts as one hosted generation. Does not open pull requests. Only
// URL-sourced projects can be regenerated this way; repository sources
// regenerate on push.
//
// POST /projects/{project_id}/generations
func (s *ProjectsService) Generate(ctx context.Context, projectID string, opts ...RequestOption) (*ProjectsGenerateResponse, error) {
	req := request{
		Method:    "POST",
		Path:      fmt.Sprintf("/projects/%s/generations", url.PathEscape(projectID)),
		Errors:    map[string]func(int, []byte, string) error{"401": newUnauthorizedError, "402": newPaymentRequiredError, "404": newNotFoundError, "422": newUnprocessableEntityError},
		SchemaKey: "projects.generate",
	}
	var out ProjectsGenerateResponse
	if err := s.core.do(ctx, req, &out, opts...); err != nil {
		return nil, err
	}
	return &out, nil
}

// MCPUsage — retrieve hosted MCP endpoint usage for a project.
//
// What the project's hosted MCP endpoint has served over the last `days` (default 30, max 90): tool calls, calls that returned an error, calls turned away by the rate limit, mean upstream latency, and a per-tool breakdown. The same numbers the console shows next to the endpoint URL. Zeroes when the endpoint is off or unused.
//
// GET /projects/{project_id}/mcp_usage
func (s *ProjectsService) MCPUsage(ctx context.Context, projectID string, params *ProjectsMCPUsageParams, opts ...RequestOption) (*MCPUsage, error) {
	query := map[string]any{}
	if params != nil {
		if params.Days != nil {
			query["days"] = *params.Days
		}
	}
	req := request{
		Method:     "GET",
		Path:       fmt.Sprintf("/projects/%s/mcp_usage", url.PathEscape(projectID)),
		Query:      query,
		Errors:     map[string]func(int, []byte, string) error{"400": newBadRequestError, "401": newUnauthorizedError, "404": newNotFoundError},
		SchemaKey:  "projects.mcpUsage",
		Idempotent: true,
	}
	var out MCPUsage
	if err := s.core.do(ctx, req, &out, opts...); err != nil {
		return nil, err
	}
	return &out, nil
}
