// typeship — projects.
// Generated by typeship — https://typeship.dev — do not edit by hand.
package typeship

import (
	"context"
	"fmt"
	"net/url"
)

// ProjectsService accesses the projects endpoints.
type ProjectsService struct {
	core *core
}

// ProjectsListParams are the inputs for ProjectsService.List.
type ProjectsListParams struct {
	// Limit Maximum number of resources to return.
	Limit *int64 `json:"-"`
	// Cursor Opaque cursor from the preceding page's next_cursor.
	Cursor *string `json:"-"`
}

// ProjectsCreateParams are the inputs for ProjectsService.Create.
type ProjectsCreateParams struct {
	// IdempotencyKey Uniquely identifies this creation attempt. Retrying the same request with the same key returns the original response instead of creating another project. Reusing a key with different parameters returns 409.
	IdempotencyKey *string `json:"-"`
}

// ProjectsListGenerationsParams are the inputs for ProjectsService.ListGenerations.
type ProjectsListGenerationsParams struct {
	// Limit Maximum number of resources to return.
	Limit *int64 `json:"-"`
	// Cursor Opaque cursor from the preceding page's next_cursor.
	Cursor *string `json:"-"`
	// Output Only generations for this output.
	Output *OutputID `json:"-"`
}

// List projects.
//
// GET /projects
//
// Returns an iterator that fetches pages lazily:
//
//	it := client.Projects.List(ctx, nil)
//	for it.Next() {
//		item := it.Value()
//	}
//	if err := it.Err(); err != nil { ... }
func (s *ProjectsService) List(ctx context.Context, params *ProjectsListParams, opts ...RequestOption) *Iter[Project] {
	query := map[string]any{}
	if params != nil {
		if params.Limit != nil {
			query["limit"] = *params.Limit
		}
		if params.Cursor != nil {
			query["cursor"] = *params.Cursor
		}
	}
	req := request{
		Method:     "GET",
		Path:       "/projects",
		Query:      query,
		Errors:     map[string]func(int, []byte, string) error{"400": newBadRequestError, "401": newUnauthorizedError, "403": newForbiddenError, "429": newRateLimitedError},
		SchemaKey:  "projects.list",
		Idempotent: true,
	}
	return newIter[Project](ctx, s.core, req, opts, pageConfig{
		Style:           "cursor",
		ItemsField:      "data",
		CursorParam:     "cursor",
		NextCursorField: "next_cursor",
		HasMoreField:    "has_more",
		LimitParam:      "limit",
	})
}

// Create a project.
//
// Stores a URL- or GitHub-sourced project. Free includes one stored project, every selected output, and the first 25 operations, while keeping manual and automatic regeneration, history, destination pull requests, and preview checks. Stateless POST /generate does not consume this slot. Pro adds projects and the whole spec.
//
// POST /projects
func (s *ProjectsService) Create(ctx context.Context, body CreateProjectRequest, params *ProjectsCreateParams, opts ...RequestOption) (*Project, error) {
	headers := map[string]string{}
	if params != nil {
		if params.IdempotencyKey != nil {
			headers["Idempotency-Key"] = fmt.Sprint(*params.IdempotencyKey)
		}
	}
	req := request{
		Method:            "POST",
		Path:              "/projects",
		Headers:           headers,
		Body:              body,
		Errors:            map[string]func(int, []byte, string) error{"400": newBadRequestError, "401": newUnauthorizedError, "402": newPaymentRequiredError, "403": newForbiddenError, "409": newConflictError, "429": newRateLimitedError, "500": newInternalServerError},
		SchemaKey:         "projects.create",
		IdempotencyHeader: "Idempotency-Key",
	}
	var out Project
	if err := s.core.do(ctx, req, &out, opts...); err != nil {
		return nil, err
	}
	return &out, nil
}

// Retrieve a project.
//
// GET /projects/{project_id}
func (s *ProjectsService) Retrieve(ctx context.Context, projectID string, opts ...RequestOption) (*Project, error) {
	req := request{
		Method:     "GET",
		Path:       fmt.Sprintf("/projects/%s", url.PathEscape(projectID)),
		Errors:     map[string]func(int, []byte, string) error{"401": newUnauthorizedError, "403": newForbiddenError, "404": newNotFoundError, "429": newRateLimitedError},
		SchemaKey:  "projects.retrieve",
		Idempotent: true,
	}
	var out Project
	if err := s.core.do(ctx, req, &out, opts...); err != nil {
		return nil, err
	}
	return &out, nil
}

// Delete a project.
//
// DELETE /projects/{project_id}
func (s *ProjectsService) Delete(ctx context.Context, projectID string, opts ...RequestOption) (*DeletedProject, error) {
	req := request{
		Method:     "DELETE",
		Path:       fmt.Sprintf("/projects/%s", url.PathEscape(projectID)),
		Errors:     map[string]func(int, []byte, string) error{"401": newUnauthorizedError, "403": newForbiddenError, "404": newNotFoundError, "429": newRateLimitedError},
		SchemaKey:  "projects.delete",
		Idempotent: true,
	}
	var out DeletedProject
	if err := s.core.do(ctx, req, &out, opts...); err != nil {
		return nil, err
	}
	return &out, nil
}

// Update a project.
//
// PATCH /projects/{project_id}
func (s *ProjectsService) Update(ctx context.Context, projectID string, body UpdateProjectRequest, opts ...RequestOption) (*Project, error) {
	req := request{
		Method:    "PATCH",
		Path:      fmt.Sprintf("/projects/%s", url.PathEscape(projectID)),
		Body:      body,
		Errors:    map[string]func(int, []byte, string) error{"400": newBadRequestError, "401": newUnauthorizedError, "402": newPaymentRequiredError, "403": newForbiddenError, "404": newNotFoundError, "429": newRateLimitedError},
		SchemaKey: "projects.update",
	}
	var out Project
	if err := s.core.do(ctx, req, &out, opts...); err != nil {
		return nil, err
	}
	return &out, nil
}

// RetrieveGithubHealth — diagnose a project's GitHub integration.
//
// Returns machine-actionable source and destination access, spec readability, optional label setup, required status names, and the latest durable webhook delivery. The console renders this same result.
//
// GET /projects/{project_id}/github
func (s *ProjectsService) RetrieveGithubHealth(ctx context.Context, projectID string, opts ...RequestOption) (*GithubIntegrationHealth, error) {
	req := request{
		Method:     "GET",
		Path:       fmt.Sprintf("/projects/%s/github", url.PathEscape(projectID)),
		Errors:     map[string]func(int, []byte, string) error{"401": newUnauthorizedError, "403": newForbiddenError, "404": newNotFoundError, "429": newRateLimitedError},
		SchemaKey:  "projects.retrieveGithubHealth",
		Idempotent: true,
	}
	var out GithubIntegrationHealth
	if err := s.core.do(ctx, req, &out, opts...); err != nil {
		return nil, err
	}
	return &out, nil
}

// ListGenerations — list a project's generations.
//
// GET /projects/{project_id}/generations
//
// Returns an iterator that fetches pages lazily:
//
//	it := client.Projects.ListGenerations(ctx, id, nil)
//	for it.Next() {
//		item := it.Value()
//	}
//	if err := it.Err(); err != nil { ... }
func (s *ProjectsService) ListGenerations(ctx context.Context, projectID string, params *ProjectsListGenerationsParams, opts ...RequestOption) *Iter[Generation] {
	query := map[string]any{}
	if params != nil {
		if params.Limit != nil {
			query["limit"] = *params.Limit
		}
		if params.Cursor != nil {
			query["cursor"] = *params.Cursor
		}
		if params.Output != nil {
			query["output"] = *params.Output
		}
	}
	req := request{
		Method:     "GET",
		Path:       fmt.Sprintf("/projects/%s/generations", url.PathEscape(projectID)),
		Query:      query,
		Errors:     map[string]func(int, []byte, string) error{"400": newBadRequestError, "401": newUnauthorizedError, "403": newForbiddenError, "404": newNotFoundError, "429": newRateLimitedError},
		SchemaKey:  "projects.listGenerations",
		Idempotent: true,
	}
	return newIter[Generation](ctx, s.core, req, opts, pageConfig{
		Style:           "cursor",
		ItemsField:      "data",
		CursorParam:     "cursor",
		NextCursorField: "next_cursor",
		HasMoreField:    "has_more",
		LimitParam:      "limit",
	})
}

// Generate outputs and open pull requests.
//
// Resolves the project's URL or GitHub source, generates every
// configured delivery package, stores each result in the project's history,
// and attempts to open a pull request in every configured destination.
// When the complete generated tree already matches a destination, no
// commit, branch, or pull request is created and that generation reports
// `pr_status: no_changes`. This is the same pipeline automatic
// regeneration runs after a source change.
//
// POST /projects/{project_id}/generations
func (s *ProjectsService) Generate(ctx context.Context, projectID string, opts ...RequestOption) (*GenerationBatch, error) {
	req := request{
		Method:    "POST",
		Path:      fmt.Sprintf("/projects/%s/generations", url.PathEscape(projectID)),
		Errors:    map[string]func(int, []byte, string) error{"401": newUnauthorizedError, "402": newPaymentRequiredError, "403": newForbiddenError, "404": newNotFoundError, "422": newUnprocessableEntityError, "429": newRateLimitedError, "500": newInternalServerError},
		SchemaKey: "projects.generate",
	}
	var out GenerationBatch
	if err := s.core.do(ctx, req, &out, opts...); err != nil {
		return nil, err
	}
	return &out, nil
}
