// typeship — projects.
// Generated by typeship — https://typeship.dev
package typeship

import (
	"context"
	"fmt"
	"net/url"
)

// ProjectsService accesses the projects endpoints.
type ProjectsService struct {
	core *core
}

// ProjectsCreateParams are the inputs for ProjectsService.Create.
type ProjectsCreateParams struct {
	// IdempotencyKey Identifies one logical write for 24 hours. The key is scoped to the authenticated organization and operation; generation without an organization uses a hashed network identity. Retrying the same method, path, query, If-Match header, and JSON body replays the original response. Reusing the key with changed intent returns 409. After expiry the key starts a new write.
	IdempotencyKey *string `json:"-"`
}

// ProjectsListParams are the inputs for ProjectsService.List.
type ProjectsListParams struct {
	// Limit Maximum number of resources to return. Omit for 20; otherwise supply base-10 digits representing an integer from 1 to 100. Empty, malformed, or out-of-range values return 400 input_invalid. List query parameters must appear only once; repeated or unrecognized parameters return 400 query_param_invalid.
	Limit *int64 `json:"-"`
	// Cursor Opaque cursor from the preceding page's next_cursor. Valid only for the same organization, operation, filters, and ordering that issued it. Omit to start at the first page. Empty or malformed cursors, and cursors issued for different filters, return 400 cursor_invalid; start again from the first page. Repeated cursors return 400 query_param_invalid. The page limit may change between requests.
	Cursor *string `json:"-"`
}

// ProjectsUpdateParams are the inputs for ProjectsService.Update.
type ProjectsUpdateParams struct {
	// IfMatch ETag from a preceding response. The write applies only if the resource still has that version; otherwise it returns 412 precondition_failed without changes. Omit to write the current version. See https://typeship.dev/docs/typeship-api#conditional-writes.
	IfMatch *string `json:"-"`
}

// ProjectsDeleteParams are the inputs for ProjectsService.Delete.
type ProjectsDeleteParams struct {
	// IfMatch ETag from a preceding response. The write applies only if the resource still has that version; otherwise it returns 412 precondition_failed without changes. Omit to write the current version. See https://typeship.dev/docs/typeship-api#conditional-writes.
	IfMatch *string `json:"-"`
}

// ProjectsGenerateParams are the inputs for ProjectsService.Generate.
type ProjectsGenerateParams struct {
	// IdempotencyKey Identifies one logical write for 24 hours. The key is scoped to the authenticated organization and operation; generation without an organization uses a hashed network identity. Retrying the same method, path, query, If-Match header, and JSON body replays the original response. Reusing the key with changed intent returns 409. After expiry the key starts a new write.
	IdempotencyKey *string `json:"-"`
}

// Create a Project.
//
// Creates a Project from a URL or GitHub Spec.
// Automatic generation is enabled by default for a saved Project.
//
// Free includes one saved Project, all selected Targets, and the first 25 operations per Target, with regeneration, history, delivery pull requests, and previews. Pro supports additional Projects and all operations. One-shot generation does not use a Project slot.
//
// POST /projects
func (s *ProjectsService) Create(ctx context.Context, body CreateProjectRequest, params *ProjectsCreateParams, opts ...RequestOption) (*ProjectResponse, error) {
	headers := map[string]string{}
	if params != nil {
		if params.IdempotencyKey != nil {
			headers["Idempotency-Key"] = fmt.Sprint(*params.IdempotencyKey)
		}
	}
	req := request{
		Method:            "POST",
		Path:              "/projects",
		Headers:           headers,
		Body:              body,
		Errors:            map[string]func(int, []byte, string) error{"400": newBadRequestError, "401": newUnauthorizedError, "402": newPaymentRequiredError, "403": newForbiddenError, "409": newConflictError, "422": newUnprocessableEntityError, "429": newRateLimitedError, "500": newInternalServerError},
		Security:          []map[string][]string{{"apiKey": {}}},
		SchemaKey:         "projects.create",
		IdempotencyHeader: "Idempotency-Key",
	}
	var out ProjectResponse
	if err := s.core.do(ctx, req, &out, opts...); err != nil {
		return nil, err
	}
	return &out, nil
}

// List Projects.
//
// GET /projects
//
// Returns an iterator that fetches pages lazily:
//
//	it := client.Projects.List(ctx, nil)
//	for it.Next() {
//		item := it.Value()
//	}
//	if err := it.Err(); err != nil { ... }
func (s *ProjectsService) List(ctx context.Context, params *ProjectsListParams, opts ...RequestOption) *Iter[Project] {
	query := map[string]any{}
	if params != nil {
		if params.Limit != nil {
			query["limit"] = *params.Limit
		}
		if params.Cursor != nil {
			query["cursor"] = *params.Cursor
		}
	}
	req := request{
		Method:     "GET",
		Path:       "/projects",
		Query:      query,
		Errors:     map[string]func(int, []byte, string) error{"400": newBadRequestError, "401": newUnauthorizedError, "403": newForbiddenError, "429": newRateLimitedError, "500": newInternalServerError},
		Security:   []map[string][]string{{"apiKey": {}}},
		SchemaKey:  "projects.list",
		Idempotent: true,
	}
	return newIter[Project](ctx, s.core, req, opts, pageConfig{
		Style:           "cursor",
		ItemsField:      "data",
		CursorParam:     "cursor",
		NextCursorField: "next_cursor",
		HasMoreField:    "has_more",
		LimitParam:      "limit",
	})
}

// Get a Project.
//
// Returns the Project's settings and Spec ID. List its Targets separately to retrieve Target configuration and Deliveries.
//
// GET /projects/{project_id}
func (s *ProjectsService) Get(ctx context.Context, projectID string, opts ...RequestOption) (*ProjectResponse, error) {
	req := request{
		Method:     "GET",
		Path:       fmt.Sprintf("/projects/%s", url.PathEscape(projectID)),
		Errors:     map[string]func(int, []byte, string) error{"401": newUnauthorizedError, "403": newForbiddenError, "404": newNotFoundError, "429": newRateLimitedError, "500": newInternalServerError},
		Security:   []map[string][]string{{"apiKey": {}}},
		SchemaKey:  "projects.get",
		Idempotent: true,
	}
	var out ProjectResponse
	if err := s.core.do(ctx, req, &out, opts...); err != nil {
		return nil, err
	}
	return &out, nil
}

// Update a Project.
//
// Omitted fields keep their current values. A supplied config replaces the entire stored object; null or an empty object clears it.
// With auto_generate enabled, changing shared config queues a Generation for each Target whose effective config changes. A queued or running Target reuses that Generation.
// Omitting If-Match applies the update to the current resource; with If-Match, a stale ETag returns 412 precondition_failed without saving.
//
// A `409 target_busy` means a Target is publishing. Retrieve the Project, wait for publishing to finish, reconcile your update, and retry.
// A `502 follow_up_failed` means the Project was saved, but an obsolete Draft pull request could not be retired. Retrieve the Project and retry the same update to finish retiring reviews if that update is still desired.
// See [conditional writes](https://typeship.dev/docs/typeship-api#conditional-writes) for ETag and If-Match.
//
// PATCH /projects/{project_id}
func (s *ProjectsService) Update(ctx context.Context, projectID string, body UpdateProjectRequest, params *ProjectsUpdateParams, opts ...RequestOption) (*ProjectResponse, error) {
	headers := map[string]string{}
	if params != nil {
		if params.IfMatch != nil {
			headers["If-Match"] = fmt.Sprint(*params.IfMatch)
		}
	}
	req := request{
		Method:    "PATCH",
		Path:      fmt.Sprintf("/projects/%s", url.PathEscape(projectID)),
		Headers:   headers,
		Body:      body,
		Errors:    map[string]func(int, []byte, string) error{"400": newBadRequestError, "401": newUnauthorizedError, "402": newPaymentRequiredError, "403": newForbiddenError, "404": newNotFoundError, "409": newConflictError, "412": newPreconditionFailedError, "422": newUnprocessableEntityError, "429": newRateLimitedError, "500": newInternalServerError, "502": newBadGatewayError},
		Security:  []map[string][]string{{"apiKey": {}}},
		SchemaKey: "projects.update",
	}
	var out ProjectResponse
	if err := s.core.do(ctx, req, &out, opts...); err != nil {
		return nil, err
	}
	return &out, nil
}

// Delete a Project.
//
// A `502 repository_unavailable` means the Project was not deleted because its Draft pull requests could not be retired. Retry deletion to finish retiring the remaining reviews. Repeating a completed deletion returns `404`.
// See [conditional writes](https://typeship.dev/docs/typeship-api#conditional-writes) for ETag and If-Match.
//
// DELETE /projects/{project_id}
func (s *ProjectsService) Delete(ctx context.Context, projectID string, params *ProjectsDeleteParams, opts ...RequestOption) (*DeletedProject, error) {
	headers := map[string]string{}
	if params != nil {
		if params.IfMatch != nil {
			headers["If-Match"] = fmt.Sprint(*params.IfMatch)
		}
	}
	req := request{
		Method:     "DELETE",
		Path:       fmt.Sprintf("/projects/%s", url.PathEscape(projectID)),
		Headers:    headers,
		Errors:     map[string]func(int, []byte, string) error{"400": newBadRequestError, "401": newUnauthorizedError, "403": newForbiddenError, "404": newNotFoundError, "412": newPreconditionFailedError, "429": newRateLimitedError, "500": newInternalServerError, "502": newBadGatewayError},
		Security:   []map[string][]string{{"apiKey": {}}},
		SchemaKey:  "projects.delete",
		Idempotent: true,
	}
	var out DeletedProject
	if err := s.core.do(ctx, req, &out, opts...); err != nil {
		return nil, err
	}
	return &out, nil
}

// Generate a Project's Targets.
//
// Queues one Generation per active Target and returns their IDs. Retrieve each Generation until its status moves from `queued` to `running` and then `completed` or `failed`. `completed` means generated files are saved; check Delivery and Draft status separately for repository delivery and pull requests. A Target already queued or running is returned without starting another Generation. A `409 targets_inactive` means the Project has no active Target to generate. A matching Idempotency-Key replay returns the same Generations with their current statuses.
//
// If the package already matches a destination and no Draft is open, delivery creates no commit, branch, or pull request. An existing Draft stays open. Automatic generation uses the same workflow.
//
// POST /projects/{project_id}/generate
func (s *ProjectsService) Generate(ctx context.Context, projectID string, body GenerateProjectRequest, params *ProjectsGenerateParams, opts ...RequestOption) (*GenerationBatch, error) {
	headers := map[string]string{}
	if params != nil {
		if params.IdempotencyKey != nil {
			headers["Idempotency-Key"] = fmt.Sprint(*params.IdempotencyKey)
		}
	}
	req := request{
		Method:            "POST",
		Path:              fmt.Sprintf("/projects/%s/generate", url.PathEscape(projectID)),
		Headers:           headers,
		Body:              body,
		Errors:            map[string]func(int, []byte, string) error{"400": newBadRequestError, "401": newUnauthorizedError, "402": newPaymentRequiredError, "403": newForbiddenError, "404": newNotFoundError, "409": newConflictError, "413": newPayloadTooLargeError, "422": newUnprocessableEntityError, "429": newRateLimitedError, "500": newInternalServerError, "502": newBadGatewayError},
		Security:          []map[string][]string{{"apiKey": {}}},
		SchemaKey:         "projects.generate",
		IdempotencyHeader: "Idempotency-Key",
	}
	var out GenerationBatch
	if err := s.core.do(ctx, req, &out, opts...); err != nil {
		return nil, err
	}
	return &out, nil
}
