// typeship — publications.
// Generated by typeship — https://typeship.dev
package typeship

import (
	"context"
	"fmt"
	"net/url"
)

// PublicationsService accesses the publications endpoints.
type PublicationsService struct {
	core *core
}

// PublicationsListParams are the inputs for PublicationsService.List.
type PublicationsListParams struct {
	// Limit Maximum number of resources to return. Omit for 20; otherwise supply base-10 digits representing an integer from 1 to 100. Empty, malformed, or out-of-range values return 400 input_invalid. List query parameters must appear only once; repeated or unrecognized parameters return 400 query_param_invalid.
	Limit *int64 `json:"-"`
	// Cursor Opaque cursor from the preceding page's next_cursor. Valid only for the same organization, operation, filters, and ordering that issued it. Omit to start at the first page. Empty or malformed cursors, and cursors issued for different filters, return 400 cursor_invalid; start again from the first page. Repeated cursors return 400 query_param_invalid. The page limit may change between requests.
	Cursor *string `json:"-"`
	// ReleaseID Only publications of this release.
	ReleaseID *ReleaseID `json:"-"`
}

// List publications.
//
// GET /publications
//
// Returns an iterator that fetches pages lazily:
//
//	it := client.Publications.List(ctx, nil)
//	for it.Next() {
//		item := it.Value()
//	}
//	if err := it.Err(); err != nil { ... }
func (s *PublicationsService) List(ctx context.Context, params *PublicationsListParams, opts ...RequestOption) *Iter[Publication] {
	query := map[string]any{}
	if params != nil {
		if params.Limit != nil {
			query["limit"] = *params.Limit
		}
		if params.Cursor != nil {
			query["cursor"] = *params.Cursor
		}
		if params.ReleaseID != nil {
			query["release_id"] = *params.ReleaseID
		}
	}
	req := request{
		Method:     "GET",
		Path:       "/publications",
		Query:      query,
		Errors:     map[string]func(int, []byte, string) error{"400": newBadRequestError, "401": newUnauthorizedError, "403": newForbiddenError, "404": newNotFoundError, "429": newRateLimitedError, "500": newInternalServerError},
		Security:   []map[string][]string{{"apiKey": {}}},
		SchemaKey:  "publications.list",
		Idempotent: true,
	}
	return newIter[Publication](ctx, s.core, req, opts, pageConfig{
		Style:           "cursor",
		ItemsField:      "data",
		CursorParam:     "cursor",
		NextCursorField: "next_cursor",
		HasMoreField:    "has_more",
		LimitParam:      "limit",
	})
}

// Get publishing status.
//
// Returns the registry publishing status for a release. A status in another organization returns 404 resource_not_found.
//
// GET /publications/{publication_id}
func (s *PublicationsService) Get(ctx context.Context, publicationID string, opts ...RequestOption) (*PublicationResponse, error) {
	req := request{
		Method:     "GET",
		Path:       fmt.Sprintf("/publications/%s", url.PathEscape(publicationID)),
		Errors:     map[string]func(int, []byte, string) error{"401": newUnauthorizedError, "403": newForbiddenError, "404": newNotFoundError, "429": newRateLimitedError, "500": newInternalServerError},
		Security:   []map[string][]string{{"apiKey": {}}},
		SchemaKey:  "publications.get",
		Idempotent: true,
	}
	var out PublicationResponse
	if err := s.core.do(ctx, req, &out, opts...); err != nil {
		return nil, err
	}
	return &out, nil
}
