// typeship — releases.
// Generated by typeship — https://typeship.dev
package typeship

import (
	"context"
	"fmt"
	"net/url"
)

// ReleasesService accesses the releases endpoints.
type ReleasesService struct {
	core *core
}

// ReleasesListParams are the inputs for ReleasesService.List.
type ReleasesListParams struct {
	// Limit Maximum number of resources to return. Omit for 20; otherwise supply base-10 digits representing an integer from 1 to 100. Empty, malformed, or out-of-range values return 400 input_invalid. List query parameters must appear only once; repeated or unrecognized parameters return 400 query_param_invalid.
	Limit *int64 `json:"-"`
	// Cursor Opaque cursor from the preceding page's next_cursor. Valid only for the same organization, operation, filters, and ordering that issued it. Omit to start at the first page. Empty or malformed cursors, and cursors issued for different filters, return 400 cursor_invalid; start again from the first page. Repeated cursors return 400 query_param_invalid. The page limit may change between requests.
	Cursor *string `json:"-"`
	// TargetID Only releases of this Target.
	TargetID *TargetID `json:"-"`
}

// ReleasesRetryParams are the inputs for ReleasesService.Retry.
type ReleasesRetryParams struct {
	// IdempotencyKey Identifies one logical write for 24 hours. The key is scoped to the authenticated organization and operation; generation without an organization uses a hashed network identity. Retrying the same method, path, query, If-Match header, and JSON body replays the original response. Reusing the key with changed intent returns 409. After expiry the key starts a new write.
	IdempotencyKey *string `json:"-"`
}

// List releases.
//
// GET /releases
//
// Returns an iterator that fetches pages lazily:
//
//	it := client.Releases.List(ctx, nil)
//	for it.Next() {
//		item := it.Value()
//	}
//	if err := it.Err(); err != nil { ... }
func (s *ReleasesService) List(ctx context.Context, params *ReleasesListParams, opts ...RequestOption) *Iter[Release] {
	query := map[string]any{}
	if params != nil {
		if params.Limit != nil {
			query["limit"] = *params.Limit
		}
		if params.Cursor != nil {
			query["cursor"] = *params.Cursor
		}
		if params.TargetID != nil {
			query["target_id"] = *params.TargetID
		}
	}
	req := request{
		Method:     "GET",
		Path:       "/releases",
		Query:      query,
		Errors:     map[string]func(int, []byte, string) error{"400": newBadRequestError, "401": newUnauthorizedError, "403": newForbiddenError, "404": newNotFoundError, "429": newRateLimitedError, "500": newInternalServerError},
		Security:   []map[string][]string{{"apiKey": {}}},
		SchemaKey:  "releases.list",
		Idempotent: true,
	}
	return newIter[Release](ctx, s.core, req, opts, pageConfig{
		Style:           "cursor",
		ItemsField:      "data",
		CursorParam:     "cursor",
		NextCursorField: "next_cursor",
		HasMoreField:    "has_more",
		LimitParam:      "limit",
	})
}

// Get a release.
//
// GET /releases/{release_id}
func (s *ReleasesService) Get(ctx context.Context, releaseID string, opts ...RequestOption) (*ReleaseResponse, error) {
	req := request{
		Method:     "GET",
		Path:       fmt.Sprintf("/releases/%s", url.PathEscape(releaseID)),
		Errors:     map[string]func(int, []byte, string) error{"401": newUnauthorizedError, "403": newForbiddenError, "404": newNotFoundError, "429": newRateLimitedError, "500": newInternalServerError},
		Security:   []map[string][]string{{"apiKey": {}}},
		SchemaKey:  "releases.get",
		Idempotent: true,
	}
	var out ReleaseResponse
	if err := s.core.do(ctx, req, &out, opts...); err != nil {
		return nil, err
	}
	return &out, nil
}

// Retry publishing a release.
//
// Queues every failed or queued Publication of the release and starts its repository publishing workflow again. Publishing uses that release's version and accepted commit, even if a newer Draft or release exists. Completed Publications are not repeated.
//
// Returns `202` with the Release. Get the Release until each Publication reaches `completed` or `failed`.
//
// A `409 publication_not_retryable` means no Publication is queued or failed. A `502 repository_unavailable` means the repository publishing workflow could not be dispatched, and nothing was changed.
//
// POST /releases/{release_id}/retry
func (s *ReleasesService) Retry(ctx context.Context, releaseID string, params *ReleasesRetryParams, opts ...RequestOption) (*ReleaseResponse, error) {
	headers := map[string]string{}
	if params != nil {
		if params.IdempotencyKey != nil {
			headers["Idempotency-Key"] = fmt.Sprint(*params.IdempotencyKey)
		}
	}
	req := request{
		Method:            "POST",
		Path:              fmt.Sprintf("/releases/%s/retry", url.PathEscape(releaseID)),
		Headers:           headers,
		Errors:            map[string]func(int, []byte, string) error{"400": newBadRequestError, "401": newUnauthorizedError, "403": newForbiddenError, "404": newNotFoundError, "409": newConflictError, "429": newRateLimitedError, "500": newInternalServerError, "502": newBadGatewayError},
		Security:          []map[string][]string{{"apiKey": {}}},
		SchemaKey:         "releases.retry",
		IdempotencyHeader: "Idempotency-Key",
	}
	var out ReleaseResponse
	if err := s.core.do(ctx, req, &out, opts...); err != nil {
		return nil, err
	}
	return &out, nil
}
