// typeship — specVersions.
// Generated by typeship — https://typeship.dev — do not edit by hand.
package typeship

import (
	"context"
	"fmt"
	"net/url"
)

// SpecVersionsService accesses the specVersions endpoints.
type SpecVersionsService struct {
	core *core
}

// SpecVersionsListParams are the inputs for SpecVersionsService.List.
type SpecVersionsListParams struct {
	// Limit Maximum number of resources to return.
	Limit *int64 `json:"-"`
	// Cursor Opaque cursor from the preceding page's next_cursor.
	Cursor *string `json:"-"`
}

// List the specs this project has generated from.
//
// The audit trail behind a regeneration: which spec produced which SDK, and when it changed. Content is omitted from the list because specs run to megabytes.
//
// GET /projects/{project_id}/spec_versions
//
// Returns an iterator that fetches pages lazily:
//
//	it := client.SpecVersions.List(ctx, id, nil)
//	for it.Next() {
//		item := it.Value()
//	}
//	if err := it.Err(); err != nil { ... }
func (s *SpecVersionsService) List(ctx context.Context, projectID string, params *SpecVersionsListParams, opts ...RequestOption) *Iter[SpecVersion] {
	query := map[string]any{}
	if params != nil {
		if params.Limit != nil {
			query["limit"] = *params.Limit
		}
		if params.Cursor != nil {
			query["cursor"] = *params.Cursor
		}
	}
	req := request{
		Method:     "GET",
		Path:       fmt.Sprintf("/projects/%s/spec_versions", url.PathEscape(projectID)),
		Query:      query,
		Errors:     map[string]func(int, []byte, string) error{"400": newBadRequestError, "401": newUnauthorizedError, "403": newForbiddenError, "404": newNotFoundError, "429": newRateLimitedError},
		SchemaKey:  "specVersions.list",
		Idempotent: true,
	}
	return newIter[SpecVersion](ctx, s.core, req, opts, pageConfig{
		Style:           "cursor",
		ItemsField:      "data",
		CursorParam:     "cursor",
		NextCursorField: "next_cursor",
		HasMoreField:    "has_more",
		LimitParam:      "limit",
	})
}

// Retrieve a spec version.
//
// One recorded spec, with its content. Storing every spec a project has generated from is only an audit trail if you can read one back and diff it against what shipped.
//
// GET /spec_versions/{spec_version_id}
func (s *SpecVersionsService) Retrieve(ctx context.Context, specVersionID string, opts ...RequestOption) (*SpecVersion, error) {
	req := request{
		Method:     "GET",
		Path:       fmt.Sprintf("/spec_versions/%s", url.PathEscape(specVersionID)),
		Errors:     map[string]func(int, []byte, string) error{"401": newUnauthorizedError, "403": newForbiddenError, "404": newNotFoundError, "429": newRateLimitedError},
		SchemaKey:  "specVersions.retrieve",
		Idempotent: true,
	}
	var out SpecVersion
	if err := s.core.do(ctx, req, &out, opts...); err != nil {
		return nil, err
	}
	return &out, nil
}

// RetrieveContent — retrieve a spec version's raw text.
//
// The escape hatch for specs too large to inline, and the endpoint to pipe straight into a diff.
//
// GET /spec_versions/{spec_version_id}/content
func (s *SpecVersionsService) RetrieveContent(ctx context.Context, specVersionID string, opts ...RequestOption) (string, error) {
	req := request{
		Method:     "GET",
		Path:       fmt.Sprintf("/spec_versions/%s/content", url.PathEscape(specVersionID)),
		Errors:     map[string]func(int, []byte, string) error{"401": newUnauthorizedError, "403": newForbiddenError, "404": newNotFoundError, "429": newRateLimitedError},
		SchemaKey:  "specVersions.retrieveContent",
		Idempotent: true,
	}
	var out string
	if err := s.core.do(ctx, req, &out, opts...); err != nil {
		return "", err
	}
	return out, nil
}
