// typeship — specRevisions.
// Generated by typeship — https://typeship.dev
package typeship

import (
	"context"
	"fmt"
	"net/url"
)

// SpecRevisionsService accesses the specRevisions endpoints.
type SpecRevisionsService struct {
	core *core
}

// SpecRevisionsListParams are the inputs for SpecRevisionsService.List.
type SpecRevisionsListParams struct {
	// Limit Maximum number of resources to return. Omit for 20; otherwise supply base-10 digits representing an integer from 1 to 100. Empty, malformed, or out-of-range values return 400 input_invalid. List query parameters must appear only once; repeated or unrecognized parameters return 400 query_param_invalid.
	Limit *int64 `json:"-"`
	// Cursor Opaque cursor from the preceding page's next_cursor. Valid only for the same organization, operation, filters, and ordering that issued it. Omit to start at the first page. Empty or malformed cursors, and cursors issued for different filters, return 400 cursor_invalid; start again from the first page. Repeated cursors return 400 query_param_invalid. The page limit may change between requests.
	Cursor *string `json:"-"`
	// SpecID Only revisions of this Spec.
	SpecID *SpecID `json:"-"`
}

// SpecRevisionsGetParams are the inputs for SpecRevisionsService.Get.
type SpecRevisionsGetParams struct {
	// Include Add related data to the response. `diagnostics` adds the `diagnostics` and `patch_diagnostics` arrays.
	Include *string `json:"-"`
}

// SpecRevisionsListFilesParams are the inputs for SpecRevisionsService.ListFiles.
type SpecRevisionsListFilesParams struct {
	// Limit Maximum number of resources to return. Omit for 20; otherwise supply base-10 digits representing an integer from 1 to 100. Empty, malformed, or out-of-range values return 400 input_invalid. List query parameters must appear only once; repeated or unrecognized parameters return 400 query_param_invalid.
	Limit *int64 `json:"-"`
	// Cursor Opaque cursor from the preceding page's next_cursor. Valid only for the same organization, operation, filters, and ordering that issued it. Omit to start at the first page. Empty or malformed cursors, and cursors issued for different filters, return 400 cursor_invalid; start again from the first page. Repeated cursors return 400 query_param_invalid. The page limit may change between requests.
	Cursor *string `json:"-"`
}

// List Spec Revisions.
//
// Lists Spec Revisions, newest first. Source content is not included; list a revision's files with listSpecRevisionFiles.
//
// GET /spec-revisions
//
// Returns an iterator that fetches pages lazily:
//
//	it := client.SpecRevisions.List(ctx, nil)
//	for it.Next() {
//		item := it.Value()
//	}
//	if err := it.Err(); err != nil { ... }
func (s *SpecRevisionsService) List(ctx context.Context, params *SpecRevisionsListParams, opts ...RequestOption) *Iter[SpecRevision] {
	query := map[string]any{}
	if params != nil {
		if params.Limit != nil {
			query["limit"] = *params.Limit
		}
		if params.Cursor != nil {
			query["cursor"] = *params.Cursor
		}
		if params.SpecID != nil {
			query["spec_id"] = *params.SpecID
		}
	}
	req := request{
		Method:     "GET",
		Path:       "/spec-revisions",
		Query:      query,
		Errors:     map[string]func(int, []byte, string) error{"400": newBadRequestError, "401": newUnauthorizedError, "403": newForbiddenError, "404": newNotFoundError, "429": newRateLimitedError, "500": newInternalServerError},
		Security:   []map[string][]string{{"apiKey": {}}},
		SchemaKey:  "specRevisions.list",
		Idempotent: true,
	}
	return newIter[SpecRevision](ctx, s.core, req, opts, pageConfig{
		Style:           "cursor",
		ItemsField:      "data",
		CursorParam:     "cursor",
		NextCursorField: "next_cursor",
		HasMoreField:    "has_more",
		LimitParam:      "limit",
	})
}

// Get a Spec Revision.
//
// Returns metadata for a saved Spec Revision with a Diagnostics summary. Pass `include=diagnostics` to add every Diagnostic, evaluated with the Spec's current patches and Diagnostic policy. List its source files and resolved document with listSpecRevisionFiles.
//
// GET /spec-revisions/{spec_revision_id}
func (s *SpecRevisionsService) Get(ctx context.Context, specRevisionID string, params *SpecRevisionsGetParams, opts ...RequestOption) (*SpecRevisionResponse, error) {
	query := map[string]any{}
	if params != nil {
		if params.Include != nil {
			query["include"] = *params.Include
		}
	}
	req := request{
		Method:     "GET",
		Path:       fmt.Sprintf("/spec-revisions/%s", url.PathEscape(specRevisionID)),
		Query:      query,
		Errors:     map[string]func(int, []byte, string) error{"400": newBadRequestError, "401": newUnauthorizedError, "403": newForbiddenError, "404": newNotFoundError, "429": newRateLimitedError, "500": newInternalServerError},
		Security:   []map[string][]string{{"apiKey": {}}},
		SchemaKey:  "specRevisions.get",
		Idempotent: true,
	}
	var out SpecRevisionResponse
	if err := s.core.do(ctx, req, &out, opts...); err != nil {
		return nil, err
	}
	return &out, nil
}

// ListFiles — list a Spec Revision's files.
//
// Lists the captured source files and the resolved document Typeship generated from, ordered by path. Read content with getFile.
//
// GET /spec-revisions/{spec_revision_id}/files
//
// Returns an iterator that fetches pages lazily:
//
//	it := client.SpecRevisions.ListFiles(ctx, id, nil)
//	for it.Next() {
//		item := it.Value()
//	}
//	if err := it.Err(); err != nil { ... }
func (s *SpecRevisionsService) ListFiles(ctx context.Context, specRevisionID string, params *SpecRevisionsListFilesParams, opts ...RequestOption) *Iter[SpecRevisionFile] {
	query := map[string]any{}
	if params != nil {
		if params.Limit != nil {
			query["limit"] = *params.Limit
		}
		if params.Cursor != nil {
			query["cursor"] = *params.Cursor
		}
	}
	req := request{
		Method:     "GET",
		Path:       fmt.Sprintf("/spec-revisions/%s/files", url.PathEscape(specRevisionID)),
		Query:      query,
		Errors:     map[string]func(int, []byte, string) error{"400": newBadRequestError, "401": newUnauthorizedError, "403": newForbiddenError, "404": newNotFoundError, "429": newRateLimitedError, "500": newInternalServerError},
		Security:   []map[string][]string{{"apiKey": {}}},
		SchemaKey:  "specRevisions.listFiles",
		Idempotent: true,
	}
	return newIter[SpecRevisionFile](ctx, s.core, req, opts, pageConfig{
		Style:           "cursor",
		ItemsField:      "data",
		CursorParam:     "cursor",
		NextCursorField: "next_cursor",
		HasMoreField:    "has_more",
		LimitParam:      "limit",
	})
}
