// typeship — specs.
// Generated by typeship — https://typeship.dev
package typeship

import (
	"context"
	"fmt"
	"net/url"
)

// SpecsService accesses the specs endpoints.
type SpecsService struct {
	core *core
}

// SpecsUpdateParams are the inputs for SpecsService.Update.
type SpecsUpdateParams struct {
	// IfMatch ETag from a preceding response. The write applies only if the resource still has that version; otherwise it returns 412 precondition_failed without changes. Omit to write the current version. See https://typeship.dev/docs/typeship-api#conditional-writes.
	IfMatch *string `json:"-"`
	// IdempotencyKey Identifies one logical write for 24 hours. The key is scoped to the authenticated organization and operation; generation without an organization uses a hashed network identity. Retrying the same method, path, query, If-Match header, and JSON body replays the original response. Reusing the key with changed intent returns 409. After expiry the key starts a new write.
	IdempotencyKey *string `json:"-"`
}

// SpecsRefreshParams are the inputs for SpecsService.Refresh.
type SpecsRefreshParams struct {
	// IdempotencyKey Identifies one logical write for 24 hours. The key is scoped to the authenticated organization and operation; generation without an organization uses a hashed network identity. Retrying the same method, path, query, If-Match header, and JSON body replays the original response. Reusing the key with changed intent returns 409. After expiry the key starts a new write.
	IdempotencyKey *string `json:"-"`
}

// Get a Spec.
//
// GET /specs/{spec_id}
func (s *SpecsService) Get(ctx context.Context, specID string, opts ...RequestOption) (*Spec, error) {
	req := request{
		Method:     "GET",
		Path:       fmt.Sprintf("/specs/%s", url.PathEscape(specID)),
		Errors:     map[string]func(int, []byte, string) error{"401": newUnauthorizedError, "403": newForbiddenError, "404": newNotFoundError, "429": newRateLimitedError, "500": newInternalServerError},
		Security:   []map[string][]string{{"apiKey": {}}},
		SchemaKey:  "specs.get",
		Idempotent: true,
	}
	var out Spec
	if err := s.core.do(ctx, req, &out, opts...); err != nil {
		return nil, err
	}
	return &out, nil
}

// Update a Spec.
//
// Resolves the source files before saving the update and records a new Spec Revision when the source changes.
// Omitted fields remain unchanged; supplied objects and arrays replace the whole field.
// If the Spec or its Project configuration changes during validation, returns 409 resource_changed without saving the rejected update. Retrieve the current Spec and Project, reconcile your changes,
// and submit a new request with a new Idempotency-Key if using one.
//
// See [conditional writes](https://typeship.dev/docs/typeship-api#conditional-writes) for ETag and If-Match.
//
// PATCH /specs/{spec_id}
func (s *SpecsService) Update(ctx context.Context, specID string, body SpecUpdateRequest, params *SpecsUpdateParams, opts ...RequestOption) (*Spec, error) {
	headers := map[string]string{}
	if params != nil {
		if params.IfMatch != nil {
			headers["If-Match"] = fmt.Sprint(*params.IfMatch)
		}
		if params.IdempotencyKey != nil {
			headers["Idempotency-Key"] = fmt.Sprint(*params.IdempotencyKey)
		}
	}
	req := request{
		Method:            "PATCH",
		Path:              fmt.Sprintf("/specs/%s", url.PathEscape(specID)),
		Headers:           headers,
		Body:              body,
		Errors:            map[string]func(int, []byte, string) error{"400": newBadRequestError, "401": newUnauthorizedError, "403": newForbiddenError, "404": newNotFoundError, "409": newConflictError, "412": newPreconditionFailedError, "422": newUnprocessableEntityError, "429": newRateLimitedError, "500": newInternalServerError},
		Security:          []map[string][]string{{"apiKey": {}}},
		SchemaKey:         "specs.update",
		IdempotencyHeader: "Idempotency-Key",
	}
	var out Spec
	if err := s.core.do(ctx, req, &out, opts...); err != nil {
		return nil, err
	}
	return &out, nil
}

// Refresh a Spec.
//
// Fetches the configured source now and creates a new Spec Revision only when its content changes. Diagnostics then reads that revision. If automatic generation is enabled, refresh queues generation for active Targets even when the source is unchanged. A `502 follow_up_failed` means the new Spec Revision was recorded but generation could not be queued.
//
// POST /specs/{spec_id}/refresh
func (s *SpecsService) Refresh(ctx context.Context, specID string, params *SpecsRefreshParams, opts ...RequestOption) (*Spec, error) {
	headers := map[string]string{}
	if params != nil {
		if params.IdempotencyKey != nil {
			headers["Idempotency-Key"] = fmt.Sprint(*params.IdempotencyKey)
		}
	}
	req := request{
		Method:            "POST",
		Path:              fmt.Sprintf("/specs/%s/refresh", url.PathEscape(specID)),
		Headers:           headers,
		Errors:            map[string]func(int, []byte, string) error{"400": newBadRequestError, "401": newUnauthorizedError, "403": newForbiddenError, "404": newNotFoundError, "409": newConflictError, "422": newUnprocessableEntityError, "429": newRateLimitedError, "500": newInternalServerError, "502": newBadGatewayError},
		Security:          []map[string][]string{{"apiKey": {}}},
		SchemaKey:         "specs.refresh",
		IdempotencyHeader: "Idempotency-Key",
	}
	var out Spec
	if err := s.core.do(ctx, req, &out, opts...); err != nil {
		return nil, err
	}
	return &out, nil
}
