// typeship — specRevisions.
// Generated by typeship — https://typeship.dev — do not edit by hand.
package typeship

import (
	"context"
	"fmt"
	"net/url"
)

// SpecRevisionsService accesses the specRevisions endpoints.
type SpecRevisionsService struct {
	core *core
}

// SpecRevisionsListParams are the inputs for SpecRevisionsService.List.
type SpecRevisionsListParams struct {
	// Limit Maximum number of resources to return.
	Limit *int64 `json:"-"`
	// Cursor Opaque cursor from the preceding page's next_cursor.
	Cursor *string `json:"-"`
}

// List specification revisions.
//
// Immutable snapshots of the exact source text this project consumed, newest first. Raw content is available from each revision's content endpoint and is never embedded in a list response.
//
// GET /projects/{project_id}/spec_revisions
//
// Returns an iterator that fetches pages lazily:
//
//	it := client.SpecRevisions.List(ctx, id, nil)
//	for it.Next() {
//		item := it.Value()
//	}
//	if err := it.Err(); err != nil { ... }
func (s *SpecRevisionsService) List(ctx context.Context, projectID string, params *SpecRevisionsListParams, opts ...RequestOption) *Iter[SpecRevision] {
	query := map[string]any{}
	if params != nil {
		if params.Limit != nil {
			query["limit"] = *params.Limit
		}
		if params.Cursor != nil {
			query["cursor"] = *params.Cursor
		}
	}
	req := request{
		Method:     "GET",
		Path:       fmt.Sprintf("/projects/%s/spec_revisions", url.PathEscape(projectID)),
		Query:      query,
		Errors:     map[string]func(int, []byte, string) error{"400": newBadRequestError, "401": newUnauthorizedError, "403": newForbiddenError, "404": newNotFoundError, "429": newRateLimitedError},
		SchemaKey:  "specRevisions.list",
		Idempotent: true,
	}
	return newIter[SpecRevision](ctx, s.core, req, opts, pageConfig{
		Style:           "cursor",
		ItemsField:      "data",
		CursorParam:     "cursor",
		NextCursorField: "next_cursor",
		HasMoreField:    "has_more",
		LimitParam:      "limit",
	})
}

// Retrieve a specification revision.
//
// Metadata for one immutable source snapshot. Fetch raw source text from the content endpoint so metadata responses stay small and predictable.
//
// GET /spec_revisions/{spec_revision_id}
func (s *SpecRevisionsService) Retrieve(ctx context.Context, specRevisionID string, opts ...RequestOption) (*SpecRevision, error) {
	req := request{
		Method:     "GET",
		Path:       fmt.Sprintf("/spec_revisions/%s", url.PathEscape(specRevisionID)),
		Errors:     map[string]func(int, []byte, string) error{"401": newUnauthorizedError, "403": newForbiddenError, "404": newNotFoundError, "429": newRateLimitedError},
		SchemaKey:  "specRevisions.retrieve",
		Idempotent: true,
	}
	var out SpecRevision
	if err := s.core.do(ctx, req, &out, opts...); err != nil {
		return nil, err
	}
	return &out, nil
}

// RetrieveContent — retrieve a specification revision's raw text.
//
// Returns the exact source text identified by the revision's SHA-256 digest, suitable for saving or piping directly into a diff.
//
// GET /spec_revisions/{spec_revision_id}/content
func (s *SpecRevisionsService) RetrieveContent(ctx context.Context, specRevisionID string, opts ...RequestOption) (string, error) {
	req := request{
		Method:     "GET",
		Path:       fmt.Sprintf("/spec_revisions/%s/content", url.PathEscape(specRevisionID)),
		Errors:     map[string]func(int, []byte, string) error{"401": newUnauthorizedError, "403": newForbiddenError, "404": newNotFoundError, "429": newRateLimitedError},
		SchemaKey:  "specRevisions.retrieveContent",
		Idempotent: true,
	}
	var out string
	if err := s.core.do(ctx, req, &out, opts...); err != nil {
		return "", err
	}
	return out, nil
}
