// typeship — targets.
// Generated by typeship — https://typeship.dev — do not edit by hand.
package typeship

import (
	"context"
	"fmt"
	"net/url"
)

// TargetsService accesses the targets endpoints.
type TargetsService struct {
	core *core
}

// TargetsListParams are the inputs for TargetsService.List.
type TargetsListParams struct {
	// Limit Maximum number of resources to return. Omit for 20; otherwise supply base-10 digits representing an integer from 1 to 100. Empty, malformed, or out-of-range values return 400 invalid_request. List query parameters must appear only once; unrecognized parameters also return 400.
	Limit *int64 `json:"-"`
	// Cursor Opaque cursor from the preceding page's next_cursor. Valid only for the same account, operation, filters, and ordering that issued it. Omit to start at the first page. Empty, malformed, or repeated cursors return 400 invalid_request. The page limit may change between requests.
	Cursor *string `json:"-"`
}

// TargetsCreateParams are the inputs for TargetsService.Create.
type TargetsCreateParams struct {
	// IdempotencyKey Identifies one logical write for 24 hours. The key is scoped to the authenticated account and operation; account-less generation uses a hashed network identity. Retrying the same method, path, query, and JSON body replays the original response. Reusing the key with changed intent returns 409. After expiry the key starts a new write.
	IdempotencyKey *string `json:"-"`
}

// TargetsListReleasesParams are the inputs for TargetsService.ListReleases.
type TargetsListReleasesParams struct {
	// Limit Maximum number of resources to return. Omit for 20; otherwise supply base-10 digits representing an integer from 1 to 100. Empty, malformed, or out-of-range values return 400 invalid_request. List query parameters must appear only once; unrecognized parameters also return 400.
	Limit *int64 `json:"-"`
	// Cursor Opaque cursor from the preceding page's next_cursor. Valid only for the same account, operation, filters, and ordering that issued it. Omit to start at the first page. Empty, malformed, or repeated cursors return 400 invalid_request. The page limit may change between requests.
	Cursor *string `json:"-"`
}

// TargetsAdoptReleaseParams are the inputs for TargetsService.AdoptRelease.
type TargetsAdoptReleaseParams struct {
	// IdempotencyKey Identifies one logical write for 24 hours. The key is scoped to the authenticated account and operation; account-less generation uses a hashed network identity. Retrying the same method, path, query, and JSON body replays the original response. Reusing the key with changed intent returns 409. After expiry the key starts a new write.
	IdempotencyKey *string `json:"-"`
}

// TargetsRepublishReleaseParams are the inputs for TargetsService.RepublishRelease.
type TargetsRepublishReleaseParams struct {
	// IdempotencyKey Identifies one logical write for 24 hours. The key is scoped to the authenticated account and operation; account-less generation uses a hashed network identity. Retrying the same method, path, query, and JSON body replays the original response. Reusing the key with changed intent returns 409. After expiry the key starts a new write.
	IdempotencyKey *string `json:"-"`
}

// List a project's Targets.
//
// GET /projects/{project_id}/targets
//
// Returns an iterator that fetches pages lazily:
//
//	it := client.Targets.List(ctx, id, nil)
//	for it.Next() {
//		item := it.Value()
//	}
//	if err := it.Err(); err != nil { ... }
func (s *TargetsService) List(ctx context.Context, projectID string, params *TargetsListParams, opts ...RequestOption) *Iter[Target] {
	query := map[string]any{}
	if params != nil {
		if params.Limit != nil {
			query["limit"] = *params.Limit
		}
		if params.Cursor != nil {
			query["cursor"] = *params.Cursor
		}
	}
	req := request{
		Method:     "GET",
		Path:       fmt.Sprintf("/projects/%s/targets", url.PathEscape(projectID)),
		Query:      query,
		Errors:     map[string]func(int, []byte, string) error{"400": newBadRequestError, "401": newUnauthorizedError, "403": newForbiddenError, "404": newNotFoundError, "429": newRateLimitedError, "500": newInternalServerError},
		Security:   []map[string][]string{{"apiKey": {}}},
		SchemaKey:  "targets.list",
		Idempotent: true,
	}
	return newIter[Target](ctx, s.core, req, opts, pageConfig{
		Style:           "cursor",
		ItemsField:      "data",
		CursorParam:     "cursor",
		NextCursorField: "next_cursor",
		HasMoreField:    "has_more",
		LimitParam:      "limit",
	})
}

// Create an independently configured Target.
//
// Creates a Target with its own configuration, Deliveries, and release history. Multiple Targets can use the same generator.
//
// POST /projects/{project_id}/targets
func (s *TargetsService) Create(ctx context.Context, projectID string, body TargetFields, params *TargetsCreateParams, opts ...RequestOption) (*TargetResponse, error) {
	headers := map[string]string{}
	if params != nil {
		if params.IdempotencyKey != nil {
			headers["Idempotency-Key"] = fmt.Sprint(*params.IdempotencyKey)
		}
	}
	req := request{
		Method:            "POST",
		Path:              fmt.Sprintf("/projects/%s/targets", url.PathEscape(projectID)),
		Headers:           headers,
		Body:              body,
		Errors:            map[string]func(int, []byte, string) error{"400": newBadRequestError, "401": newUnauthorizedError, "402": newPaymentRequiredError, "403": newForbiddenError, "404": newNotFoundError, "409": newConflictError, "422": newUnprocessableEntityError, "429": newRateLimitedError, "500": newInternalServerError},
		Security:          []map[string][]string{{"apiKey": {}}},
		SchemaKey:         "targets.create",
		IdempotencyHeader: "Idempotency-Key",
	}
	var out TargetResponse
	if err := s.core.do(ctx, req, &out, opts...); err != nil {
		return nil, err
	}
	return &out, nil
}

// Retrieve a Target.
//
// GET /targets/{target_id}
func (s *TargetsService) Retrieve(ctx context.Context, targetID string, opts ...RequestOption) (*TargetResponse, error) {
	req := request{
		Method:     "GET",
		Path:       fmt.Sprintf("/targets/%s", url.PathEscape(targetID)),
		Errors:     map[string]func(int, []byte, string) error{"401": newUnauthorizedError, "403": newForbiddenError, "404": newNotFoundError, "429": newRateLimitedError, "500": newInternalServerError},
		Security:   []map[string][]string{{"apiKey": {}}},
		SchemaKey:  "targets.retrieve",
		Idempotent: true,
	}
	var out TargetResponse
	if err := s.core.do(ctx, req, &out, opts...); err != nil {
		return nil, err
	}
	return &out, nil
}

// Delete an unused Target.
//
// Deletes a Target with no Generation history, release history, or active Draft. Disable a Target instead if it has any of these.
//
// DELETE /targets/{target_id}
func (s *TargetsService) Delete(ctx context.Context, targetID string, opts ...RequestOption) (*DeletedTarget, error) {
	req := request{
		Method:     "DELETE",
		Path:       fmt.Sprintf("/targets/%s", url.PathEscape(targetID)),
		Errors:     map[string]func(int, []byte, string) error{"401": newUnauthorizedError, "403": newForbiddenError, "404": newNotFoundError, "409": newConflictError, "429": newRateLimitedError, "500": newInternalServerError},
		Security:   []map[string][]string{{"apiKey": {}}},
		SchemaKey:  "targets.delete",
		Idempotent: true,
	}
	var out DeletedTarget
	if err := s.core.do(ctx, req, &out, opts...); err != nil {
		return nil, err
	}
	return &out, nil
}

// Update a Target, its Deliveries, or its next reviewed version.
//
// A `502` response means the selected version was saved, but regeneration failed.
//
// PATCH /targets/{target_id}
func (s *TargetsService) Update(ctx context.Context, targetID string, body TargetUpdateRequest, opts ...RequestOption) (*TargetResponse, error) {
	req := request{
		Method:    "PATCH",
		Path:      fmt.Sprintf("/targets/%s", url.PathEscape(targetID)),
		Body:      body,
		Errors:    map[string]func(int, []byte, string) error{"400": newBadRequestError, "401": newUnauthorizedError, "402": newPaymentRequiredError, "403": newForbiddenError, "404": newNotFoundError, "409": newConflictError, "422": newUnprocessableEntityError, "429": newRateLimitedError, "500": newInternalServerError, "502": newBadGatewayError},
		Security:  []map[string][]string{{"apiKey": {}}},
		SchemaKey: "targets.update",
	}
	var out TargetResponse
	if err := s.core.do(ctx, req, &out, opts...); err != nil {
		return nil, err
	}
	return &out, nil
}

// ListReleases — list immutable releases for a Target.
//
// GET /targets/{target_id}/releases
//
// Returns an iterator that fetches pages lazily:
//
//	it := client.Targets.ListReleases(ctx, id, nil)
//	for it.Next() {
//		item := it.Value()
//	}
//	if err := it.Err(); err != nil { ... }
func (s *TargetsService) ListReleases(ctx context.Context, targetID string, params *TargetsListReleasesParams, opts ...RequestOption) *Iter[TargetRelease] {
	query := map[string]any{}
	if params != nil {
		if params.Limit != nil {
			query["limit"] = *params.Limit
		}
		if params.Cursor != nil {
			query["cursor"] = *params.Cursor
		}
	}
	req := request{
		Method:     "GET",
		Path:       fmt.Sprintf("/targets/%s/releases", url.PathEscape(targetID)),
		Query:      query,
		Errors:     map[string]func(int, []byte, string) error{"400": newBadRequestError, "401": newUnauthorizedError, "403": newForbiddenError, "404": newNotFoundError, "429": newRateLimitedError, "500": newInternalServerError},
		Security:   []map[string][]string{{"apiKey": {}}},
		SchemaKey:  "targets.listReleases",
		Idempotent: true,
	}
	return newIter[TargetRelease](ctx, s.core, req, opts, pageConfig{
		Style:           "cursor",
		ItemsField:      "data",
		CursorParam:     "cursor",
		NextCursorField: "next_cursor",
		HasMoreField:    "has_more",
		LimitParam:      "limit",
	})
}

// RetrieveDraft — retrieve a Target's rolling Draft release.
//
// Returns Current's version, the proposed Draft version, readiness, and commit. Pass `revision` as `expected_revision` when updating the Draft to avoid changing a newer candidate.
//
// GET /targets/{target_id}/draft
func (s *TargetsService) RetrieveDraft(ctx context.Context, targetID string, opts ...RequestOption) (*TargetDraftResponse, error) {
	req := request{
		Method:     "GET",
		Path:       fmt.Sprintf("/targets/%s/draft", url.PathEscape(targetID)),
		Errors:     map[string]func(int, []byte, string) error{"401": newUnauthorizedError, "403": newForbiddenError, "404": newNotFoundError, "429": newRateLimitedError, "500": newInternalServerError},
		Security:   []map[string][]string{{"apiKey": {}}},
		SchemaKey:  "targets.retrieveDraft",
		Idempotent: true,
	}
	var out TargetDraftResponse
	if err := s.core.do(ctx, req, &out, opts...); err != nil {
		return nil, err
	}
	return &out, nil
}

// UpdateDraft — select an exact Draft version or return to automatic versioning.
//
// Checks your version choice against the required version bump, then regenerates the existing Draft pull request.
//
// A `502` response means the selected version was saved, but regeneration failed.
//
// PATCH /targets/{target_id}/draft
func (s *TargetsService) UpdateDraft(ctx context.Context, targetID string, body TargetDraftUpdate, opts ...RequestOption) (*TargetDraftResponse, error) {
	req := request{
		Method:    "PATCH",
		Path:      fmt.Sprintf("/targets/%s/draft", url.PathEscape(targetID)),
		Body:      body,
		Errors:    map[string]func(int, []byte, string) error{"400": newBadRequestError, "401": newUnauthorizedError, "403": newForbiddenError, "404": newNotFoundError, "409": newConflictError, "422": newUnprocessableEntityError, "429": newRateLimitedError, "500": newInternalServerError, "502": newBadGatewayError},
		Security:  []map[string][]string{{"apiKey": {}}},
		SchemaKey: "targets.updateDraft",
	}
	var out TargetDraftResponse
	if err := s.core.do(ctx, req, &out, opts...); err != nil {
		return nil, err
	}
	return &out, nil
}

// RetrieveCustomizations — inspect preserved custom code for a Target Draft.
//
// Returns preserved changes, conflicts, reused resolutions, and check results for the Draft. Includes the input and package identifiers needed to compare attempts. Does not include file contents.
//
// GET /targets/{target_id}/customizations
func (s *TargetsService) RetrieveCustomizations(ctx context.Context, targetID string, opts ...RequestOption) (*TargetCustomizationsResponse, error) {
	req := request{
		Method:     "GET",
		Path:       fmt.Sprintf("/targets/%s/customizations", url.PathEscape(targetID)),
		Errors:     map[string]func(int, []byte, string) error{"401": newUnauthorizedError, "403": newForbiddenError, "404": newNotFoundError, "429": newRateLimitedError, "500": newInternalServerError},
		Security:   []map[string][]string{{"apiKey": {}}},
		SchemaKey:  "targets.retrieveCustomizations",
		Idempotent: true,
	}
	var out TargetCustomizationsResponse
	if err := s.core.do(ctx, req, &out, opts...); err != nil {
		return nil, err
	}
	return &out, nil
}

// ResetCustomizations — resolve or reset custom code on the rolling Draft.
//
// Keeps the current or generated side of selected conflicts, or resets all customizations. Reruns integration and checks on the same Draft. Supply the expected head revision to prevent a stale choice from changing a newer Draft.
//
// A `502` response means regeneration failed after the reset commit.
//
// POST /targets/{target_id}/customizations/reset
func (s *TargetsService) ResetCustomizations(ctx context.Context, targetID string, body ResetTargetCustomizations, opts ...RequestOption) (*TargetCustomizationsResponse, error) {
	req := request{
		Method:    "POST",
		Path:      fmt.Sprintf("/targets/%s/customizations/reset", url.PathEscape(targetID)),
		Body:      body,
		Errors:    map[string]func(int, []byte, string) error{"400": newBadRequestError, "401": newUnauthorizedError, "403": newForbiddenError, "404": newNotFoundError, "409": newConflictError, "429": newRateLimitedError, "500": newInternalServerError, "502": newBadGatewayError},
		Security:  []map[string][]string{{"apiKey": {}}},
		SchemaKey: "targets.resetCustomizations",
	}
	var out TargetCustomizationsResponse
	if err := s.core.do(ctx, req, &out, opts...); err != nil {
		return nil, err
	}
	return &out, nil
}

// AdoptRelease — adopt a verified existing package as Current.
//
// Checks the repository tag, package metadata, and registry artifact, then records the package as an Imported Current release. Opens the first Typeship Draft at the next major version; review it to establish the baseline for preserving existing code.
//
// POST /targets/{target_id}/adopt
func (s *TargetsService) AdoptRelease(ctx context.Context, targetID string, body TargetAdoption, params *TargetsAdoptReleaseParams, opts ...RequestOption) (*TargetReleaseResponse, error) {
	headers := map[string]string{}
	if params != nil {
		if params.IdempotencyKey != nil {
			headers["Idempotency-Key"] = fmt.Sprint(*params.IdempotencyKey)
		}
	}
	req := request{
		Method:            "POST",
		Path:              fmt.Sprintf("/targets/%s/adopt", url.PathEscape(targetID)),
		Headers:           headers,
		Body:              body,
		Errors:            map[string]func(int, []byte, string) error{"400": newBadRequestError, "401": newUnauthorizedError, "403": newForbiddenError, "404": newNotFoundError, "409": newConflictError, "422": newUnprocessableEntityError, "429": newRateLimitedError, "500": newInternalServerError},
		Security:          []map[string][]string{{"apiKey": {}}},
		SchemaKey:         "targets.adoptRelease",
		IdempotencyHeader: "Idempotency-Key",
	}
	var out TargetReleaseResponse
	if err := s.core.do(ctx, req, &out, opts...); err != nil {
		return nil, err
	}
	return &out, nil
}

// RetrieveRelease — retrieve an immutable Target release.
//
// GET /target_releases/{target_release_id}
func (s *TargetsService) RetrieveRelease(ctx context.Context, targetReleaseID string, opts ...RequestOption) (*TargetReleaseResponse, error) {
	req := request{
		Method:     "GET",
		Path:       fmt.Sprintf("/target_releases/%s", url.PathEscape(targetReleaseID)),
		Errors:     map[string]func(int, []byte, string) error{"401": newUnauthorizedError, "403": newForbiddenError, "404": newNotFoundError, "429": newRateLimitedError, "500": newInternalServerError},
		Security:   []map[string][]string{{"apiKey": {}}},
		SchemaKey:  "targets.retrieveRelease",
		Idempotent: true,
	}
	var out TargetReleaseResponse
	if err := s.core.do(ctx, req, &out, opts...); err != nil {
		return nil, err
	}
	return &out, nil
}

// RepublishRelease — retry publication of an exact Target release.
//
// Retries publication of the specified release through its repository workflow. Uses that release's version and accepted commit, even if a newer Draft or release exists.
//
// A `502` response means the repository publication workflow could not be dispatched.
//
// POST /target_releases/{target_release_id}/republish
func (s *TargetsService) RepublishRelease(ctx context.Context, targetReleaseID string, params *TargetsRepublishReleaseParams, opts ...RequestOption) (*TargetReleaseResponse, error) {
	headers := map[string]string{}
	if params != nil {
		if params.IdempotencyKey != nil {
			headers["Idempotency-Key"] = fmt.Sprint(*params.IdempotencyKey)
		}
	}
	req := request{
		Method:            "POST",
		Path:              fmt.Sprintf("/target_releases/%s/republish", url.PathEscape(targetReleaseID)),
		Headers:           headers,
		Errors:            map[string]func(int, []byte, string) error{"400": newBadRequestError, "401": newUnauthorizedError, "403": newForbiddenError, "404": newNotFoundError, "409": newConflictError, "429": newRateLimitedError, "500": newInternalServerError, "502": newBadGatewayError},
		Security:          []map[string][]string{{"apiKey": {}}},
		SchemaKey:         "targets.republishRelease",
		IdempotencyHeader: "Idempotency-Key",
	}
	var out TargetReleaseResponse
	if err := s.core.do(ctx, req, &out, opts...); err != nil {
		return nil, err
	}
	return &out, nil
}
