// typeship — targets.
// Generated by typeship — https://typeship.dev — do not edit by hand.
package typeship

import (
	"context"
	"fmt"
	"net/url"
)

// TargetsService accesses the targets endpoints.
type TargetsService struct {
	core *core
}

// TargetsListParams are the inputs for TargetsService.List.
type TargetsListParams struct {
	// Limit Maximum number of resources to return.
	Limit *int64 `json:"-"`
	// Cursor Opaque cursor from the preceding page's next_cursor. Valid only for the same account, operation, filters, and ordering that issued it.
	Cursor *string `json:"-"`
}

// TargetsCreateParams are the inputs for TargetsService.Create.
type TargetsCreateParams struct {
	// IdempotencyKey Identifies one logical write for 24 hours. The key is scoped to the authenticated account and operation; account-less generation uses a hashed network identity. Retrying the same method, path, query, and JSON body replays the original response. Reusing the key with changed intent returns 409. After expiry the key starts a new write.
	IdempotencyKey *string `json:"-"`
}

// TargetsListReleasesParams are the inputs for TargetsService.ListReleases.
type TargetsListReleasesParams struct {
	// Limit Maximum number of resources to return.
	Limit *int64 `json:"-"`
	// Cursor Opaque cursor from the preceding page's next_cursor. Valid only for the same account, operation, filters, and ordering that issued it.
	Cursor *string `json:"-"`
}

// List a project's Targets.
//
// GET /projects/{project_id}/targets
//
// Returns an iterator that fetches pages lazily:
//
//	it := client.Targets.List(ctx, id, nil)
//	for it.Next() {
//		item := it.Value()
//	}
//	if err := it.Err(); err != nil { ... }
func (s *TargetsService) List(ctx context.Context, projectID string, params *TargetsListParams, opts ...RequestOption) *Iter[Target] {
	query := map[string]any{}
	if params != nil {
		if params.Limit != nil {
			query["limit"] = *params.Limit
		}
		if params.Cursor != nil {
			query["cursor"] = *params.Cursor
		}
	}
	req := request{
		Method:     "GET",
		Path:       fmt.Sprintf("/projects/%s/targets", url.PathEscape(projectID)),
		Query:      query,
		Errors:     map[string]func(int, []byte, string) error{"400": newBadRequestError, "401": newUnauthorizedError, "403": newForbiddenError, "404": newNotFoundError, "429": newRateLimitedError},
		SchemaKey:  "targets.list",
		Idempotent: true,
	}
	return newIter[Target](ctx, s.core, req, opts, pageConfig{
		Style:           "cursor",
		ItemsField:      "data",
		CursorParam:     "cursor",
		NextCursorField: "next_cursor",
		HasMoreField:    "has_more",
		LimitParam:      "limit",
	})
}

// Create an independently configured Target.
//
// Several Targets may use the same generator with distinct configuration, Deliveries, and release streams.
//
// POST /projects/{project_id}/targets
func (s *TargetsService) Create(ctx context.Context, projectID string, body TargetFields, params *TargetsCreateParams, opts ...RequestOption) (*TargetResponse, error) {
	headers := map[string]string{}
	if params != nil {
		if params.IdempotencyKey != nil {
			headers["Idempotency-Key"] = fmt.Sprint(*params.IdempotencyKey)
		}
	}
	req := request{
		Method:            "POST",
		Path:              fmt.Sprintf("/projects/%s/targets", url.PathEscape(projectID)),
		Headers:           headers,
		Body:              body,
		Errors:            map[string]func(int, []byte, string) error{"400": newBadRequestError, "401": newUnauthorizedError, "403": newForbiddenError, "404": newNotFoundError, "409": newConflictError, "422": newUnprocessableEntityError, "429": newRateLimitedError},
		SchemaKey:         "targets.create",
		IdempotencyHeader: "Idempotency-Key",
	}
	var out TargetResponse
	if err := s.core.do(ctx, req, &out, opts...); err != nil {
		return nil, err
	}
	return &out, nil
}

// Retrieve a Target.
//
// GET /targets/{target_id}
func (s *TargetsService) Retrieve(ctx context.Context, targetID string, opts ...RequestOption) (*TargetResponse, error) {
	req := request{
		Method:     "GET",
		Path:       fmt.Sprintf("/targets/%s", url.PathEscape(targetID)),
		Errors:     map[string]func(int, []byte, string) error{"401": newUnauthorizedError, "403": newForbiddenError, "404": newNotFoundError, "429": newRateLimitedError},
		SchemaKey:  "targets.retrieve",
		Idempotent: true,
	}
	var out TargetResponse
	if err := s.core.do(ctx, req, &out, opts...); err != nil {
		return nil, err
	}
	return &out, nil
}

// Delete an unused Target.
//
// Targets with Generation or release history, or an active release candidate, must be disabled instead.
//
// DELETE /targets/{target_id}
func (s *TargetsService) Delete(ctx context.Context, targetID string, opts ...RequestOption) (*DeletedTarget, error) {
	req := request{
		Method:     "DELETE",
		Path:       fmt.Sprintf("/targets/%s", url.PathEscape(targetID)),
		Errors:     map[string]func(int, []byte, string) error{"401": newUnauthorizedError, "403": newForbiddenError, "404": newNotFoundError, "409": newConflictError, "429": newRateLimitedError},
		SchemaKey:  "targets.delete",
		Idempotent: true,
	}
	var out DeletedTarget
	if err := s.core.do(ctx, req, &out, opts...); err != nil {
		return nil, err
	}
	return &out, nil
}

// Update a Target, its Deliveries, or its next reviewed version.
//
// PATCH /targets/{target_id}
func (s *TargetsService) Update(ctx context.Context, targetID string, body TargetUpdateRequest, opts ...RequestOption) (*TargetResponse, error) {
	req := request{
		Method:    "PATCH",
		Path:      fmt.Sprintf("/targets/%s", url.PathEscape(targetID)),
		Body:      body,
		Errors:    map[string]func(int, []byte, string) error{"400": newBadRequestError, "401": newUnauthorizedError, "403": newForbiddenError, "404": newNotFoundError, "409": newConflictError, "422": newUnprocessableEntityError, "429": newRateLimitedError},
		SchemaKey: "targets.update",
	}
	var out TargetResponse
	if err := s.core.do(ctx, req, &out, opts...); err != nil {
		return nil, err
	}
	return &out, nil
}

// ListReleases — list immutable releases for a Target.
//
// GET /targets/{target_id}/releases
//
// Returns an iterator that fetches pages lazily:
//
//	it := client.Targets.ListReleases(ctx, id, nil)
//	for it.Next() {
//		item := it.Value()
//	}
//	if err := it.Err(); err != nil { ... }
func (s *TargetsService) ListReleases(ctx context.Context, targetID string, params *TargetsListReleasesParams, opts ...RequestOption) *Iter[TargetRelease] {
	query := map[string]any{}
	if params != nil {
		if params.Limit != nil {
			query["limit"] = *params.Limit
		}
		if params.Cursor != nil {
			query["cursor"] = *params.Cursor
		}
	}
	req := request{
		Method:     "GET",
		Path:       fmt.Sprintf("/targets/%s/releases", url.PathEscape(targetID)),
		Query:      query,
		Errors:     map[string]func(int, []byte, string) error{"400": newBadRequestError, "401": newUnauthorizedError, "403": newForbiddenError, "404": newNotFoundError, "429": newRateLimitedError},
		SchemaKey:  "targets.listReleases",
		Idempotent: true,
	}
	return newIter[TargetRelease](ctx, s.core, req, opts, pageConfig{
		Style:           "cursor",
		ItemsField:      "data",
		CursorParam:     "cursor",
		NextCursorField: "next_cursor",
		HasMoreField:    "has_more",
		LimitParam:      "limit",
	})
}

// RetrieveRelease — retrieve an immutable Target release.
//
// GET /target_releases/{target_release_id}
func (s *TargetsService) RetrieveRelease(ctx context.Context, targetReleaseID string, opts ...RequestOption) (*TargetReleaseResponse, error) {
	req := request{
		Method:     "GET",
		Path:       fmt.Sprintf("/target_releases/%s", url.PathEscape(targetReleaseID)),
		Errors:     map[string]func(int, []byte, string) error{"401": newUnauthorizedError, "403": newForbiddenError, "404": newNotFoundError, "429": newRateLimitedError},
		SchemaKey:  "targets.retrieveRelease",
		Idempotent: true,
	}
	var out TargetReleaseResponse
	if err := s.core.do(ctx, req, &out, opts...); err != nil {
		return nil, err
	}
	return &out, nil
}
