// typeship — usage.
// Generated by typeship — https://typeship.dev — do not edit by hand.
package typeship

import (
	"context"
)

// UsageService accesses the usage endpoints.
type UsageService struct {
	core *core
}

// Retrieve usage for this account.
//
// What this account has consumed and what remains. A hosted generation can cost more than one unit: a project generating TypeScript, Python, and Go consumes three, so callers that would otherwise discover the limit by receiving a 402 can check first.
//
// GET /usage
func (s *UsageService) Retrieve(ctx context.Context, opts ...RequestOption) (*Usage, error) {
	req := request{
		Method:     "GET",
		Path:       "/usage",
		Errors:     map[string]func(int, []byte, string) error{"401": newUnauthorizedError},
		SchemaKey:  "usage.retrieve",
		Idempotent: true,
	}
	var out Usage
	if err := s.core.do(ctx, req, &out, opts...); err != nil {
		return nil, err
	}
	return &out, nil
}
