// typeship — usage.
// Generated by typeship — https://typeship.dev — do not edit by hand.
package typeship

import (
	"context"
)

// UsageService accesses the usage endpoints.
type UsageService struct {
	core *core
}

// Retrieve usage for this account.
//
// Cumulative linked-project generation telemetry, the endpoint allowance for the current plan, and which generated surfaces have called the API. Generations have no count quota; hosted_generations.included and hosted_generations.remaining are always null.
//
// GET /usage
func (s *UsageService) Retrieve(ctx context.Context, opts ...RequestOption) (*Usage, error) {
	req := request{
		Method:     "GET",
		Path:       "/usage",
		Errors:     map[string]func(int, []byte, string) error{"401": newUnauthorizedError},
		SchemaKey:  "usage.retrieve",
		Idempotent: true,
	}
	var out Usage
	if err := s.core.do(ctx, req, &out, opts...); err != nil {
		return nil, err
	}
	return &out, nil
}
