// Runtime validation of JSON bodies against the spec's own schemas.
// Generated by typeship — https://typeship.dev — do not edit by hand.
package typeship

import (
	"encoding/json"
	"fmt"
	"reflect"
	"regexp"
	"strings"
	"unicode/utf8"
)

const maxViolations = 50

// Violation is one place a payload disagreed with the spec.
type Violation struct {
	Path    string
	Message string
}

func (v Violation) String() string { return v.Path + " " + v.Message }

// ValidationError means a request or response body did not match the
// spec's schema. Returned only when the client was built with
// WithValidation; match it with errors.As.
type ValidationError struct {
	// Direction is "request" or "response".
	Direction  string
	Violations []Violation
}

func (e *ValidationError) Error() string {
	shown := make([]string, 0, 3)
	for i, v := range e.Violations {
		if i == 3 {
			break
		}
		shown = append(shown, v.String())
	}
	extra := ""
	if len(e.Violations) > 3 {
		extra = fmt.Sprintf(" (+%d more)", len(e.Violations)-3)
	}
	return e.Direction + " body failed schema validation: " + strings.Join(shown, "; ") + extra
}

func jsonTypeOf(value any) string {
	switch v := value.(type) {
	case nil:
		return "null"
	case bool:
		return "boolean"
	case float64:
		if v == float64(int64(v)) {
			return "integer"
		}
		return "number"
	case string:
		return "string"
	case []any:
		return "array"
	case map[string]any:
		return "object"
	}
	return "unknown"
}

func typeMatches(value any, expected string) bool {
	actual := jsonTypeOf(value)
	switch expected {
	case "number":
		return actual == "number" || actual == "integer"
	case "integer":
		return actual == "integer"
	}
	return actual == expected
}

// validateValue checks a decoded JSON value against the emitted schema
// subset. Constraints outside the subset (formats, multipleOf, not, ...)
// are ignored: validation may miss drift, but must never reject valid
// traffic.
func validateValue(value any, schema any, path string, out *[]Violation, defs map[string]any) {
	if len(*out) >= maxViolations {
		return
	}
	s, ok := schema.(map[string]any)
	if !ok {
		return
	}

	// Named components are deduplicated into defs; recursion is bounded by
	// the data's own depth, so cyclic schemas terminate.
	if ref, ok := s["$ref"].(string); ok {
		validateValue(value, defs[ref], path, out, defs)
		return
	}

	if all, ok := s["allOf"].([]any); ok {
		for _, sub := range all {
			validateValue(value, sub, path, out, defs)
		}
	}
	variants, _ := s["anyOf"].([]any)
	if variants == nil {
		variants, _ = s["oneOf"].([]any)
	}
	if len(variants) > 0 {
		matched := false
		for _, sub := range variants {
			var scratch []Violation
			validateValue(value, sub, path, &scratch, defs)
			if len(scratch) == 0 {
				matched = true
				break
			}
		}
		if !matched {
			*out = append(*out, Violation{path, "matches none of the allowed variants"})
		}
	}

	if declared, present := s["type"]; present {
		var allowed []string
		switch t := declared.(type) {
		case string:
			allowed = []string{t}
		case []any:
			for _, item := range t {
				if name, ok := item.(string); ok {
					allowed = append(allowed, name)
				}
			}
		}
		if nullable, _ := s["nullable"].(bool); nullable && !containsString(allowed, "null") {
			allowed = append(allowed, "null")
		}
		if len(allowed) > 0 {
			ok := false
			for _, name := range allowed {
				if typeMatches(value, name) {
					ok = true
					break
				}
			}
			if !ok {
				*out = append(*out, Violation{path, "expected " + strings.Join(allowed, " | ") + ", got " + jsonTypeOf(value)})
				return // the remaining constraints assume the right type
			}
		}
	}
	if value == nil {
		return
	}

	if enum, ok := s["enum"].([]any); ok {
		found := false
		for _, allowed := range enum {
			if reflect.DeepEqual(allowed, value) {
				found = true
				break
			}
		}
		if !found {
			*out = append(*out, Violation{path, "not one of the allowed enum values"})
		}
	}
	if constant, present := s["const"]; present && !reflect.DeepEqual(constant, value) {
		*out = append(*out, Violation{path, "does not equal the required constant"})
	}

	if number, ok := value.(float64); ok {
		if minimum, ok := s["minimum"].(float64); ok && number < minimum {
			*out = append(*out, Violation{path, fmt.Sprintf("below minimum %v", minimum)})
		}
		if maximum, ok := s["maximum"].(float64); ok && number > maximum {
			*out = append(*out, Violation{path, fmt.Sprintf("above maximum %v", maximum)})
		}
	}

	if text, ok := value.(string); ok {
		if minLength, ok := s["minLength"].(float64); ok && float64(utf8.RuneCountInString(text)) < minLength {
			*out = append(*out, Violation{path, fmt.Sprintf("shorter than minLength %v", minLength)})
		}
		if maxLength, ok := s["maxLength"].(float64); ok && float64(utf8.RuneCountInString(text)) > maxLength {
			*out = append(*out, Violation{path, fmt.Sprintf("longer than maxLength %v", maxLength)})
		}
		if pattern, ok := s["pattern"].(string); ok {
			// An invalid pattern in the spec must never fail valid data.
			if re, err := regexp.Compile(pattern); err == nil && !re.MatchString(text) {
				*out = append(*out, Violation{path, "does not match pattern"})
			}
		}
	}

	if list, ok := value.([]any); ok {
		if minItems, ok := s["minItems"].(float64); ok && float64(len(list)) < minItems {
			*out = append(*out, Violation{path, fmt.Sprintf("fewer than minItems %v", minItems)})
		}
		if maxItems, ok := s["maxItems"].(float64); ok && float64(len(list)) > maxItems {
			*out = append(*out, Violation{path, fmt.Sprintf("more than maxItems %v", maxItems)})
		}
		if items, present := s["items"]; present {
			for i, item := range list {
				if len(*out) >= maxViolations {
					break
				}
				validateValue(item, items, fmt.Sprintf("%s[%d]", path, i), out, defs)
			}
		}
	}

	if object, ok := value.(map[string]any); ok {
		if required, ok := s["required"].([]any); ok {
			for _, item := range required {
				name, ok := item.(string)
				if !ok {
					continue
				}
				if _, present := object[name]; !present {
					*out = append(*out, Violation{path, fmt.Sprintf("missing required property %q", name)})
				}
			}
		}
		if properties, ok := s["properties"].(map[string]any); ok {
			for name, sub := range properties {
				if field, present := object[name]; present {
					validateValue(field, sub, path+"."+name, out, defs)
				}
			}
			if additional, ok := s["additionalProperties"].(bool); ok && !additional {
				for name := range object {
					if _, known := properties[name]; !known {
						*out = append(*out, Violation{path, fmt.Sprintf("unexpected property %q", name)})
					}
				}
			}
		}
	}
}

func containsString(list []string, want string) bool {
	for _, item := range list {
		if item == want {
			return true
		}
	}
	return false
}

// validateBody checks one body and reports what it found. Validation runs
// on the JSON as it goes over the wire, not on the Go structs, so it sees
// exactly what the spec describes.
func (c *core) validateBody(direction, method, path string, payload []byte, schema json.RawMessage) error {
	if len(schema) == 0 || len(payload) == 0 {
		return nil
	}
	var value any
	if err := json.Unmarshal(payload, &value); err != nil {
		return nil // not JSON: nothing the schema can say about it
	}
	var decoded any
	if err := json.Unmarshal(schema, &decoded); err != nil {
		return nil
	}
	var violations []Violation
	validateValue(value, decoded, direction, &violations, schemaDefs)
	if len(violations) == 0 {
		return nil
	}
	err := &ValidationError{Direction: direction, Violations: violations}
	if c.validate == ValidateWarn {
		c.emitDebug(DebugEvent{Method: method, Path: path, Err: err})
		return nil
	}
	if c.onError != nil {
		c.onError(err, method, path)
	}
	return err
}
